# Era Factions / PotPvP local simulation baseline
server-port=25565
server-ip=
online-mode=false
max-players=200
motd=Daegon Reborn | 1.8.8 PotPvP Factions Simulation
level-name=world
level-seed=4920183751
level-type=FLAT
generator-settings=2;7,59x1,3x3,2;1;
generate-structures=false
spawn-protection=0
pvp=true
difficulty=2
hardcore=false
allow-flight=true
allow-nether=true
enable-command-block=false
view-distance=6
max-build-height=256
white-list=false
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
snooper-enabled=false
network-compression-threshold=256
player-idle-timeout=0
