owner:
  claim-first-human: true
  uuid: ''
  name: ''
  ignored-prefixes:
    - Bench
    - DuelBot
    - StateBot
    - Sim
    - Fake
map:
  auto-bootstrap: true
  complete: false
  surface-y: 63
  world-border: 3000
  safezone-radius: 60
  warzone-radius: 250
economy:
  starting-balance: 500.0
pvp:
  pearl-cooldown-seconds: 16
metrics:
  enabled: true
  interval-seconds: 5

creator-tag:
  enabled: true
  head-prefix: '&c[YT] &f'
  chat-prefix: '&c[YT] '
  creators:
    - Stimpy
    - Stimp
    - Marcel
    - PainfulPvP
    - lolitsalex
    - loolitsalex
    - Skimpy
