package dev.jorel.eracore;

import org.bukkit.Material;
import org.bukkit.World;

import java.util.ArrayDeque;
import java.util.Base64;

/**
 * Canonical Phase-2B surface modules reconstructed directly from the five
 * user-supplied HCF reference schematics.
 *
 * The templates intentionally contain the exact visible surface voxel geometry
 * (including AIR) for the selected above-grade reference component. They do not
 * include the references' underground bases or surrounding terrain. This keeps
 * EraCore's authored FreeMap and Phase-3 underground compiler independent while
 * preserving the entrance, glass, roof and facade proportions that define each
 * reference family.
 */
final class HcfSurfaceReferenceTemplates {
    private HcfSurfaceReferenceTemplates() {}

    static final class Template {
        final int width, height, length, yOffset;
        final byte[] rle;
        Template(int width,int height,int length,int yOffset,String encoded) {
            this.width=width;
            this.height=height;
            this.length=length;
            this.yOffset=yOffset;
            this.rle=Base64.getDecoder().decode(encoded);
        }
    }

    // REDEMPTION: 19x21x19, 2758 non-air cells; exact selected surface component.
    private static final Template REDEMPTION=new Template(19,21,19,0,
        "AOgBAAADAAAAEAEAAAMAAAAQAQAAAwAAAFgBAAApAgAAAQMAAAMCAAABAwAAAwIAAAEDAAADAgAAAQMAAAUCAAADAwAAAQIAAAMD" +
        "AAABAgAAAwMAAAECAAADAwAABQIAAA0DAAAHAgAAAQMAAAEEAAABAQAAAQQAAAJhAgABAQAAAQQAAAIBAAABAwAABwIAAAIDAAAB" +
        "AQAAAWECAAIEAAABAQAAAWECAAEBAAACBAAAAgMAAAUCAAADAwAAAQEAAAFhAgADAQAAAQQAAAFhAgABAQAAAQQAAAMDAAAFAgAA" +
        "AgMAAAEEAAACAQAAAmECAAIBAAACBAAAAgMAAAcCAAABAwAAAgEAAAFhAgABBAAAAQEAAAFhAgABAQAAAWECAAEBAAABAwAABwIA" +
        "AAIDAAABBAAAAgEAAAEEAAACAQAAAQQAAAFhAgABBAAAAgMAAAUCAAADAwAAAWECAAEBAAABAwAAAQQAAAFhAgABBAAAAQEAAAFh" +
        "AgABAQAAAwMAAAUCAAABAwAAAwIAAAMBAAACYQIAAQEAAAEEAAACAwAACgIAAAEBAAABYQIAAQQAAAEBAAABBAAAAQEAAAEEAAAB" +
        "AwAACwIAAAkDAAAJAgAAAwMAAAECAAADAwAAAQIAAAMDAAAJAgAAAQMAAAMCAAABAwAAAwIAAAEDAAApAgAAKQAAAAFiAAADAAAA" +
        "AWIAAAMAAAABYgAAAwAAAAFiAAAFAAAAAWIAAAERAAABYgAAAYsAAAFiAAABEQAAAWIAAAGLAAABYgAAAREAAAFiAAABiwAAAWIA" +
        "AAERAAABYgAABQAAAA1iAAAGAAAAAYsAAAFiAAAGAAAAAWsDAAFEAwABCQAAAWIAAAGLAAAGAAAAAmIAAAYAAAABawMAAT8KAAFE" +
        "BAACYgAABQAAAAFiAAABEQAAAWIAAAYAAAABEQAAAWsCAAFrAAABYgAAAREAAAFiAAAFAAAAAmIAAAkAAAACYgAABgAAAAGLAAAB" +
        "YgAACQAAAAFiAAABiwAABgAAAAJiAAAJAAAAAmIAAAUAAAABYgAAAREAAAFiAAABawAAAWsCAAERAAAGAAAAAWIAAAERAAABYgAA" +
        "BQAAAAFiAAADAAAAAWsDAAYAAAACYgAACgAAAAFrAQAGAAAAAWIAAAGLAAAKAAAACWIAAAkAAAABYgAAAREAAAFiAAABiwAAAWIA" +
        "AAERAAABYgAAAYsAAAFiAAABEQAAAWIAAAkAAAABYgAAAwAAAAFiAAADAAAAAWIAAFIAAAABYgAAAwAAAAFiAAADAAAAAWIAAAMA" +
        "AAABYgAABQAAAAFiAAABEQAAAwAAAAERAAADAAAAAREAAAMAAAABEQAAAWIAAAYAAAABYgAAAVUAAANiAAABVQAAA2IAAAFVAAAB" +
        "YgAACAAAAAFVAAAGAAAAAWsDAAIAAAABVQAACAAAAAFiAAAGAAAAAWsDAAIAAAABYgAABgAAAAFiAAABEQAAAWIAAAYAAAABEQAA" +
        "AWsCAAFrAAABYgAAAREAAAFiAAAGAAAAAWIAAAkAAAABYgAACAAAAAFVAAAJAAAAAVUAAAgAAAABYgAACQAAAAFiAAAGAAAAAWIA" +
        "AAERAAABYgAAAWsAAAFrAgABEQAABgAAAAFiAAABEQAAAWIAAAUAAAABYgAAAwAAAAFrAwAGAAAAAWIAAAcAAAABRAMAAwAAAAFr" +
        "AQAGAAAAAVUAAAsAAAACYgAAAVUAAANiAAABVQAAAWIAAAkAAAABRAQAAWIAAAERAAADAAAAAREAAAMAAAABEQAAAWIAAAkAAAAB" +
        "YgAAAwAAAAFiAAADAAAAAWIAAFIAAAABiwAAAwAAAAFDAgADAAAAAUMCAAMAAAABiwAABQAAAAGLAAABEQAAAUMFAAEAAAABQwQA" +
        "AREAAAFDBQABAAAAAUMEAAERAAABQwUAAQAAAAFDBAABEQAAAYsAAAUAAAABQwcAAWIAAAFVAAADYgAAAVUAAANiAAABVQAAASsF" +
        "AAFDBwAHAAAAAVUAAAYAAAABawEAAgAAAAFVAAAHAAAAAUMGAAFiAAAGAAAAAWsBAAIAAAABYgAAAUMGAAUAAAABQwAAAREAAAFi" +
        "AAAGAAAAAREAAAJrAAABYgAAAREAAAFDAQAFAAAAAUMHAAFiAAAJAAAAAWIAAAFDBwAHAAAAAVUAAAkAAAABVQAABwAAAAFDBgAB" +
        "YgAACQAAAAFiAAABQwYABQAAAAGLAAABEQAAAWIAAAJrAgABEQAABgAAAAFiAAABEQAAAUMBAAUAAAABiwAAAwAAAAFrAwAGAAAA" +
        "AWIAAAFDBwAKAAAAAWsDAAYAAAABVQAACwAAAAJiAAABVQAAA2IAAAFVAAABYgAAAUMGAAkAAAABiwAAAREAAAFDBQABAAAAAUME" +
        "AAERAAABQwUAAQAAAAFDBAABEQAAAYsAAAkAAAABiwAAAwAAAAFDAwADAAAAAYsAAFYAAAABiwAAAwAAAAGLAAAKAAAAAREAAANi" +
        "AAABEQAAA2IAAAERAAADYgAAAREAAAYAAAABYgAAAQAAAAliAAABKwUAAWIAAAYAAAACYgAABgAAAAFiAAACAAAAAmIAAAYAAAAC" +
        "YgAABgAAAAFiAAACAAAAAmIAAAUAAAABiwAAAREAAAFiAAAGAAAAAREIAANiAAABEQAAAYsAAAUAAAACYgAACQAAAAJiAAAGAAAA" +
        "AmIAAAkAAAACYgAABgAAAAJiAAAJAAAAAmIAAAYAAAABEQAAA2IAAAERAAAGAAAAAWIAAAERAAABiwAACQAAAAFiAAAGAAAAAmIA" +
        "AAoAAAABYgAABgAAAAJiAAAKAAAAB2IAAAEAAAABYgAACgAAAAERAAADYgAAAREAAANiAAABEQAADgAAAAGLAABWAAAAAW0GAAGL" +
        "AAABAAAAAYsAAAFtBgABiwAAAQAAAAGLAAABbQYAAYsAAAEAAAABiwAAAW0GAAUAAAABbQQAAREAAAMRBAABEQAAAxEEAAERAAAD" +
        "EQQAAREAAAFtBQAEAAAAAYsAAAERCAADYgAAAREIAANiAAABEQgAAmIAAAErBQABEQgAAYsAAAUAAAABEQgAA2IAAAERCAADYgAA" +
        "AREIAAFiAAABYAMAAWIAAAERCAAFAAAAAYsAAAERCAADYgAAAREIAANiAAABEQgAA2IAAAERCAABiwAABAAAAAFtBAABEQAAAxEE" +
        "AAERCAADEQQAAREAAAMRBAABEQAAAW0FAAQAAAABiwAAAREIAANiAAABEQgAA2IAAAERCAADYgAAAREIAAGLAAAFAAAAAREIAANi" +
        "AAABEQgAA2IAAAERCAADYgAAAREIAAUAAAABiwAAAREIAANiAAABEQgAA2IAAAERCAADYgAAAREIAAGLAAAEAAAAAW0EAAERAAAD" +
        "EQQAAREAAAcRBAABEQAAAW0FAAUAAAABbQcAAYsAAAEAAAABLA0AAREIAANiAAABEQgAA2IAAAERCAABiwAACQAAAAERCAADYgAA" +
        "AREIAANiAAABEQgACQAAAAGLAAABEQgAA2IAAAERCAADYgAAAREIAAGLAAAIAAAAAW0EAAERAAADEQQAAREAAAMRBAABEQAAAW0F" +
        "AAkAAAABbQcAAYsAAAEAAAABiwAAAW0HAAGLAAABAAAAAYsAAAFtBwBAAAAAAW0GAAEAAAABbQYAAQAAAAFtBgABAAAAAW0GAAEA" +
        "AAABbQYAAQAAAAFtBgAHAAAAAREAAANiAAABEQAAA2IAAAERAAADYgAAAREAAAUAAAABEQAACAAAAAERAAADYgAAAhEAAAMAAAAB" +
        "bQQAAWIAAAgAAAABawMAAQAAAAGUAAABAAAAAmIAAAFtBQADAAAAAWIAAAgAAAABawEAAgAAAAGUAAACYgAAAwAAAAFtBAABYgAA" +
        "CAAAAAFrAQADAAAAAmIAAAFtBQADAAAAAREAAAgAAAABEQAAAmsAAAFrAgACEQAAAwAAAAFtBAABYgAADQAAAAFiAAABbQUAAwAA" +
        "AAFiAAANAAAAAWIAAAMAAAABbQQAAWIAAA0AAAABYgAAAW0FAAMAAAABEQAADQAAAAERAAAFAAAAAREAAAFiAAABbQcAAREAAAkA" +
        "AAABYgAAAW0FAAcAAAABbQQACQAAAAFiAAAIAAAAAWIAAAkAAAABYgAAAW0FAAcAAAABEQAACQAAAAERAAAJAAAAAREAAANiAAAB" +
        "EQAAA2IAAAERAAALAAAAAW0HAAEAAAABbQcAAQAAAAFtBwABAAAAAW0HAC4AAAABBQAAASsFAAEFAAABiwAAAQUAAAErBQABBQAA" +
        "AYsAAAEFAAABYgAAAQUAAAcAAAABEQAAAwAAAAERAAADAAAAAREAAAMAAAABEQAABQAAAAERAAAIAAAAAREAAAMAAAACEQAAAwAA" +
        "AAEFAAAJAAAAAWsDAAUAAAABBQAAAgAAAAErBQAJAAAAAWsDAAUAAAABYgAAAgAAAAEFAAAJAAAAAWsDAAUAAAABBQAAAwAAAAER" +
        "AAAHAAAAAUQEAAERAAACawAAAWsCAAIRAAABiwAAAgAAAAEFAAAJAAAAAUQDAAUAAAABBQAAAgAAAAErBQAPAAAAAWIAAAIAAAAB" +
        "BQAADwAAAAEFAAADAAAAAREAAA0AAAABEQAAAYsAAAQAAAABEQAAAQUAAAFiAAABEQAACgAAAAEFAAAHAAAAAWIAAAoAAAABYgAA" +
        "BwAAAAEFAAAKAAAAAQUAAAcAAAABEQAACQAAAAERAAAJAAAAAREAAAMAAAABEQAAAwAAAAERAAALAAAAAQUAAAFiAAABBQAAAYsA" +
        "AAEFAAABYgAAAQUAABsAAAABTQQAAQAAAAFNBAABAAAAAU0EAAEAAAABTQQAAQAAAAFNBAABAAAAAU0EAAcAAAABYAQAAQUAAAFV" +
        "AAABBQAAAWAEAAEFAAABVQAAAQUAAAFgBAABBQAAAVUAAAEFAAABYAQABQAAAAFiAAABEQAAAwAAAAERAAADAAAAAREAAAMAAAAB" +
        "EQAAAWIAAAMAAAABYAYAAREAAAgAAAABEQAAAwAAAAIRAAABYAcAAQAAAAFNAgABBQAACQAAAAFrAwAFAAAAAQUAAAFNAQABAAAA" +
        "AVUAAAkAAAABawMABQAAAAFVAAABAAAAAU0CAAEFAAAJAAAAAWsDAAUAAAABBQAAAU0BAAEAAAABYAYAAREAAAgAAAABEQAAA2sA" +
        "AAIRAAABYAcAAQAAAAFNAgABBQAADwAAAAEFAAABTQEAAQAAAAFVAAAPAAAAAVUAAAEAAAABTQIAAQUAAA8AAAABBQAAAU0BAAEA" +
        "AAABYAYAAREAAA0AAAABEQAAAWAHAAMAAAABYgAAAREAAAEFAAABVQAAAREAAAoAAAABBQAAAU0BAAMAAAABYAUAAU0DAAEAAAAB" +
        "VQAACgAAAAFVAAAGAAAAAU0CAAEFAAAKAAAAAQUAAAFNAQAFAAAAAWAGAAERAAAJAAAAAREAAAFgBwAHAAAAAWIAAAERAAADAAAA" +
        "AREAAAMAAAABEQAAAWIAAAkAAAABYAUAAQUAAAFVAAABBQAAAWAFAAEFAAABVQAAAQUAAAFgBQALAAAAAU0DAAEAAAABTQMAAQAA" +
        "AAFNAwABAAAAAU0DABoAAAABbQAAAQUAAAFVAAABBQAAAVUAAAEFAAABVQAAAQUAAAFVAAABBQAAAVUAAAEFAAABbQIABQAAAAFi" +
        "AAABEQAAAwAAAAERAAADAAAAAREAAAMAAAABEQAAAWIAAAMAAAABbQIAAREAAAgAAAABEQAAAwAAAAIRAAABbQEAAgAAAAEFAAAJ" +
        "AAAAAWIAAAUAAAABBQAAAgAAAAFVAAAJAAAAAWIAAAUAAAABVQAAAgAAAAEFAAAJAAAAAWIAAAUAAAABBQAAAgAAAAFVAAABEQAA" +
        "CAAAAAERAAADYgAAAhEAAAFVAAACAAAAAQUAAA8AAAABBQAAAgAAAAFVAAAPAAAAAVUAAAIAAAABBQAADwAAAAEFAAACAAAAAVUA" +
        "AAERAAANAAAAAREAAAFVAAADAAAAAWIAAAERAAABBQAAAVUAAAERAAAKAAAAAQUAAAMAAAABQwcAA2IAAAFVAAAKAAAAAVUAAAUA" +
        "AAABLA0AAWIAAAEFAAAKAAAAAQUAAAYAAAABYgAAAREAAAkAAAABEQAAAW0BAAYAAAABQwQAAWIAAAERAAADAAAAAREAAAMAAAAB" +
        "EQAAAWIAAAkAAAABVQAAAQUAAAFVAAABBQAAAVUAAAEFAAABVQAAAQUAAAFtAwAtAAAAAREAAAliAAABEQAABwAAAAEFAQADAAAA" +
        "AREAAAMAAAABEQAAA2IAAAEFAQAFAAAAAQUBAAERCAADEQQAAREIAAMRBAABEQgAAxEEAAERCAABBQEAARIMAAIAAAABEQAAAhEI" +
        "AANiAAABEQgAA2IAAAERCAADYgAAAREIAAFiAAABEQAAAgAAAAFiAAACEQgAA2IAAAERCAADYgAAAREIAAFiAAABYAEAAWIAAAER" +
        "CAACYgAAAgAAAAFiAAACEQgAA2IAAAERCAADYgAAAREIAANiAAABEQgAAmIAAAIAAAABYgAAAREAAAERCAALEQQAAREIAAERAAAB" +
        "YgAAAgAAAAFiAAACEQgAA2IAAAERCAADYgAAAREIAANiAAABEQgAAmIAAAIAAAABYgAAAhEIAANiAAABEQgAA2IAAAERCAADYgAA" +
        "AREIAAJiAAACAAAAAREAAAIRCAADYgAAAREIAANiAAABEQgAA2IAAAERCAACYgAAAgAAAAESDAABBQEAAREIAAMRBAABEQgABxEE" +
        "AAERCAABEQAAAWIAAAMAAAACBQEAA2IAAAERCAADYgAAAREIAANiAAABEQgAAmIAAAMAAAABEQAAARQAAANiAAABEQgAA2IAAAER" +
        "CAADYgAAAREIAAJiAAAFAAAAAREAAAJiAAABEQgAA2IAAAERCAADYgAAAREIAAFiAAABEQAABgAAAAEUAAABYgAAAREIAAMRBAAB" +
        "EQgAAxEEAAERCAABBQEABwAAAAERAAACBQEAAmIAAAEAAAABEQAAA2IAAAEFAQABEgwACQAAAAESBAABEQAABWIAAAERAAAuAAAA" +
        "AREAAAEFAQABbQEAAQAAAAFtAAABEQAAAW0BAAEAAAABbQAAAQUBAAERAAAHAAAADQUBAAUAAAABBQEAAX4JAAcAAAABEQAAAwAA" +
        "AAG8AAABBQEAARIMAAIAAAABEQAAAQUBAAgAAAABawMAAQAAAAGUAAACAAAAAQUBAAERAAACAAAAAUMEAAEFAQAIAAAAAWsDAAIA" +
        "AAABlAAAAQAAAAIFAQACAAAAAW0AAAEFAQAIAAAAAWsDAAQAAAABBQEAAwAAAAERAAABBQEACAAAAAERAAACawAAAWsCAAERAAAB" +
        "BQEAAW0CAAIAAAABbQAAAQUBAA0AAAABBQEAAWIAAAIAAAABQwQAAQUBAA0AAAABBQEAAREAAAIAAAABEQAAAQUBAA0AAAABBQEA" +
        "AWIAAAIAAAABEgwAAQUBAA0AAAABBQEAAW0DAAMAAAACBQEADAAAAAEFAQAEAAAAAREAAAEUAAAMAAAAAgUBAAUAAAABEQAAAwAA" +
        "AAERAAABNgUAAZIEAAE2BAABkgQAATYEAAERAAACBQEAAREAAAYAAAABFAAAAZEBAAEFAQABAAAAATYFAAGSBAABNgQAAZIEAAE2" +
        "BAABAAAAAgUBAAcAAAABEQAAAgUBAAGGBgAFBQEAAYYGAAEFAQABEgwACQAAAAESDAABEQAAAQAAAAFtAwABEQAAAW0DAAEAAAAB" +
        "EQAAHAAAAAESDAADAAAAAWAEAA0AAAABQwAAAREAAAMAAAABEQAAAwAAAAERAAABQwEABwAAAAGGAAADBQEAARQAAAMFAQABFAAA" +
        "AwUBAAGGAQAFAAAAAYYCAAEFAQAHAAAAAREAAAIAAAABfgkAAQUBAAESDAADAAAAAUMCAAEFAQAIAAAAAWsDAAQAAAABBQEAAUMC" +
        "AAIAAAABEQAAAQUBAAgAAAABawMABAAAAAEFAQABEQAAAwAAAAEUAAAIAAAAAWsDAAQAAAABBQEAAW0HAAEAAAABYAYAAREAAAEF" +
        "AQAIAAAAAREAAAJrAAABawIAAREAAAEUAAAEAAAAARQAAA0AAAABBQEAAWIAAAIAAAABEQAAAQUBAA0AAAABBQEAAREAAAIAAAAB" +
        "QwMAAQUBAA0AAAABBQEAAWIAAAIAAAABEgwAAgUBAAwAAAABFAAABAAAAAGGAgABBQEADAAAAAEFAQABbQYAAwAAAAERAAABFAAA" +
        "DAAAAAEFAQABEQAABQAAAAERAAADAAAAAREAAAE2BQABkgQAATYEAAGSBAABNgQAAREAAAIFAQABQwMABgAAAAEUAAABhgUAAQUB" +
        "AAEAAAABNgUAAZIEAAE2BAABkgQAATYEAAEAAAABBQEAAYYDAAcAAAABEQAAAYYBAAESDAABBQEAAYYGAAMFAQABhgYAAQUBAAGG" +
        "AQABEgwACgAAAAFDAAABEQAAAQAAAAERAAABAAAAAREAAAFDAQAPAAAAAWAFAAwAAAABEgwAEgAAAAERAAABBQEAAQAAAAFtBAAB" +
        "EQAAAW0FAAEAAAABBQEAAREAAAkAAAALBQEABwAAAAGGAgABBQEAAX4JAAUAAAABEQAAAQAAAAGGBAACBQEAARIMAAQAAAABhgIA" +
        "AQUBAAcAAAABawMAAgAAAAGGBAACBQEAAwAAAAERAAABBQEACAAAAAFrAwADAAAAAX4JAAEFAQABEQAAAwAAAAEUAAAIAAAAAWsD" +
        "AAQAAAACBQEAAgAAAAERAAABBQEACAAAAAERAAADawIAAREAAAEFAQAEAAAAARQAAA0AAAABBQEAAW0CAAIAAAABEQAAAQUBAA0A" +
        "AAABBQEAAREAAAFgBwACAAAAAwUBAAsAAAABBQEAAW0DAAIAAAABEgwAAgUBAAwAAAABBQEABQAAAAEFAQAMAAAAAgUBAAMAAAAB" +
        "QwAAAREAAAsAAAACBQEAAREAAAUAAAABEQAAAgAAAAEFAQABEQAAATYFAAGSBAABNgQAAZIEAAE2BAABEQAAAgUBAAcAAAABEQAA" +
        "AwUBAAE2BQABkgQAATYEAAGSBAABNgQAAgUBAAgAAAABQwMAAQAAAAESDAAHBQEAARIMAAwAAAABEQAAAW0HAAERAAABbQcAAREA" +
        "AB4AAAABEgwAEQAAAAFDAAABEQAAAREEAAEFAQABbQIAAQUBAAERBAABEQAAAUMBAAkAAAABhgAACQUBAAGGAQAIAAAAAgUBAAUA" +
        "AAABEQAAAWIAAAIFAQABEgwABgAAAAESBAABBQEABgAAAAERCAACYgAAAgUBAAGGAgADAAAAAREAAAIFAQAHAAAAAREIAANiAAAC" +
        "BQEAAUMCAAIAAAABbQQAAQUBAAgAAAABEQgABGIAAAEFAQABEQAAAgAAAAFtAAABBQEACAAAAAERAAADEQQAAREAAAEFAQABEQgA" +
        "AgAAAAFtBAABBQEADQAAAAIFAQACAAAAAREAAAEFAQANAAAAAQUBAAERAAADAAAAAwUBAAsAAAACBQEAAwAAAAESDAACBQEACwAA" +
        "AAEFAQABEQgABAAAAAEFAQAMAAAAAQUBAAERAAAEAAAAAREAAAsAAAACBQEAAUMDAAUAAAABFAAAAQAAAAF+CQABBQEAAREAAAE2" +
        "BQABkgUAATYEAAGSBAABNgQAAREAAAEFAQABhgMABwAAAAERAAABBQEAARIEAAEFAQABNgUAAZIFAAE2BAABkgQAATYEAAIFAQAL" +
        "AAAAARIMAAYFAQABEgwADAAAAAFDAAABEQAAAW0DAAERAAABQwEAMQAAAAESDAABQwAAAREAAAEAAAABEQAAAUMBAAwAAAABhgAA" +
        "AwUBAAEUAAADBQEAAYYBAAkAAAABfgEAAgUBAAF+CQADAAAAAWIAAAIFAQABfgEABwAAAAESBAACBQEABQAAAAFiAAADBQEAAX4B" +
        "AAQAAAABQwIAAYYCAAIFAQAGAAAAAWIAAAQFAQAEAAAAAREAAAEFAQAIAAAAAWIAAAIAAAACBQEAAYYCAAQAAAABFAAACAAAAAER" +
        "AAAEYgAAAQUBAAFDAgACAAAAAREAAAEFAQANAAAAAQUBAAERAAACAAAAAUMDAAGGAwABBQEADAAAAAEUAAAFAAAAAgUBAAsAAAAB" +
        "BQEAAREAAAQAAAABEgwAAQUBAAsAAAABBQEAAUMDAAQAAAABhgIAAQUBAAoAAAABBQEAAYYDAAUAAAABEQAAAgAAAAGGBgAIAAAA" +
        "AQUBAAcAAAABFAAAAQAAAAMFAQABhgUAAwAAAAGGBAACBQEACAAAAAERAAABhgEAAQAAAAEFAQABhgYAAYYFAAEAAAABhgYAAYYE" +
        "AAEFAQABEgwADAAAAAUFAQABfgEADgAAAAERAAABAAAAAREAADQAAAABEQAAAQUBAAERAAAOAAAAARIEAAGGAAADBQEAAYYBAAwA" +
        "AAABEgwAAgUBAAF+CQACAAAAAQUBAAF+AQAKAAAAARIEAAMFAQADAAAAAwUBAAESBAAHAAAAAX4BAAIFAQAFAAAAAWIAAAMFAQAF" +
        "AAAAAREAAAIFAQAHAAAAAWIAAAEAAAACBQEAARIEAAQAAAABbQQAAQUBAAgAAAABEQAAAmIAAAIFAQABhgIAAwAAAAERAAACBQEA" +
        "DAAAAAEFAQABEQAABAAAAAIFAQALAAAAAQUBAAFtBQAEAAAAAX4BAAEFAQALAAAAAQUBAAERAAAEAAAAARIMAAEFAQAKAAAAAQUB" +
        "AAGGAwAGAAAAAQUBAAoAAAABBQEABgAAAAEsAwAEBQEABgAAAAEFAQABfgEABwAAAAERAAAFBQEAAwAAAAIFAQAJAAAAASwDAAEA" +
        "AAABEgQAAQAAAAIFAQABAAAAAgUBAA8AAAAEBQEADwAAAAERAAABbQcAAREAADQAAAABQwAAAREEAAFDAQAQAAAAAwUBAA4AAAAB" +
        "EgwAAX4BAAMFAQANAAAAAX4BAAMFAQABfgkAAgUBAAISDAAJAAAAARIEAAEFAQABfgkABAAAAAMFAQAGAAAAAUMCAAGGAgACBQEA" +
        "BgAAAAFiAAABAAAAAQUBAAF+AQAFAAAAAREIAAIFAQABfgkABgAAAAERAAABYgAAAgUBAAF+AQAEAAAAAUMDAAGGAwACBQEACQAA" +
        "AAMFAQABQwIABQAAAAIFAQAIAAAAAwUBAAERCAAFAAAAAX4BAAEFAQAIAAAAAwUBAAFDAwAFAAAAARIMAAEFAQAJAAAAAQUBAAcA" +
        "AAABfgEAAQUBAAgAAAABBQEACAAAAAUFAQAFAAAAAQUBAAgAAAABEQAAAQUBAAEAAAABEgwAAX4BAAEFAQACAAAAAgUBAAESDAAN" +
        "AAAAAX4BAAEFAQABhgYAAgUBAA8AAAADBQEAAX4BAA8AAAABQwAAAREEAAFDAQA1AAAAAUMCABIAAAABBQEAEgAAAAEFAQAQAAAA" +
        "ARIMAAF+AQACBQEAAX4BAA0AAAAHBQEACgAAAAF+AQACBQEABAAAAAFiAAACBQEABgAAAAFDAAAEBQEAAX4JAAQAAAABEQAAAWIA" +
        "AAEFAQABfgEABwAAAAISBAACBQEABgAAAAIFAQAJAAAAAX4BAAEFAQAHAAAAAwUBAAFDAQAGAAAAARIMAAEFAQAHAAAAAQUBAAF+" +
        "AQAJAAAAAQUBAAF+CQAGAAAAAQUBAAkAAAABhgAAAwUBAAQAAAABBQEACgAAAAEFAQABEgwAAX4BAAEFAQABhgYAAgAAAAF+CQAB" +
        "BQEACQAAAAEsAwAEAAAABAUBAAESDAAPAAAAAwUBABAAAAABhgAAAQUBAAGGAQARAAAAAUMDAIAAAAABEgwAAX4BAAIFAQABEgwA" +
        "DQAAAAF+AQAFBQEAAX4BAAwAAAADBQEAAhQAAAIFAQALAAAAARIEAAGGAwABBQEAAxQAAAIFAQABfgEACwAAAAESDAABBQEABBQA" +
        "AAIFAQAMAAAAAQUBAAQUAAACBQEAARIEAAsAAAADBQEAAhQAAAIFAQALAAAABAUBAAEUAAACBQEAAX4BAA0AAAABEgwABAUBAAES" +
        "DAAPAAAAAgUBABIAAAABBQEAEgAAAAFDAwAtAAA=");

    // BASE_HCF: 29x20x26, 3976 non-air cells; exact selected surface component.
    private static final Template BASE_HCF=new Template(29,20,26,0,
        "AvKbAAAmAAAAAywFAAIBBgADLAUAEwAAAAIsBQADAQYAAQAAAAFBAwADAQYAAiwFABAAAAABLAUAAgEGAAMFAQACAAAAAwUBAAIB" +
        "BgABLAUADgAAAAFVAAABAQYAAQEAAAMAAAABBQEAAmsAAAEFAQADAAAAAQUBAAEBBgABVQAADAAAAAEsBQABAQYAAQEAAAEFAQAK" +
        "AAAAAgUBAAEBBgABLAUACgAAAAEsBQABAQYAAgUBAAwAAAACBQEAAQEGAAEsBQAIAAAAASwFAAEBBgABBQEAEAAAAAEFAQABAQYA" +
        "ASwFAAcAAAABLAUAAQEGAAEFAQAQAAAAAQUBAAEBBgABLAUABwAAAAEBBgABAQAAAQUBABAAAAACBQEAAQEGAAYAAAABbQIAAQEG" +
        "AAIFAQAQAAAAAgUBAAEBBgABbQIABQAAAAEsDQABAQYAAQUBAAgAAAABIwsAAWsAAAEjCwAHAAAAAQUBAAEBBgABLA0ABgAAAAFr" +
        "AQAJAAAAAWsDAAEAAAABawEACAAAAAFrAQAHAAAAAWsDAAkAAAABIwsAAWsCAAEjCwAIAAAAAWsBAAYAAAABLA0AAQEGAAEFAQAS" +
        "AAAAAQUBAAEBBgABLA0ABQAAAAFtAwABAQYAAgUBABAAAAACBQEAAQEGAAFtAwAGAAAAAQEGAAEBAAABBQEAEAAAAAIFAQABAQYA" +
        "BwAAAAEsBQABAQYAAQUBABAAAAABBQEAAQEGAAEsBQAHAAAAASwFAAEBBgABBQEAEAAAAAEFAQABAQYAASwFAAgAAAABLAUAAQEG" +
        "AAIFAQAMAAAAAgUBAAEBBgABLAUACgAAAAEsBQABAQYAAQEAAAEFAQAKAAAAAQUBAAEBAAABAQYAASwFAAwAAAABVQAAAQEGAAEF" +
        "AQADAAAAAQUBAAFrAgABawAAAQUBAAMAAAABBQEAAQEGAAFVAAAOAAAAASwFAAIBBgADBQEAAgAAAAMFAQACAQYAASwFABAAAAAC" +
        "LAUAAwEGAAFBAgABAAAAAQEGAAEBAAABAQYAAiwFABMAAAADLAUAAgEGAAMsBQBSAAAAAgEGABgAAAADBQEAAQAAAAFBAwADBQEA" +
        "EgAAAAF+CQABAQYABAUBAAIAAAAEBQEAAQEGAAF+CQAOAAAAAVUAAAGGAgABBQEAAwAAAAEFAQACawAAAQUBAAMAAAABBQEAAYYC" +
        "AAFVAAAMAAAAAX4JAAGGAAACBQEACgAAAAIFAQABhgEAAX4JAAsAAAABAQYAAgUBAAwAAAACBQEAAQEGAAoAAAACBQEAEAAAAAIF" +
        "AQAJAAAAAgUBABAAAAACBQEACAAAAAEBBgACBQEAEAAAAAIFAQABAQYACAAAAAIFAQAQAAAAAgUBAAcAAAABKwUAAQEGAAEFAQAI" +
        "AAAAASMLAAFrAAABIwsABwAAAAEFAQABAQYAASsFAAYAAAABawEACQAAAAFrAwABAAAAAWsBAAgAAAABawEABwAAAAFrAwAJAAAA" +
        "ASMLAAFrAgABIwsACAAAAAFrAQAGAAAAASsFAAEBBgABBQEAEgAAAAEFAQABAQYAASsFAAcAAAACBQEAEAAAAAIFAQAIAAAAAQEG" +
        "AAIFAQAQAAAAAgUBAAEBBgAIAAAAAgUBABAAAAACBQEACQAAAAIFAQAQAAAAAgUBAAoAAAABAQYAAgUBAAwAAAACBQEAAQEGAAsA" +
        "AAABfgkAAYYAAAIFAQAKAAAAAgUBAAGGAQABfgkADAAAAAFVAAABhgMAAQUBAAMAAAABBQEAAWsCAAFrAAABBQEAAwAAAAEFAQAB" +
        "hgMAAVUAAA4AAAABfgkAAQEGAAQFAQACAAAABAUBAAEBBgABfgkAEgAAAAMFAQABQQIAAQAAAAMFAQAYAAAAAwEGAFEAAAAIAQYA" +
        "EwAAAAIBBgADBQEAAgAAAAMFAQACAQYAEQAAAAEBBgAEBQEAAgEGAAQFAQABAQYADwAAAAFVAAABAAAAAQUBAAMAAAABBQEAAgEG" +
        "AAEFAQADAAAAAQUBAAEAAAABVQAADgAAAAF+AQABIw8ACgAAAAEjDwABfgEADAAAAAIBBgABBQEAASMPAAwAAAABIw8AAQUBAAIB" +
        "BgAIAAAAAQEGAAIFAQAQAAAAAgUBAAEBBgAHAAAAAQEGAAIFAQAQAAAAAgUBAAEBBgAHAAAAAQEGAAIFAQAQAAAAAgUBAAEBBgAG" +
        "AAAAAW0GAAEAAAABfgEAASMPABAAAAABIw8AAX4BAAEAAAABbQYABQAAAAEsDQABAQYAAQUBAAgAAAABXwsAASMLAAFfCwAHAAAA" +
        "AQUBAAEBBgABLA0ABgAAAAIFAQAIAAAAASMLAAFEAgABIwsABwAAAAIFAQAHAAAAAgUBAAgAAAABXwsAASMLAAFfCwAHAAAAAgUB" +
        "AAYAAAABLA0AAQEGAAEFAQASAAAAAQUBAAEBBgABLA0ABQAAAAFtBwABAAAAAX4BAAEjDwAQAAAAASMPAAF+AQABAAAAAW0HAAYA" +
        "AAABAQYAAgUBABAAAAACBQEAAQEGAAcAAAABAQYAAgUBABAAAAACBQEAAQEGAAcAAAABAQYAAgUBABAAAAACBQEAAQEGAAgAAAAC" +
        "AQYAAQUBAAEjDwAMAAAAASMPAAEFAQACAQYADAAAAAF+AQABIw8ACgAAAAEjDwABfgEADgAAAAFVAAABAAAAAQUBAAMAAAABBQEA" +
        "AgEGAAEFAQADAAAAAQUBAAEAAAABVQAADwAAAAEBBgAEBQEAAgEGAAQFAQABAQYAEQAAAAIBBgADBQEAAgAAAAMFAQACAQYAEwAA" +
        "AAgBBgBQAAAAAVUAAAEsBQACAQYAASwFAAFVAAAWAAAAAwUBAAIAAAADBQEAEwAAAAEBBgAEBQEAAgAAAAQFAQABAQYADwAAAAFV" +
        "AAABAAAAASMPAAMAAAABBQEAAl8AAAEFAQADAAAAASMPAAEAAAABVQAADgAAAAEjDwABBQEACgAAAAEFAQABIw8ADQAAAAEBBgAB" +
        "Iw8AAQUBAAwAAAABBQEAASMPAAEBBgAJAAAAASwNAAFVAAABIw8AEAAAAAEjDwABVQAAASwNAAgAAAACBQEAEAAAAAIFAQAIAAAA" +
        "AQEGAAIFAQAQAAAAAgUBAAEBBgAIAAAAAQUBAAEjDwAQAAAAASMPAAEFAQAHAAAAAW0HAAEBBgABBQEACAAAAANfCwAHAAAAAQUB" +
        "AAEBBgABbQcABQAAAAFgDgABWQAAAQUBAAgAAAABXwsAAQAAAAFfCwAHAAAAAQUBAAFZAAABYA8ABQAAAAFgDgABWQAAAQUBAAgA" +
        "AAADXwsABwAAAAEFAQABWQAAAWAPAAUAAAABbQYAAQEGAAEFAQASAAAAAQUBAAEBBgABbQYABwAAAAEFAQABIw8AEAAAAAEjDwAB" +
        "BQEACAAAAAEBBgACBQEAEAAAAAIFAQABAQYACAAAAAIFAQAQAAAAAgUBAAgAAAABLA0AAVUAAAEjDwAQAAAAASMPAAFVAAABLA0A" +
        "CQAAAAEBBgABIw8AAQUBAAwAAAABBQEAASMPAAEBBgANAAAAASMPAAEFAQAKAAAAAQUBAAEjDwAOAAAAAVUAAAEAAAABIw8AAwAA" +
        "AAEFAQACXwAAAQUBAAMAAAABIw8AAQAAAAFVAAAPAAAAAQEGAAQFAQACAAAABAUBAAEBBgATAAAAAwUBAAIAAAADBQEAFgAAAAFV" +
        "AAABLAUAAgEGAAEsBQABVQAAUQAAAAF8AAABAAAAAgEGAAEAAAABfAAAFQAAAAF+AQABhgQAAZgAAAEFAQACAAAAAQUBAAGYAAAB" +
        "hgUAAX4BABEAAAABfgkAAQEGAAEFAQACIw8AAQUBAAIAAAABBQEAAiMPAAEFAQABAQYAAX4JAA4AAAABfgEAAX4JAAEjDwADAAAA" +
        "AQUBAAJfAAABBQEAAwAAAAEjDwABfgkAAX4BAAwAAAACfgkAASMPAAEFAQAKAAAAAQUBAAEjDwACfgkACgAAAAEsDQABAQYAASMP" +
        "AAEFAQAMAAAAAQUBAAEjDwABAQYAASwNAAkAAAABVQAAASMPABAAAAABIw8AAVUAAAgAAAABLAUAAgUBABAAAAACBQEAASwFAAcA" +
        "AAABAQYAAgUBABAAAAACBQEAAQEGAAcAAAABLA0AAX4JAAEjDwAQAAAAASMPAAF+CQABLA0ACAAAAAEFAQAIAAAAA18LAAcAAAAB" +
        "BQEABwAAAAEsBQABAQYAAQUBAAgAAAABXwsAAQAAAAFfCwAHAAAAAQUBAAEBBgABLAUABQAAAAEsBQABAQYAAQUBAAgAAAADXwsA" +
        "BwAAAAEFAQABAQYAASwFAAcAAAABBQEAEgAAAAEFAQAIAAAAASwNAAF+CQABIw8AEAAAAAEjDwABfgkAASwNAAcAAAABAQYAAgUB" +
        "ABAAAAACBQEAAQEGAAcAAAABLAUAAgUBABAAAAACBQEAASwFAAgAAAABVQAAASMPABAAAAABIw8AAVUAAAkAAAABLA0AAQEGAAEj" +
        "DwABBQEADAAAAAEFAQABIw8AAQEGAAEsDQAKAAAAAn4JAAEjDwABBQEACgAAAAEFAQABIw8AAn4JAAwAAAABfgEAAX4JAAEjDwAD" +
        "AAAAAQUBAAJfAAABBQEAAwAAAAEjDwABfgkAAX4BAA4AAAABfgkAAQEGAAEFAQACIw8AAQUBAAIAAAABBQEAAiMPAAEFAQABAQYA" +
        "AX4JABEAAAABfgEAAYYEAAGYAAABBQEAAgAAAAEFAQABmAAAAYYFAAF+AQAVAAAAAXwAAAEAAAACAQYAAQAAAAF8AABTAAAAAgEG" +
        "ABgAAAACfgEAAYYEAAIAAAABhgUAAn4BABMAAAABAQYAAQUBAAIjDwABBQEAAgAAAAEFAQACIw8AAQUBAAEBBgAQAAAAAQUBAAEj" +
        "DwADfgkAAQUBAAJfAAABBQEAA34JAAEjDwABBQEADQAAAAF+CQABBQEAASMPAAEFAQAKfgkAAwUBAAF+CQAKAAAAAX4JAAEBBgAB" +
        "Iw8AAQUBAAN+CQAGAAAAA34JAAEFAQABIw8AAQEGAAF+CQAJAAAAAVUAAAEjDwADfgkACgAAAAN+CQABIw8AAVUAAAkAAAABhgYA" +
        "ASMPAAJ+CQAMAAAAAn4JAAEjDwABhgYACAAAAAEBBgABhgYAASMPAAJ+CQAMAAAAAn4JAAEjDwABAAAAAQEGAAYAAAABYA4AAVkA" +
        "AAIFAQACfgkADAAAAAJ+CQACBQEAAVkAAAFgDwAGAAAAAW0CAAIFAQACfgkABQAAAANfCwAEAAAAAn4JAAIFAQABbQIABwAAAAJt" +
        "BAABBQEAAn4JAAUAAAABXwsAAQAAAAFfCwAEAAAAAn4JAAEFAQACbQUABwAAAAJtBAABBQEAAn4JAAUAAAADXwsABAAAAAJ+CQAB" +
        "BQEAAm0FAAcAAAABbQMAAgUBAAJ+CQAMAAAAAn4JAAIFAQABbQMABgAAAAFgDgABWQAAAgUBAAJ+CQAMAAAAAn4JAAIFAQABWQAA" +
        "AWAPAAYAAAABAQYAAYYHAAEjDwACfgkADAAAAAJ+CQABIw8AAYYHAAEBBgAIAAAAAYYHAAEjDwACfgkADAAAAAJ+CQABIw8AAYYH" +
        "AAkAAAABVQAAASMPAAN+CQAKAAAAA34JAAEjDwABVQAACQAAAAF+CQABAQYAASMPAAEFAQADfgkABgAAAAN+CQABBQEAASMPAAEB" +
        "BgABfgkACgAAAAF+CQABBQEAASMPAAEFAQAKfgkAAwUBAAF+CQANAAAAAQUBAAEjDwADfgkAAQUBAAJfAAABBQEAA34JAAEjDwAB" +
        "BQEAEAAAAAEBBgABBQEAAiMPAAEFAQACAAAAAQUBAAIjDwABBQEAAQEGABMAAAACfgEAAYYEAAIAAAABhgUAAn4BABgAAAACAQYA" +
        "UwAAAAIsBQACAAAAAiwFABUAAAABLAUACAEGAAEsBQASAAAAAgEGAAMFAAACAQYAAwUAAAIBBgAQAAAAAQEGAAIFAAADfgAAAgEG" +
        "AAN+AAACBQAAAQEGAA4AAAABVQAAAQEGAAEFAAACfgAABgUAAAJ+AAABBQAAAQEGAAFVAAAMAAAAAVUAAAEBBgABBQAAAX4AAAIF" +
        "AAAGIwsAAgUAAAF+AAABBQAAAQEGAAFVAAAKAAAAAX4BAAEBBgABBQAAAX4AAAEFAAADIwsAAV8LAAIjCwABXwsAAyMLAAEFAAAB" +
        "fgAAAQUAAAEBBgABfgEACgAAAAEBBgACBQAAAyMLAAJfCwACIwsAAl8LAAMjCwACBQAAAQEGAAoAAAABAQYAAwUAAAEjCwAEXwsA" +
        "AiMLAARfCwABIwsAAwUAAAEBBgAIAAAAASwFAAEBBgADBQAAASMLAARfCwACIwsABF8LAAEjCwADBQAAAQEGAAEsBQAHAAAAASwN" +
        "AAEBBgADBQAAASMLAANfCwAEIwsAA18LAAEjCwADBQAAAQEGAAEsDQAHAAAAASwNAAEBBgADBQAABiMLAAFgCQAFIwsAAQUAAAF+" +
        "AAABBQAAAQEGAAEsDQAHAAAAASwNAAEBBgADBQAADCMLAAEFAAABfgAAAQUAAAEBBgABLA0ABwAAAAEsDQABAQYAAwUAAAEjCwAD" +
        "XwsABCMLAANfCwABIwsAAQUAAAF+AAABBQAAAQEGAAEsDQAHAAAAASwFAAEBBgADBQAAASMLAARfCwACIwsABF8LAAEjCwABBQAA" +
        "AX4AAAEFAAABAQYAASwFAAgAAAABAQYAAwUAAAEjCwAEXwsAAiMLAARfCwABIwsAAwUAAAEBBgAKAAAAAQEGAAIFAAADIwsAAl8L" +
        "AAIjCwACXwsAAyMLAAIFAAABAQYACgAAAAF+AQABAQYAAQUAAAF+AAABBQAAAyMLAAFfCwACIwsAAV8LAAMjCwABBQAAAX4AAAEF" +
        "AAABAQYAAX4BAAoAAAABVQAAAQEGAAEFAAABfgAAAgUAAAYjCwACBQAAAX4AAAEFAAABAQYAAVUAAAwAAAABVQAAAQEGAAEFAAAC" +
        "fgAABgUAAAJ+AAABBQAAAQEGAAFVAAAOAAAAAQEGAAIFAAAIfgAAAgUAAAEBBgAQAAAAAgEGAAgFAAACAQYAEgAAAAEsBQAIAQYA" +
        "ASwFABUAAAACLAUAAgAAAAIsBQBtAAAAARgCAAGLAAABGAIAAosAAAEYAgABiwAAARgCABMAAAACiwAACAAAAAKLAAAQAAAAAosA" +
        "AAoAAAACiwAADgAAAAGAAgABiwAAAwAAAAYBBgADAAAAAYsAAAGAAgAMAAAAAYAAAAEYAgABiwAAAQAAAAMBBgABBQEAAgAAAAEF" +
        "AQADAQYAAQAAAAGLAAABGAIAAYABAAsAAAACiwAAAQAAAAMBBgABBQEABAAAAAEFAQADAQYAAQAAAAKLAAALAAAAAYsAAAEAAAAC" +
        "AQYAAgUBAAYAAAACBQEAAgEGAAEAAAABiwAACgAAAAEYAQABGAIAAVUAAAEBBgABBQEACgAAAAEFAQABAQYAAVUAAAEYAgABGAEA" +
        "CQAAAAGLAAACAAAAAQEGAAEFAQAKAAAAAQUBAAEBBgACAAAAAYsAAAkAAAABGAEAAQAAAAFVAAABAQYAAQUBAAMAAAABIwsAAWsA" +
        "AAFrAgABIwsAAwAAAAEFAQABAQYAAVUAAAEAAAABGAEACQAAAAGLAAACAAAAAQEGAAEFAQADAAAAAWsBAAIAAAABawMABAAAAAEB" +
        "BgACAAAAAYsAAAkAAAABiwAAAgAAAAEBBgABBQEAAwAAAAFrAQACAAAAAWsDAAQAAAABAQYAAgAAAAGLAAAJAAAAARgBAAEAAAAB" +
        "VQAAAQEGAAEFAQADAAAAASMLAAFrAgABawAAASMLAAMAAAABBQEAAQEGAAFVAAABAAAAARgBAAkAAAABiwAAAgAAAAEBBgABBQEA" +
        "CgAAAAEFAQABAQYAAgAAAAGLAAAJAAAAAhgCAAFVAAABAQYAAQUBAAoAAAABBQEAAQEGAAFVAAACGAIACgAAAAGLAAABAAAAAgEG" +
        "AAIFAQAGAAAAAgUBAAIBBgABAAAAAYsAAAsAAAACiwAAAQAAAAMBBgABBQEABAAAAAEFAQADAQYAAQAAAAKLAAALAAAAAYAAAAEY" +
        "AgABiwAAAQAAAAMBBgABBQEAAgAAAAEFAQADAQYAAQAAAAGLAAABGAIAAYABAAwAAAABgAMAAYsAAAMAAAAGAQYAAwAAAAGLAAAB" +
        "gAMADgAAAAKLAAAKAAAAAosAABAAAAACiwAACAAAAAKLAAATAAAAARgCAAGLAAABGAIAAosAAAEYAgABiwAAARgCAIkAAAABGAIA" +
        "AQAAAAEYAgACAAAAARgCAAEAAAABGAIAUAAAAAEBBgABbQIAAgEGAAFtAgABAQYAEgAAAAEYAgACAAAAAVUAAAFtAAABAQYAAQUB" +
        "AAIAAAABBQEAAQEGAAFtAQABVQAAAgAAAAEYAgAPAAAAAW0CAAIBBgABBQEABAAAAAEFAQACAQYAAW0CABAAAAACAQYAAgUBAAYA" +
        "AAACBQEAAgEGAAwAAAABiwAAAQAAAAFVAAABbQIAAQUBAAoAAAABBQEAAW0CAAFVAAABAAAAAYsAAAwAAAABGAEAAQUBAAoAAAAB" +
        "BQEAARgBAAwAAAABGAEAAQAAAAFVAAABbQMAAQUBAAMAAAABIwsAAWsAAAFrAgABIwsAAwAAAAEFAQABbQMAAVUAAAEAAAABGAEA" +
        "DAAAAAEBBgABBQEAAwAAAAFrAQACAAAAAWsDAAQAAAABAQYADwAAAAEBBgABBQEAAwAAAAFrAQACAAAAAWsDAAQAAAABAQYADAAA" +
        "AAEYAQABAAAAAVUAAAFtAgABBQEAAwAAAAEjCwACawAAASMLAAMAAAABBQEAAW0CAAFVAAABAAAAARgBAAwAAAABGAEAAQUBAAoA" +
        "AAABBQEAARgBAAwAAAABiwAAAQAAAAFVAAABbQMAAQUBAAoAAAABBQEAAW0DAAFVAAABAAAAAYsAAAwAAAACAQYAAgUBAAYAAAAC" +
        "BQEAAgEGABAAAAABbQMAAgEGAAEFAQAEAAAAAQUBAAIBBgABbQMADwAAAAEYAgACAAAAAVUAAAFtAAABAQYAAQUBAAIAAAABBQEA" +
        "AQEGAAFtAQABVQAAAgAAAAEYAgASAAAAAQEGAAFtAwACAQYAAW0DAAEBBgBQAAAAARgCAAEAAAABGAIAAgAAAAEYAgABAAAAARgC" +
        "AIkAAAABiwAAAQAAAAGAAQACLAEAAYAAAAEAAAABiwAAFwAAAAEsCQACAAAAASwJADUAAAABAQYAAQAAAAIBBgABAAAAAQEGABIA" +
        "AAABGAIAAgAAAAFVAAABAAAAAQEGAAEFAQACAAAAAQUBAAEBBgABAAAAAVUAAAIAAAABGAIAEAAAAAEsCQABAAAAAQUBAAQAAAAB" +
        "BQEAAQAAAAEsCQARAAAAAgEGAAIFAQAGAAAAAgUBAAIBBgAMAAAAAYsAAAEAAAABVQAAAQAAAAEFAQAKAAAAAQUBAAEAAAABVQAA" +
        "AQAAAAGLAAAMAAAAARgBAAEFAQAKAAAAAQUBAAEYAQAMAAAAAYADAAEAAAABVQAAAQAAAAEFAQADAAAABCMLAAMAAAABBQEAAQAA" +
        "AAFVAAABAAAAAYADAAwAAAABAQYAAVUAAAEjDwACAAAAASMLAAEAAAABYAoAASMLAAQAAAABAQYADwAAAAEBBgABVQAAASMPAAIA" +
        "AAABIwsAAgAAAAEjCwAEAAAAAQEGAAwAAAABgAIAAQAAAAFVAAABAAAAAQUBAAMAAAAEIwsAAwAAAAEFAQABAAAAAVUAAAEAAAAB" +
        "gAIADAAAAAEYAQABBQEACgAAAAEFAQABGAEADAAAAAGLAAABAAAAAVUAAAEAAAABBQEACgAAAAEFAQABAAAAAVUAAAEAAAABiwAA" +
        "DAAAAAIBBgACBQEABgAAAAIFAQACAQYAEQAAAAEsCQABAAAAAQUBAAQAAAABBQEAAQAAAAEsCQAQAAAAARgCAAIAAAABVQAAAQAA" +
        "AAEBBgABBQEAAgAAAAEFAQABAQYAAQAAAAFVAAACAAAAARgCABIAAAABAQYAAQAAAAIBBgABAAAAAQEGADUAAAABLAkAAgAAAAEs" +
        "CQAXAAAAAYsAAAEAAAABgAEAAiwBAAGAAAABAAAAAYsAAIkAAAABiwAAASwBAAGAAgACgAYAAYACAAEsAQABiwAAFAAAAAIsAQAG" +
        "AAAAAiwBABIAAAABLAEABAAAAAIsCQAEAAAAASwBABAAAAABLAEAAgAAAAEsCQABGAIAAQAAAAIYAgABAAAAARgCAAEsCQACAAAA" +
        "ASwBAA4AAAABGAIAAgAAAAFVAAABLAkAAQEGAAEFAQACfgkAAQUBAAEBBgABLAkAAVUAAAIAAAABGAIADAAAAAEsAQACAAAAASsB" +
        "AAEsDQABLAEAAQUBAAQAAAABBQEAASwBAAEsDQABKwEAAgAAAAEsAQAKAAAAASwBAAIAAAACAQYAAgUBAAYAAAACBQEAAgEGAAIA" +
        "AAABLAEACQAAAAGABAABAAAAAVUAAAEAAAABBQEACgAAAAEFAQABAAAAAVUAAAEAAAABgAUACQAAAAEsCQACAAAAAW0AAAEFAQAK" +
        "AAAAAQUBAAFtAQACAAAAASwJAAkAAAABgAcAAQAAAAFVAAABAAAAAQUBAAQAAAACIwsABAAAAAEFAQABAAAAAVUAAAEAAAABgAcA" +
        "CQAAAAEsAQADAAAAAVUAAAEjDwACAAAAAiMLAAFgCgABIwsAAwAAAAF+CQABAQYAAgAAAAEsAQAJAAAAASwBAAMAAAABVQAAASMP" +
        "AAIAAAAEIwsAAwAAAAF+CQABAQYAAgAAAAEsAQAJAAAAAYAGAAEAAAABVQAAAQAAAAEFAQAEAAAAAiMLAAQAAAABBQEAAQAAAAFV" +
        "AAABAAAAAYAGAAkAAAABLAkAAgAAAAFtAAABBQEACgAAAAEFAQABbQEAAgAAAAEsCQAJAAAAAYAEAAEAAAABVQAAAQAAAAEFAQAK" +
        "AAAAAQUBAAEAAAABVQAAAQAAAAGABQAJAAAAASwBAAIAAAACAQYAAgUBAAYAAAACBQEAAgEGAAIAAAABLAEACgAAAAEsAQACAAAA" +
        "ASsBAAEsDQABLAEAAQUBAAQAAAABBQEAASwBAAEsDQABKwEAAgAAAAEsAQAMAAAAARgCAAIAAAABVQAAASwJAAEBBgABBQEAAn4J" +
        "AAEFAQABAQYAASwJAAFVAAACAAAAARgCAA4AAAABLAEAAgAAAAEsCQABGAIAAQAAAAIYAgABAAAAARgCAAEsCQACAAAAASwBABAA" +
        "AAABLAEABAAAAAIsCQAEAAAAASwBABIAAAACLAEABgAAAAIsAQAUAAAAAYsAAAEsAQABgAMAAoAHAAGAAwABLAEAAYsAAIkAAAAB" +
        "GAIABgAAAAEYAgA1AAAAAlUAABQAAAABgAYABAAAAAEYAgABbQUAAhgCAAFtBAABGAIABAAAAAGABgAMAAAAAYAEAAEYAgABgAUA" +
        "AQAAAAFVAAACAQYAAQUBAAJfCwABBQEAAgEGAAFVAAABAAAAAYAEAAEYAgABgAUADAAAAAGABwACAAAAAQEGAAIFAQAEXwsAAgUB" +
        "AAEBBgACAAAAAYAHAA4AAAABKwEAAQEGAAEFAQAIXwsAAQUBAAEBBgABKwEADgAAAAFVAAABLAUAAQUBAApfCwABBQEAASwFAAFV" +
        "AAALAAAAAYAAAAMAAAABBQEACl8LAAEFAQADAAAAAYABAAgAAAABsQQAAYAAAAEAAAABVQAAASwFAAEFAQAEXwsAAgAAAARfCwAB" +
        "BQEAASwFAAFVAAABAAAAAYABAA0AAAABVQAAASMPAAJfCwAEAAAABF8LAAErAQAQAAAAAVUAAAEjDwACXwsABAAAAARfCwABKwEA" +
        "CwAAAAGxBAABgAAAAQAAAAFVAAABLAUAAQUBAARfCwACAAAABF8LAAEFAQABLAUAAVUAAAEAAAABgAEACQAAAAGAAAADAAAAAQUB" +
        "AApfCwABBQEAAwAAAAGAAQALAAAAAVUAAAEsBQABBQEACl8LAAEFAQABLAUAAVUAAA4AAAABKwEAAQEGAAEFAQAIXwsAAQUBAAEB" +
        "BgABKwEADgAAAAGABgACAAAAAQEGAAIFAQAEXwsAAgUBAAEBBgACAAAAAYAGAAwAAAABgAQAARgCAAGABQABAAAAAVUAAAIBBgAB" +
        "BQEAAl8LAAEFAQACAQYAAVUAAAEAAAABgAQAARgCAAGABQAMAAAAAYAHAAQAAAABGAIAAW0FAAIYAgABbQQAARgCAAQAAAABgAcA" +
        "FAAAAAJVAAA1AAAAARgCAAYAAAABGAIAxgAAAAJVAAAUAAAAAYACAAQAAAABGAIAAW0AAAIYAgABbQEAARgCAAQAAAABgAIADAAA" +
        "AAGAAAABWQAAAYABAAEAAAABVQAAASwFAAEAAAABBQEAATYFAAGSBAABBQEAAQAAAAEsBQABVQAAAQAAAAGAAAABWQAAAYABAAwA" +
        "AAABgAMAAgAAAAEsBQACBQEAAZIFAAE2BQABkgQAATYEAAIFAQABLAUAAgAAAAGAAwAOAAAAASsBAAEsBQACBQEAATYFAAGSBQAC" +
        "AAAAATYEAAGSBQACBQEAASwFAAErAQAOAAAAAVUAAAFtBwADBQEAATYFAAQAAAABkgUAAwUBAAFtBwABVQAADwAAAAEFAQACNgMA" +
        "BgAAAAI2AwABBQEADwAAAAFVAAABbQYAAQUBAAKSAwAGAAAAApIDAAEFAQABbQYAAVUAAA4AAAABKwEAASMPAAI2AwAGAAAAAjYD" +
        "AAEAAAABKwEADwAAAAErAQABIw8AApIDAAYAAAACkgMAAQAAAAErAQAOAAAAAVUAAAFtBwABBQEAAjYDAAYAAAACNgMAAQUBAAFt" +
        "BwABVQAADwAAAAEFAQACkgMABgAAAAKSAwABBQEADwAAAAFVAAABbQYAAwUBAAGSBQAEAAAAATYFAAMFAQABbQYAAVUAAA4AAAAB" +
        "KwEAASwFAAIFAQABkgUAATYFAAIAAAABkgQAATYFAAIFAQABLAUAASsBAA4AAAABgAIAAgAAAAEsBQACBQEAATYFAAGSBQABNgQA" +
        "AZIEAAIFAQABLAUAAgAAAAGAAgAMAAAAAYAAAAFZAAABgAEAAQAAAAFVAAABLAUAAQAAAAEFAQABkgUAATYEAAEFAQABAAAAASwF" +
        "AAFVAAABAAAAAYAAAAFZAAABgAEADAAAAAGAAwAEAAAAARgCAAFtAAACGAIAAW0BAAEYAgAEAAAAAYADABQAAAACVQABAwAAAAJV" +
        "AAAZAAAAAQEGAAEAAAACAQYAAQAAAAEBBgAVAAAAAVUAAAEAAAABLA0AAQUBAAE2BQABkgQAAQUBAAEsDQABAAAAAVUAABQAAAAC" +
        "BQEAAZIFAAE2BQABkgQAATYEAAIFAQASAAAAASwJAAEsDQACBQEAATYFAAGSBQACAAAAATYEAAGSBQACBQEAASwNAAEsCQAOAAAA" +
        "AVUAAAEsAQADBQEAATYFAAQAAAABkgUAAwUBAAEsAQABVQAADgAAAAFtBAABBQEAAjYDAAYAAAACNgMAAQUBAAFtBQAOAAAAAVUA" +
        "AAEsAQABBQEAApIDAAYAAAACkgMAAQUBAAEsAQABVQAADgAAAAEsCQABLAUAAjYDAAYAAAACNgMAASwFAAEsCQAPAAAAASwJAAEs" +
        "BQACkgMABgAAAAKSAwABLAUAASwJAA4AAAABVQAAASwBAAEFAQACNgMABgAAAAI2AwABBQEAASwBAAFVAAAOAAAAAW0EAAEFAQAC" +
        "kgMABgAAAAKSAwABBQEAAW0FAA4AAAABVQAAASwBAAMFAQABkgUABAAAAAE2BQADBQEAASwBAAFVAAAOAAAAASwJAAEsDQACBQEA" +
        "AZIFAAE2BQACAAAAAZIEAAE2BQACBQEAASwNAAEsCQASAAAAAgUBAAE2BQABkgUAATYEAAGSBAACBQEAFAAAAAFVAAABAAAAASwN" +
        "AAEFAQABkgUAATYEAAEFAQABLA0AAQAAAAFVAAAVAAAAAQEGAAEAAAACAQYAAQAAAAEBBgAZAAAAAlUAAQMAAAACVQAAGAAAAAEs" +
        "DQABAQYAAW0GAAIBBgABbQYAAQEGAAEsDQAUAAAAAVUAAAFtBAABAQYAAQUBAAE2BQABkgUAAQUBAAEBBgABbQUAAVUAABEAAAAB" +
        "LAkAAW0GAAIBBgABBQEAAZIFAAE2BQABkgUAATYEAAEFAQACAQYAAW0GAAEsCQAPAAAAARgBAAEBBgACBQEAATYFAAGSBQACAAAA" +
        "ATYEAAGSBQACBQEAAQEGAAEYAQAOAAAAAVUAAAEsDQADBQEAATYFAAQAAAABkgUAAwUBAAEsDQABVQAADgAAAAFtAAABBQEAAjYD" +
        "AAYAAAACNgMAAQUBAAFtAQAOAAAAAVUAAAEsDQABBQEAApIDAAYAAAACkgMAAQUBAAEsDQABVQAADgAAAAEYAQACNgMACAAAAAI2" +
        "AwABGAEADwAAAAEYAQACkgIACAAAAAKSAgABGAEADgAAAAFVAAABLA0AAQUBAAI2AwAGAAAAAjYDAAEFAQABLA0AAVUAAA4AAAAB" +
        "bQAAAQUBAAKSAwAGAAAAApIDAAEFAQABbQEADgAAAAFVAAABLA0AAwUBAAGSBQAEAAAAATYFAAMFAQABLA0AAVUAAA4AAAABGAEA" +
        "AQEGAAIFAQABkgUAATYFAAIAAAABkgUAATYFAAIFAQABAQYAARgBAA8AAAABLAkAAW0HAAIBBgABBQEAATYFAAGSBQABNgUAAZIF" +
        "AAEFAQACAQYAAW0HAAEsCQARAAAAAVUAAAFtBAABAQYAAQUBAAGSBQABNgUAAQUBAAEBBgABbQUAAVUAABQAAAABLA0AAQEGAAFt" +
        "BwACAQYAAW0HAAEBBgABLA0AGAAAAAJVAAECAAAAAWAMAAIsAQABYAwAFgAAAAIsAQAGGAIAAiwBABIAAAABLAEAAhgCAAEAAAAB" +
        "BQEAAgAAAAIFAQACGAIAASwBABAAAAABLAUAARgCAAEAAAACBQEABAAAAAIFAQABAAAAARgCAAEsBQAOAAAAASwFAAEYAgACAAAA" +
        "AQUBAAYAAAADBQEAARgCAAEsBQANAAAAAYAEAAEYAQADBQEABgAAAAMFAQABGAEAAYAFAA0AAAABgAAAARgBAAEFAQAKAAAAAQUB" +
        "AAEYAQABgAEADQAAAAGABAABGAEAAQUBAAoAAAABBQEAARgBAAGABQANAAAAASwFAAErBQAMAAAAASsFAAEsBQANAAAAASwFAAEr" +
        "BQAMAAAAASsFAAEsBQANAAAAAYAEAAEYAQABBQEACgAAAAEFAQABGAEAAYAFAA0AAAABgAAAARgBAAEFAQAKAAAAAQUBAAEYAQAB" +
        "gAEADQAAAAGABAABGAEAAwUBAAYAAAADBQEAARgBAAGABQANAAAAASwFAAEYAgABAAAAAgUBAAYAAAADBQEAARgCAAEsBQAOAAAA" +
        "ASwFAAEYAgADBQEABAAAAAMFAQABGAIAASwFABAAAAABLAEAAhgCAAIFAQACAAAAAgUBAAIYAgABLAEAEgAAAAIsAQAGGAIAAiwB" +
        "ABYAAAABYA0AAiwBAAFgDQEBAAAABCwFABgAAAABLAUABCsFAAEsBQAVAAAAAiwFAAZhAgACLAUAEgAAAAEsBQAKYQIAASwFABAA" +
        "AAABLAUAA2ECAAVfCAAEYQIAASwFAA4AAAABLAUAASsFAANhAgAFXwgABGECAAErBQABLAUADgAAAAEsDQADYQIABV8IAARhAgAB" +
        "LA0ADgAAAAEsBQABKwUAA2ECAAVfCAAEYQIAASsFAAEsBQAOAAAAASwFAANhAgAFXwgABGECAAEsBQAPAAAAASwFAANhAgAFXwgA" +
        "BGECAAEsBQAOAAAAASwFAAErBQADYQIABV8IAARhAgABKwUAASwFAA4AAAABLA0AA2ECAAVfCAAEYQIAASwNAA4AAAABLAUAASsF" +
        "AANhAgAFXwgABGECAAErBQABLAUADgAAAAEsBQADYQIABV8IAARhAgABLAUAEAAAAAEsBQAEYQIAAl8IAARhAgABLAUAEgAAAAIs" +
        "BQAGYQIAAiwFABUAAAABLAUABCsFAAEsBQAYAAAABCwFAVgAAAAELAUAGAAAAAEsBQABYQIAAgAAAAFhAgAYAAAAASwFAARhAgAY" +
        "AAAAASwFAAFhAgACAAAAAWECABgAAAABLAUAA2ECAAFfCAABLAUAFwAAAAEsBQABXwgAAgAAAAFhAgABKwUAFwAAAAJhAgACAAAA" +
        "AWECAAErBQAXAAAAASwFAAFfCAACYQIAAV8IAAEsBQAXAAAAASwFAARhAgAYAAAAASwFAARhAgAYAAAAASwFAARhAgAYAAAAAiwF" +
        "AAJhAgACLAUBzAAAAAIsBQA3AAAAAWECAAIsBQABYQIAGQAAAAFhAgACAAAAAWECABkAAAABYQIAAiwNAAFhAgAZAAAABGECABkA" +
        "AAABYQIAAiwNAAFhAgAZAAAAAWECAAIAAAABYQIAGgAAAAJhAgEUAAA=");

    // MODERN_HCF: 17x9x17, 805 non-air cells; exact selected surface component.
    private static final Template MODERN_HCF=new Template(17,9,17,0,
        "AAECAAABAwAAApsAAAEDAAAFAgAAAQMAAAIFAQABAwAABAIAAAGbAAADBQEAAQMAAAMFAQACAwAAAwUBAAEDAAADAgAAAZsAAAcF" +
        "AQABAwAABAUBAAIDAAACAgAAAZsAAAIFAQABAwAABwUBAAKEAgABBQEAAZsAAAICAAABAwAACgUBAAKEAgABBQEAAZsAAAICAAAB" +
        "AwAAAgUBAAEDAAAEBQEAAQMAAAQFAQACAwAAAgIAAAEDAAACBQEAAgMAAAMFAQACAwAAAwUBAAEDAAABmwAAAgIAAAEDAAACAgAA" +
        "AQMAAAUFAQABAwAAAgUBAAEDAAABBQEAAZsAAAICAAABmwAADQUBAAGbAAACAgAAAZsAAAMFAQALmwAAAgIAAAGbAAADBQEAAZsA" +
        "AAmEAgABmwAAAgIAAAGbAAADBQEAAZsAAAmEAgABmwAAAgIAAAGbAAADBQEAAZsAAAmEAgABmwAAAgIAAAGbAAADBQEAAZsAAAmE" +
        "AgABmwAAAgIAAAGbAAADBQEAC5sAACMCAAABAAAAAZsAAAKgDwABmwAABQAAAAGfCQACoA8AAZ8JAAQAAAABoA8AAwAAAAEFAQAD" +
        "awQAAwUBAAGGAQABAAAAAQUBAAMAAAABoA8ABwAAAAEFAQABhgEAAwAAAAEFAQABmwAAAgAAAAGgDwACRAIAAZsAAAQAAAABawcA" +
        "BAAAAAEFAQADAAAAAZsAAAGSBQABNgQAAaAPAAQAAAABawcABAAAAAEFAQADAAAAAZsAAAGSBQABNgQAAZsAAAQAAAABBQEAAYYB" +
        "AAMAAAABBQEAAZsAAAIAAAABmwAAAn4JAAGbAAABBQEAA2sGAAMFAQABhgEAAQAAAAEFAQABLA8AAgAAAAGbAAACfgEAAZsAAAUA" +
        "AAABnwkAAqAPAAGfCQABAAAAASwPAAIAAAABLA8ADQAAAAEsDwACAAAAASwPAA0AAAABLA8AAgAAAAEsDwANAAAAASwPAAIAAAAB" +
        "LA8ADQAAAAEsDwACAAAAASwPAA0AAAABLA8AAgAAAAEsDwANAAAAASwPAAIAAAABmwAAAwAAAAGbAAAJLA8AAZsAAAYAAAACRAMA" +
        "HAAAAAGbAAACoA8AAZsAAAUAAAABnwkAAqAPAAGfCQAEAAAAAaAPAAMAAAABBQEAA2sEAAIFAQABhgEAAgAAAAEFAQADAAAAAaAP" +
        "AAcAAAABBQEABAAAAAEFAQABmwAAAgAAAAGbAAACAAAAAZsAAAQAAAABawcABAAAAAGgDwADAAAAAZsAAAJ+CQABoA8ABAAAAAFr" +
        "BwAEAAAAAaAPAAMAAAABmwAAAn4BAAGbAAAEAAAAAQUBAAQAAAABBQEAAZsAAAIAAAABLAcAAgAAAAEsBwABBQEAA2sGAAIFAQAB" +
        "hgEAAgAAAAEFAQAMAAAAAZ8JAAKgDwABnwkAnQAAAAGbAAACoA8AAZsAAAUAAAABnwkAAqAPAAGfCQAEAAAAAaAPAAN+CQAEBQEA" +
        "AX0BAAGGAQADAAAAAQUBAAMAAAABmwAAB34JAAEFAQAEAAAAAQUBAAGbAAACAAAAAZsAAAJ+AQABmwAABH4JAAEFAQAEAAAAAaAP" +
        "AAMAAAABLAcAAgAAAAGgDwAEfgkAAQUBAAQAAAABoA8ABgAAAAGbAAAEfgkAAQUBAAQAAAABBQEAAZsAAAYAAAAFBQEAAYYBAAMA" +
        "AAABBQEADAAAAAGfCQACoA8AAZ8JAJ0AAAAEmwAABZwGAAGfCQACoA8AAZ8JAAKcBgACAAAAAZsAAAIAAAABawcACQAAAAEFAQAB" +
        "nAUAAgAAAAEsBwACAAAAAWsHAAQAAAABBQEABAAAAAEFAQABmwAABQAAAAGbAAAEAAAAAQUBAAQAAAABhgQAAZsAAAUAAAABoA8A" +
        "BAAAAAEFAQAEAAAAAYYEAAGbAAAFAAAAAZsAAAQAAAABBQEABAAAAAEFAQABmwAABQAAAAGcBAAJAAAAAQUBAAGcBQAFAAAABpwH" +
        "AAGfCQACoA8AAZ8JAAGcBwABnAUAngAAAAGbAAAFoA8AAZ8JAAKgDwABnwkAAqAPAAUAAAABawcACgAAAAGgDwAFAAAAAWsHAAQA" +
        "AAABBQEABQAAAAGbAAAFAAAAAZsAAAQAAAABoA8ABQAAAAGgDwAFAAAAAaAPAAQAAAABoA8ABQAAAAGgDwAFAAAAAaAPAAQAAAAB" +
        "BQEABQAAAAGbAAAFAAAAAaAPAAoAAAABoA8ABQAAAAagDwABnwkAAqAPAAGfCQACoA8AngAAAAGbAAAFoA8AAZ8JAAKgDwABnwkA" +
        "AqAPAAUAAAABmwAACgAAAAGgDwAFAAAAAZsAAAQAAAABBQEABQAAAAGbAAAFAAAAAZsAAAQAAAABBQEABQAAAAGgDwAFAAAAAaAP" +
        "AAQAAAABBQEABQAAAAGgDwAFAAAAAaAPAAQAAAABBQEABQAAAAGbAAAFAAAAAaAPAAoAAAABoA8ABQAAAAagDwABnwkAAqAPAAGf" +
        "CQACoA8AnAAAAAEsDwAHmwAAAZ8JAAKbAAABnwkAA5sAAAIAAAABLA8ADpsAAAIAAAABLA8ACJsAAAJfDwAEmwAAAgAAAAEsDwAI" +
        "mwAAAl8PAASbAAACAAAAASwPAAibAAACXw8ABJsAAAIAAAABLA8ACJsAAAJfDwAEmwAAAgAAAAEsDwAOmwAAAgAAAAEsDwAHmwAA" +
        "AZ8JAAKbAAABnwkAA5sAAAIAAAABLA8ADpsAAAIAAAAPLA8AgQAAAASfCQANAAAABJ8JAA0AAAABnwkAAgAAAAGfCQANAAAAAZ8J" +
        "AAIAAAABnwkADQAAAAGfCQACAAAAAZ8JAA0AAAABnwkAAgAAAAGfCQANAAAABJ8JAA0AAAAEnwkAnAAA");

    // TUNNEL: 11x12x11, 447 non-air cells; exact selected surface component.
    private static final Template TUNNEL=new Template(11,12,11,1,
        "AAFtAAABEQAAAW0BAAUAAAABbQAAAREAAAFtAQABAAAAAW0DAAJiAAADawQAAmIAAAFtAwADAAAAAWIAAAUAAAABYgAABAAAAAFr" +
        "AwAFAAAAAWsBAAQAAAABawEABQAAAAFrAQAEAAAAAWsBAAUAAAABawMABAAAAAFiAAAFAAAAAWIAAAMAAAABbQIAAmIAAAJrAgAB" +
        "awYAAmIAAAFtAgABAAAAAW0AAAERAAABbQEABQAAAAFtAAABEQAAAW0BAAEAAAABbQMAASUAAAYAAAABbQMABAAAAAMfAQABAAAA" +
        "AR8BAAElAAACAAAAAY8CAAERAAAHAAAAAREAAAGPAQACAAAAAWIAAAFtAgADawQAAW0CAAFiAAAEAAAAAW0AAAUAAAABbQEABAAA" +
        "AAFrAwAFAAAAAWsBAAQAAAABawEABQAAAAFrAQAEAAAAAWsBAAUAAAABawMABAAAAAFtAAAFAAAAAW0BAAQAAAABYgAAAW0DAAJr" +
        "AgABawYAAW0DAAFiAAACAAAAAY8CAAERAAAHAAAAAREAAAGPAQABAAAAAY8DAAcAAAABjwMADAAAAAGPAgABEQAAATIEAAUAAAAB" +
        "MgQAAREAAAGPAQABAAAAATICAAFiAAABbQYAA2sEAAFtBgABYgAAATIBAAMAAAABbQQABQAAAAFtBQAEAAAAAWsDAAUAAAABawEA" +
        "BAAAAAFrAwAFAAAAAWsBAAQAAAABawMABQAAAAFrAQAEAAAAAW0EAAUAAAABbQUAAwAAAAEyAgABYgAAAW0HAANrAgABbQcAAWIA" +
        "AAEyAQABAAAAAY8CAAERAAABMgMABQAAAAEyAwABEQAAAY8BAAEAAAABjwMABwAAAAGPAwAMAAAAAY8CAAERAAABbQYABQAAAAFt" +
        "BgABEQAAAY8BAAEAAAABbQQAAWIAAAFtAgABbQYAAW0CAAFtBgABbQIAAWIAAAFtBQADAAAAAW0AAAUsDQABbQEABAAAAAFtBAAB" +
        "LA0AAwAAAAEsDQABbQUABAAAAAFtAAABLA0AAwAAAAEsDQABbQEABAAAAAFtBAABLA0AAwAAAAEsDQABbQUABAAAAAFtAAAFLA0A" +
        "AW0BAAMAAAABbQQAAWIAAAFtAwABbQcAAW0DAAFtBwABbQMAAWIAAAFtBQABAAAAAY8CAAERAAABbQcABQAAAAFtBwABEQAAAY8B" +
        "AAEAAAABjwMABwAAAAGPAwANAAAAASwFAAGPBAAFAAAAAY8EAAEsBQACAAAAAY8CAAERAAABbQIAAQAAAAFtAgABAAAAAW0CAAER" +
        "AAABjwEAAwAAAAFtAAABYgAAARQAAAFiAAABFAAAAWIAAAFtAQAFAAAAARQAAAMAAAABFAAABQAAAAFtAAABYgAAAwAAAAFiAAAB" +
        "bQEABQAAAAEUAAADAAAAARQAAAUAAAABbQAAAWIAAAEUAAABYgAAARQAAAFiAAABbQEAAwAAAAGPAgABEQAAAW0DAAEAAAABbQMA" +
        "AQAAAAFtAwABEQAAAY8BAAIAAAABLAUABgAAAAGPAwABLAUAGQAAAAGPBAAFAAAAAY8EAAMAAAABjwIAAREAAAJtBgABbQIAAm0G" +
        "AAERAAABjwEAAwAAAAFtBAAFYgAAAW0FAAQAAAABbQQAAWIAAAMAAAABYgAAAW0FAAQAAAABbQAAAWIAAAMAAAABYgAAAW0BAAQA" +
        "AAABbQQAAWIAAAMAAAABYgAAAW0FAAQAAAABbQQABWIAAAFtBQADAAAAAY8CAAERAAACbQcAAW0DAAJtBwABEQAAAY8BAAMAAAAB" +
        "jwMABQAAAAGPAwAaAAAAAY8EAAUAAAABjwQAAwAAAAGPAgABEQAAAW0CAAEAAAABbQYAAQAAAAFtAgABEQAAAY8BAAMAAAABbQAA" +
        "AWIAAAEUAAABYgAAARQAAAFiAAABbQEABQAAAAEUAAADLA0AARQAAAUAAAABbQQAAWIAAAEsDQABAAAAASwNAAFiAAABbQUABQAA" +
        "AAEUAAADLA0AARQAAAUAAAABbQAAAWIAAAEUAAABYgAAARQAAAFiAAABbQEAAwAAAAGPAgABEQAAAW0DAAEAAAABbQcAAQAAAAFt" +
        "AwABEQAAAY8BAAMAAAABjwMABQAAAAGPAwAlAAAAASwFAAIAAAABiwAAAQAAAAGPBAABLAUABAAAAAGPAgABEQAAAW0GAAFtAgAB" +
        "bQYAAREAAAGPAQAFAAAAAW0EAANiAAABbQUABQAAAAGLAAABbQAAAWIAAAEAAAABYgAAAW0BAAGLAAAFAAAAAW0EAANiAAABbQUA" +
        "BQAAAAGPAgABEQAAAW0HAAFtAwABbQcAAREAAAGPAQAEAAAAASwFAAGPAwABAAAAAYsAAAEAAAABjwMAASwFADMAAAABMgUAAQAA" +
        "AAGPBAAFAAAAAY8CAAERAAABbQYAAQAAAAFtBgABEQAAAY8BAAUAAAABbQQAAWIAAAEUAAABYgAAAW0FAAUAAAABMgUAAQAAAAEU" +
        "AAABAAAAARQAAAEAAAABMgUABQAAAAFtBAABYgAAARQAAAFiAAABbQUABQAAAAGPAgABEQAAAW0HAAEAAAABbQcAAREAAAGPAQAF" +
        "AAAAAY8DAAEAAAABMgUAAQAAAAGPAwA2AAAAAY8EAAUAAAABjwIAAREAAAFtAgABbQYAAW0CAAERAAABjwEABQAAAAFtAAACYgAA" +
        "ASwNAAFtAQAGAAAAAW0EAAFiAAABAAAAAWIAAAFtBQAGAAAAAW0AAANiAAABbQEABQAAAAGPAgABEQAAAW0DAAFtBwABbQMAAREA" +
        "AAGPAQAFAAAAAY8DAAMAAAABjwMAPQAAAAEsBQABbQYAAQAAAAFtBgABLAUABgAAAAFtBAADKwUAAW0FAAcAAAADKwUABwAAAAFt" +
        "BAADKwUAAW0FAAYAAAABLAUAAW0HAAEAAAABbQcAASwFAFQAAAABLAUAAQAAAAEsBQATAAAAASwFAAEAAAABLAUAOwAA");

    // CAVE: 13x12x13, 600 non-air cells; exact selected surface component.
    private static final Template CAVE=new Template(13,12,13,1,
        "AAEAAAABogEAATUCAAGiAQABNQEAAwAAAAE1AAABogEAATUCAAGiAQACAAAAATUAAAOfCwADawAAA58LAAE1AQACAAAAAaIBAAGf" +
        "CwAHAAAAAZ8LAAGiAQACAAAAATUDAAGfCwAHAAAAAZ8LAAE1AwADAAAAAWsHAAcAAAABawEABAAAAAFrAwAHAAAAAWsFAAQAAAAB" +
        "awEABwAAAAFrAwADAAAAATUCAAGfCwAHAAAAAZ8LAAE1AgACAAAAAaIBAAGfCwAHAAAAAZ8LAAGiAQACAAAAATUAAAOfCwADawIA" +
        "A58LAAE1AQACAAAAAaIBAAE1AwABogEABQAAAAGiAQABNQMAAaIBABwAAAABogEAAWAEAAGiAQAFAAAAAaIBAAFgBAABogEAAgAA" +
        "AAFgBgADnwsAA2sAAAOfCwABYAcAAgAAAAGiAQABnwsABwAAAAGfCwABogEAAgAAAAFNAgABnwsABwAAAAGfCwAEAAAAAWsDAAcA" +
        "AAABawEABAAAAAFrAQAHAAAAAWsBAAQAAAABawMABwAAAAFrAQADAAAAAU0CAAGfCwAHAAAAAZ8LAAMAAAABogEAAZ8LAAcAAAAB" +
        "nwsAAaIBAAIAAAABYA4AA58LAANrAgADnwsAAWAHAAIAAAABogEAAWANAAGiAQAFAAAAAaIBAAFgBQABogEAHAAAAAGiAQABNQYA" +
        "AaIBAAE1BQADAAAAATUEAAGiAQABNQYAAaIBAAIAAAABNQQAA58LAANrAAADnwsAATUFAAIAAAABogEAAZ8LAAcAAAABnwsAAaIB" +
        "AAIAAAABNQcAAZ8LAAcAAAABnwsAATUHAAMAAAABawMABwAAAAFrAQAEAAAAAWsBAAcAAAABawEABAAAAAFrAwAHAAAAAWsBAAMA" +
        "AAABNQYAAZ8LAAcAAAABnwsAATUGAAIAAAABogEAAZ8LAAcAAAABnwsAAaIBAAIAAAABNQQAA58LAANrAAADnwsAATUFAAIAAAAB" +
        "ogEAATUHAAGiAQAFAAAAAaIBAAE1BwABogEAGwAAAAGiBQABogEACaIFAAGiCQABogUAAQAAAAGiCQAEnwsAAQUAAASfCwABogkA" +
        "AgAAAAGiCQABnwsABwAAAAGfCwABogkAAgAAAAGiCQABnwsABwAAAAGfCwABogkAAgAAAAGiCQABnwsABwAAAAGfCwABogkAAgAA" +
        "AAGiCQABBQAABwAAAAEFAAABogkAAgAAAAGiCQABnwsABwAAAAGfCwABogkAAgAAAAGiCQABnwsABwAAAAGfCwABogkAAgAAAAGi" +
        "CQABnwsABwAAAAGfCwABogkAAgAAAAGiCQAEnwsAAQUAAASfCwABogkAAQAAAAGiBQABogEACaIFAAGiAQABogUAAQAAAAGiCQAJ" +
        "AAAAAaIJAAIAAAABTQMACQAAAAFNAwACAAAAAX4AAAGiCQAHAAAAAaIJAAF+AAABAAAAAU0CAAGiBQABogEAAjUCAAGiAQABNQIA" +
        "AaIBAAI1AgABogEAAaIFAAFNAQACAAAAATUAAAdfCgABNQEABAAAAAE1AAAHXwoAATUBAAQAAAABogEAB18KAAGiAQAEAAAAATUE" +
        "AAdfCgABNQEABAAAAAGiAQAHXwoAAaIBAAQAAAABNQAAB18KAAE1AQAEAAAAATUAAAdfCgABNQEAAgAAAAFNAgABogUAAaIBAAI1" +
        "AwABogEAATUDAAGiAQACNQMAAaIBAAGiBQABTQEAAQAAAAF+AAABogkABwAAAAGiCQABfgAAAwAAAAFNAwAHAAAAAU0DAB4AAAAB" +
        "ogEAAmAEAAGiAQABVQAAAaIBAAJgBAABogEABAAAAAFgBgACnwsAAwAAAAKfCwABYAcABAAAAAFgBgABnwsABQAAAAGfCwABYAcA" +
        "BAAAAAGiAQAHAAAAAaIBAAQAAAABVQAABwAAAAFVAAAEAAAAAaIBAAcAAAABogEABAAAAAFgBgABnwsABQAAAAGfCwABYAcABAAA" +
        "AAFgBgACnwsAAwAAAAKfCwABYAcABAAAAAGiAQACYAUAAaIBAAFVAAABogEAAmAFAAGiAQAuAAAAATUGAAEAAAABNQYABwAAAAGi" +
        "AQACNQYAAaIBAAE1AgABogEAAjUGAAGiAQAEAAAAATUEAAcAAAABNQUABAAAAAE1BAAHAAAAATUFAAMAAAABNQQAAaIBAAcAAAAB" +
        "ogEAATUFAAMAAAABNQAABwAAAAE1AQADAAAAATUEAAGiAQAHAAAAAaIBAAE1BQADAAAAATUEAAcAAAABNQUABAAAAAE1BAAHAAAA" +
        "ATUFAAQAAAABogEAAjUHAAGiAQABNQMAAaIBAAI1BwABogEABwAAAAE1BwABAAAAATUHACEAAAABogkABzUCAAGiCQACAAAAAU0C" +
        "AAGiBQABogEAAgAAAAGiAQABNQIAAaIBAAIAAAABogEAAaIFAAFNAQABAAAAATUAAAEFAAAIAAAAATUBAAIAAAABNQAAAQUAAAgA" +
        "AAABNQEAAgAAAAE1AAABogEABwAAAAGiAQABNQEAAgAAAAE1AAABBQAABwAAAAI1AQACAAAAATUAAAGiAQAHAAAAAaIBAAE1AQAC" +
        "AAAAATUAAAEFAAAIAAAAATUBAAIAAAABNQAAAQUAAAgAAAABNQEAAQAAAAFNAgABogUAAaIBAAIAAAABogEAATUDAAGiAQACAAAA" +
        "AaIBAAGiBQABTQEAAgAAAAGiCQAHNQMAAaIJAAQAAAABTQMABwAAAAFNAwAeAAAAAaIBAAI1AgABogEAATUCAAGiAQACNQIAAaIB" +
        "AAQAAAABNQAABwAAAAE1AQAEAAAAATUAAAcAAAABNQEABAAAAAGiAQAHAAAAAaIBAAQAAAABNQAABwAAAAE1AQAEAAAAAaIBAAcA" +
        "AAABogEABAAAAAE1AAAHAAAAATUBAAQAAAABNQAABwAAAAE1AQAEAAAAAaIBAAI1AwABogEAATUDAAGiAQACNQMAAaIBADgAAAAB" +
        "fgEAAgAAAAF+AQABAAAAAX4BAAIAAAABfgEABQAAAAc1AgAGAAAAATUAAAGiAQABXwYAAV8KAAFfBgABogEAATUBAAUAAAABfgEA" +
        "ATUAAAFfBgABXwoAAaIJAAFfCgABXwYAATUBAAF+AQAFAAAAATUAAAFfCgABogUAAV8GAAGiBQABXwoAATUBAAUAAAABfgEAATUA" +
        "AAFfBgABXwoAAaIJAAFfCgABXwYAATUBAAF+AQAFAAAAATUAAAGiAQABXwYAAV8KAAFfBgABogEAATUBAAYAAAAGNQMAATUBAAUA" +
        "AAABfgEAAgAAAAF+AQABAAAAAX4BAAIAAAABfgEAVQAAAAF+AQABAAAAAX4BAAkAAAACfgEAAQAAAAJ+AQAVAAAAAn4BAAEAAAAC" +
        "fgEACQAAAAF+AQABAAAAAX4BAO8AAA==");

    static Template forFamily(int family) {
        switch(family) {
            case 0: return REDEMPTION;
            case 1: return BASE_HCF;
            case 2: return MODERN_HCF;
            case 3: return TUNNEL;
            case 4: return CAVE;
            default: return BASE_HCF;
        }
    }

    static int width(int family) { return forFamily(family).width; }
    static int height(int family) {
        Template t=forFamily(family);
        return t.height+t.yOffset;
    }
    static int length(int family) { return forFamily(family).length; }

    // Primary player/bot entrance center measured from the same selected
    // schematic components. Offsets are relative to the plan center; Y is
    // relative to surfaceY. These are gate-panel cells, not bounding-box edges.
    static int primaryGateOffsetX(int family) {
        switch(family) {
            case 0: return 4;   // Redemption recessed 2x3 lower gate sheet
            case 1: return -1;  // Base-HCF north 2x2 gate
            case 2: return -1;  // Modern north 3x2 gate
            case 3: return 0;   // Tunnel north 3x3 gate
            case 4: return 0;   // Devhorah north 3x3 gate
            default: return 0;
        }
    }

    static int primaryGateOffsetZ(int family) {
        switch(family) {
            case 0: return -2;
            case 1: return -8;
            case 2: return -7;
            case 3: return -4;
            case 4: return -5;
            default: return 0;
        }
    }

    static int primaryGateOffsetY(int family) {
        // Redemption's lower gate panel begins two blocks above its reference
        // floor; all other selected primary gate sheets begin one above grade
        // after their template vertical offsets are applied.
        return family==0?2:1;
    }

    /**
     * Compare the materialized above-grade reference component against the exact
     * encoded schematic voxels after every queued production operation has run.
     * The surface floor layer is excluded because the functional 3x3 dropdown
     * intentionally cuts that layer; every facade/roof/gate/glass voxel above
     * grade must remain block-and-data exact.
     */
    static String facadeMismatchSample(World world,HcfBasePlan plan) {
        Template t=forFamily(plan.primaryFamily);
        int originX=plan.cx-((t.width-1)/2);
        int originZ=plan.cz-((t.length-1)/2);
        int cursor=0;
        int total=t.width*t.height*t.length;
        StringBuilder out=new StringBuilder();
        int shown=0;

        for(int i=0;i+3<t.rle.length;i+=4) {
            int count=((t.rle[i]&0xff)<<8)|(t.rle[i+1]&0xff);
            int id=t.rle[i+2]&0xff;
            byte data=t.rle[i+3];

            for(int n=0;n<count && cursor<total;n++,cursor++) {
                int x=cursor%t.width;
                int q=cursor/t.width;
                int z=q%t.length;
                int y=q/t.length;
                int worldY=plan.surfaceY+t.yOffset+y;
                if(worldY<=plan.surfaceY) continue;

                org.bukkit.block.Block actual=world.getBlockAt(originX+x,worldY,originZ+z);
                if(actual.getTypeId()!=id || actual.getData()!=data) {
                    if(shown>0) out.append(" | ");
                    out.append("at=").append(originX+x).append(",").append(worldY).append(",").append(originZ+z)
                        .append(" expected=").append(id).append(":").append(data&0xff)
                        .append(" actual=").append(actual.getTypeId()).append(":").append(actual.getData()&0xff);
                    shown++;
                    if(shown>=16) return out.toString();
                }
            }
        }
        return out.toString();
    }

    static int facadeMismatches(World world,HcfBasePlan plan) {
        Template t=forFamily(plan.primaryFamily);
        int originX=plan.cx-((t.width-1)/2);
        int originZ=plan.cz-((t.length-1)/2);
        int cursor=0;
        int total=t.width*t.height*t.length;
        int mismatches=0;

        for(int i=0;i+3<t.rle.length;i+=4) {
            int count=((t.rle[i]&0xff)<<8)|(t.rle[i+1]&0xff);
            int id=t.rle[i+2]&0xff;
            byte data=t.rle[i+3];

            for(int n=0;n<count && cursor<total;n++,cursor++) {
                int x=cursor%t.width;
                int q=cursor/t.width;
                int z=q%t.length;
                int y=q/t.length;

                int worldY=plan.surfaceY+t.yOffset+y;
                if(worldY<=plan.surfaceY) continue;

                org.bukkit.block.Block actual=world.getBlockAt(originX+x,worldY,originZ+z);
                if(actual.getTypeId()!=id || actual.getData()!=data) mismatches++;
            }
        }
        return mismatches;
    }

    /**
     * Queue the exact selected surface component centered on the production
     * plan. RLE traversal order is Y, Z, X and includes AIR so old procedural
     * facade cells cannot survive a rebuild.
     */
    static void queue(ArrayDeque<HcfBaseBuilder.Op> queue,World world,HcfBasePlan plan) {
        Template t=forFamily(plan.primaryFamily);
        int originX=plan.cx-((t.width-1)/2);
        int originZ=plan.cz-((t.length-1)/2);
        int cursor=0;
        int total=t.width*t.height*t.length;

        for(int i=0;i+3<t.rle.length;i+=4) {
            int count=((t.rle[i]&0xff)<<8)|(t.rle[i+1]&0xff);
            int id=t.rle[i+2]&0xff;
            byte data=t.rle[i+3];
            Material material=Material.getMaterial(id);
            if(material==null) material=Material.AIR;

            for(int n=0;n<count && cursor<total;n++,cursor++) {
                int x=cursor%t.width;
                int q=cursor/t.width;
                int z=q%t.length;
                int y=q/t.length;
                queue.add(new HcfBaseBuilder.Op(world,originX+x,plan.surfaceY+t.yOffset+y,originZ+z,material,data));
            }
        }

        // A malformed template must fail visibly rather than silently leave a
        // partial shell. The encoded constants are compile-time data, so this
        // branch is only defensive against accidental future edits.
        if(cursor!=total) {
            throw new IllegalStateException("Incomplete HCF surface template family="+
                plan.primaryFamily+" decoded="+cursor+" expected="+total);
        }
    }
}