package dev.jorel.eracore;

import org.bukkit.Material;
import org.bukkit.World;

import java.util.ArrayDeque;
import java.util.Base64;

/**
 * Canonical Phase-2B surface modules reconstructed directly from the five
 * user-supplied HCF reference schematics.
 *
 * The templates intentionally contain the exact visible surface voxel geometry
 * (including AIR) for the selected above-grade reference component. They do not
 * include the references' underground bases or surrounding terrain. This keeps
 * EraCore's authored FreeMap and Phase-3 underground compiler independent while
 * preserving the entrance, glass, roof and facade proportions that define each
 * reference family.
 */
final class HcfSurfaceReferenceTemplates {
    private HcfSurfaceReferenceTemplates() {}

    static final class Template {
        final int width, height, length, yOffset;
        final byte[] rle;
        Template(int width,int height,int length,int yOffset,String encoded) {
            this.width=width;
            this.height=height;
            this.length=length;
            this.yOffset=yOffset;
            this.rle=Base64.getDecoder().decode(encoded);
        }
    }

    // REDEMPTION: 19x21x19, 2758 non-air cells; exact selected surface component.
    private static final Template REDEMPTION=new Template(19,21,19,0,
        "AOgBAAADAAAAEAEAAAMAAAAQAQAAAwAAAFgBAAApAgAAAQMAAAMCAAABAwAAAwIAAAEDAAADAgAAAQMAAAUCAAADAwAAAQIAAAMD" +
        "AAABAgAAAwMAAAECAAADAwAABQIAAA0DAAAHAgAAAQMAAAEEAAABAQAAAQQAAAJhAgABAQAAAQQAAAIBAAABAwAABwIAAAIDAAAB" +
        "AQAAAWECAAIEAAABAQAAAWECAAEBAAACBAAAAgMAAAUCAAADAwAAAQEAAAFhAgADAQAAAQQAAAFhAgABAQAAAQQAAAMDAAAFAgAA" +
        "AgMAAAEEAAACAQAAAmECAAIBAAACBAAAAgMAAAcCAAABAwAAAgEAAAFhAgABBAAAAQEAAAFhAgABAQAAAWECAAEBAAABAwAABwIA" +
        "AAIDAAABBAAAAgEAAAEEAAACAQAAAQQAAAFhAgABBAAAAgMAAAUCAAADAwAAAWECAAEBAAABAwAAAQQAAAFhAgABBAAAAQEAAAFh" +
        "AgABAQAAAwMAAAUCAAABAwAAAwIAAAMBAAACYQIAAQEAAAEEAAACAwAACgIAAAEBAAABYQIAAQQAAAEBAAABBAAAAQEAAAEEAAAB" +
        "AwAACwIAAAkDAAAJAgAAAwMAAAECAAADAwAAAQIAAAMDAAAJAgAAAQMAAAMCAAABAwAAAwIAAAEDAAApAgAAKQAAAAFiAAADAAAA" +
        "AWIAAAMAAAABYgAAAwAAAAFiAAAFAAAAAWIAAAERAAABYgAAAYsAAAFiAAABEQAAAWIAAAGLAAABYgAAAREAAAFiAAABiwAAAWIA" +
        "AAERAAABYgAABQAAAA1iAAAGAAAAAYsAAAFiAAAGAAAAAWsDAAFEAwABCQAAAWIAAAGLAAAGAAAAAmIAAAYAAAABawMAAT8KAAFE" +
        "BAACYgAABQAAAAFiAAABEQAAAWIAAAYAAAABEQAAAWsCAAFrAAABYgAAAREAAAFiAAAFAAAAAmIAAAkAAAACYgAABgAAAAGLAAAB" +
        "YgAACQAAAAFiAAABiwAABgAAAAJiAAAJAAAAAmIAAAUAAAABYgAAAREAAAFiAAABawAAAWsCAAERAAAGAAAAAWIAAAERAAABYgAA" +
        "BQAAAAFiAAADAAAAAWsDAAYAAAACYgAACgAAAAFrAQAGAAAAAWIAAAGLAAAKAAAACWIAAAkAAAABYgAAAREAAAFiAAABiwAAAWIA" +
        "AAERAAABYgAAAYsAAAFiAAABEQAAAWIAAAkAAAABYgAAAwAAAAFiAAADAAAAAWIAAFIAAAABYgAAAwAAAAFiAAADAAAAAWIAAAMA" +
        "AAABYgAABQAAAAFiAAABEQAAAwAAAAERAAADAAAAAREAAAMAAAABEQAAAWIAAAYAAAABYgAAAVUAAANiAAABVQAAA2IAAAFVAAAB" +
        "YgAACAAAAAFVAAAGAAAAAWsDAAIAAAABVQAACAAAAAFiAAAGAAAAAWsDAAIAAAABYgAABgAAAAFiAAABEQAAAWIAAAYAAAABEQAA" +
        "AWsCAAFrAAABYgAAAREAAAFiAAAGAAAAAWIAAAkAAAABYgAACAAAAAFVAAAJAAAAAVUAAAgAAAABYgAACQAAAAFiAAAGAAAAAWIA" +
        "AAERAAABYgAAAWsAAAFrAgABEQAABgAAAAFiAAABEQAAAWIAAAUAAAABYgAAAwAAAAFrAwAGAAAAAWIAAAcAAAABRAMAAwAAAAFr" +
        "AQAGAAAAAVUAAAsAAAACYgAAAVUAAANiAAABVQAAAWIAAAkAAAABRAQAAWIAAAERAAADAAAAAREAAAMAAAABEQAAAWIAAAkAAAAB" +
        "YgAAAwAAAAFiAAADAAAAAWIAAFIAAAABiwAAAwAAAAFDAgADAAAAAUMCAAMAAAABiwAABQAAAAGLAAABEQAAAUMFAAEAAAABQwQA" +
        "AREAAAFDBQABAAAAAUMEAAERAAABQwUAAQAAAAFDBAABEQAAAYsAAAUAAAABQwcAAWIAAAFVAAADYgAAAVUAAANiAAABVQAAASsF" +
        "AAFDBwAHAAAAAVUAAAYAAAABawEAAgAAAAFVAAAHAAAAAUMGAAFiAAAGAAAAAWsBAAIAAAABYgAAAUMGAAUAAAABQwAAAREAAAFi" +
        "AAAGAAAAAREAAAJrAAABYgAAAREAAAFDAQAFAAAAAUMHAAFiAAAJAAAAAWIAAAFDBwAHAAAAAVUAAAkAAAABVQAABwAAAAFDBgAB" +
        "YgAACQAAAAFiAAABQwYABQAAAAGLAAABEQAAAWIAAAJrAgABEQAABgAAAAFiAAABEQAAAUMBAAUAAAABiwAAAwAAAAFrAwAGAAAA" +
        "AWIAAAFDBwAKAAAAAWsDAAYAAAABVQAACwAAAAJiAAABVQAAA2IAAAFVAAABYgAAAUMGAAkAAAABiwAAAREAAAFDBQABAAAAAUME" +
        "AAERAAABQwUAAQAAAAFDBAABEQAAAYsAAAkAAAABiwAAAwAAAAFDAwADAAAAAYsAAFYAAAABiwAAAwAAAAGLAAAKAAAAAREAAANi" +
        "AAABEQAAA2IAAAERAAADYgAAAREAAAYAAAABYgAAAQAAAAliAAABKwUAAWIAAAYAAAACYgAABgAAAAFiAAACAAAAAmIAAAYAAAAC" +
        "YgAABgAAAAFiAAACAAAAAmIAAAUAAAABiwAAAREAAAFiAAAGAAAAAREIAANiAAABEQAAAYsAAAUAAAACYgAACQAAAAJiAAAGAAAA" +
        "AmIAAAkAAAACYgAABgAAAAJiAAAJAAAAAmIAAAYAAAABEQAAA2IAAAERAAAGAAAAAWIAAAERAAABiwAACQAAAAFiAAAGAAAAAmIA" +
        "AAoAAAABYgAABgAAAAJiAAAKAAAAB2IAAAEAAAABYgAACgAAAAERAAADYgAAAREAAANiAAABEQAADgAAAAGLAABWAAAAAW0GAAGL" +
        "AAABAAAAAYsAAAFtBgABiwAAAQAAAAGLAAABbQYAAYsAAAEAAAABiwAAAW0GAAUAAAABbQQAAREAAAMRBAABEQAAAxEEAAERAAAD" +
        "EQQAAREAAAFtBQAEAAAAAYsAAAERCAADYgAAAREIAANiAAABEQgAAmIAAAErBQABEQgAAYsAAAUAAAABEQgAA2IAAAERCAADYgAA" +
        "AREIAAFiAAABYAMAAWIAAAERCAAFAAAAAYsAAAERCAADYgAAAREIAANiAAABEQgAA2IAAAERCAABiwAABAAAAAFtBAABEQAAAxEE" +
        "AAERCAADEQQAAREAAAMRBAABEQAAAW0FAAQAAAABiwAAAREIAANiAAABEQgAA2IAAAERCAADYgAAAREIAAGLAAAFAAAAAREIAANi" +
        "AAABEQgAA2IAAAERCAADYgAAAREIAAUAAAABiwAAAREIAANiAAABEQgAA2IAAAERCAADYgAAAREIAAGLAAAEAAAAAW0EAAERAAAD" +
        "EQQAAREAAAcRBAABEQAAAW0FAAUAAAABbQcAAYsAAAEAAAABLA0AAREIAANiAAABEQgAA2IAAAERCAABiwAACQAAAAERCAADYgAA" +
        "AREIAANiAAABEQgACQAAAAGLAAABEQgAA2IAAAERCAADYgAAAREIAAGLAAAIAAAAAW0EAAERAAADEQQAAREAAAMRBAABEQAAAW0F" +
        "AAkAAAABbQcAAYsAAAEAAAABiwAAAW0HAAGLAAABAAAAAYsAAAFtBwBAAAAAAW0GAAEAAAABbQYAAQAAAAFtBgABAAAAAW0GAAEA" +
        "AAABbQYAAQAAAAFtBgAHAAAAAREAAANiAAABEQAAA2IAAAERAAADYgAAAREAAAUAAAABEQAACAAAAAERAAADYgAAAhEAAAMAAAAB" +
        "bQQAAWIAAAgAAAABawMAAQAAAAGUAAABAAAAAmIAAAFtBQADAAAAAWIAAAgAAAABawEAAgAAAAGUAAACYgAAAwAAAAFtBAABYgAA" +
        "CAAAAAFrAQADAAAAAmIAAAFtBQADAAAAAREAAAgAAAABEQAAAmsAAAFrAgACEQAAAwAAAAFtBAABYgAADQAAAAFiAAABbQUAAwAA" +
        "AAFiAAANAAAAAWIAAAMAAAABbQQAAWIAAA0AAAABYgAAAW0FAAMAAAABEQAADQAAAAERAAAFAAAAAREAAAFiAAABbQcAAREAAAkA" +
        "AAABYgAAAW0FAAcAAAABbQQACQAAAAFiAAAIAAAAAWIAAAkAAAABYgAAAW0FAAcAAAABEQAACQAAAAERAAAJAAAAAREAAANiAAAB" +
        "EQAAA2IAAAERAAALAAAAAW0HAAEAAAABbQcAAQAAAAFtBwABAAAAAW0HAC4AAAABBQAAASsFAAEFAAABiwAAAQUAAAErBQABBQAA" +
        "AYsAAAEFAAABYgAAAQUAAAcAAAABEQAAAwAAAAERAAADAAAAAREAAAMAAAABEQAABQAAAAERAAAIAAAAAREAAAMAAAACEQAAAwAA" +
        "AAEFAAAJAAAAAWsDAAUAAAABBQAAAgAAAAErBQAJAAAAAWsDAAUAAAABYgAAAgAAAAEFAAAJAAAAAWsDAAUAAAABBQAAAwAAAAER" +
        "AAAHAAAAAUQEAAERAAACawAAAWsCAAIRAAABiwAAAgAAAAEFAAAJAAAAAUQDAAUAAAABBQAAAgAAAAErBQAPAAAAAWIAAAIAAAAB" +
        "BQAADwAAAAEFAAADAAAAAREAAA0AAAABEQAAAYsAAAQAAAABEQAAAQUAAAFiAAABEQAACgAAAAEFAAAHAAAAAWIAAAoAAAABYgAA" +
        "BwAAAAEFAAAKAAAAAQUAAAcAAAABEQAACQAAAAERAAAJAAAAAREAAAMAAAABEQAAAwAAAAERAAALAAAAAQUAAAFiAAABBQAAAYsA" +
        "AAEFAAABYgAAAQUAABsAAAABTQQAAQAAAAFNBAABAAAAAU0EAAEAAAABTQQAAQAAAAFNBAABAAAAAU0EAAcAAAABYAQAAQUAAAFV" +
        "AAABBQAAAWAEAAEFAAABVQAAAQUAAAFgBAABBQAAAVUAAAEFAAABYAQABQAAAAFiAAABEQAAAwAAAAERAAADAAAAAREAAAMAAAAB" +
        "EQAAAWIAAAMAAAABYAYAAREAAAgAAAABEQAAAwAAAAIRAAABYAcAAQAAAAFNAgABBQAACQAAAAFrAwAFAAAAAQUAAAFNAQABAAAA" +
        "AVUAAAkAAAABawMABQAAAAFVAAABAAAAAU0CAAEFAAAJAAAAAWsDAAUAAAABBQAAAU0BAAEAAAABYAYAAREAAAgAAAABEQAAA2sA" +
        "AAIRAAABYAcAAQAAAAFNAgABBQAADwAAAAEFAAABTQEAAQAAAAFVAAAPAAAAAVUAAAEAAAABTQIAAQUAAA8AAAABBQAAAU0BAAEA" +
        "AAABYAYAAREAAA0AAAABEQAAAWAHAAMAAAABYgAAAREAAAEFAAABVQAAAREAAAoAAAABBQAAAU0BAAMAAAABYAUAAU0DAAEAAAAB" +
        "VQAACgAAAAFVAAAGAAAAAU0CAAEFAAAKAAAAAQUAAAFNAQAFAAAAAWAGAAERAAAJAAAAAREAAAFgBwAHAAAAAWIAAAERAAADAAAA" +
        "AREAAAMAAAABEQAAAWIAAAkAAAABYAUAAQUAAAFVAAABBQAAAWAFAAEFAAABVQAAAQUAAAFgBQALAAAAAU0DAAEAAAABTQMAAQAA" +
        "AAFNAwABAAAAAU0DABoAAAABbQAAAQUAAAFVAAABBQAAAVUAAAEFAAABVQAAAQUAAAFVAAABBQAAAVUAAAEFAAABbQIABQAAAAFi" +
        "AAABEQAAAwAAAAERAAADAAAAAREAAAMAAAABEQAAAWIAAAMAAAABbQIAAREAAAgAAAABEQAAAwAAAAIRAAABbQEAAgAAAAEFAAAJ" +
        "AAAAAWIAAAUAAAABBQAAAgAAAAFVAAAJAAAAAWIAAAUAAAABVQAAAgAAAAEFAAAJAAAAAWIAAAUAAAABBQAAAgAAAAFVAAABEQAA" +
        "CAAAAAERAAADYgAAAhEAAAFVAAACAAAAAQUAAA8AAAABBQAAAgAAAAFVAAAPAAAAAVUAAAIAAAABBQAADwAAAAEFAAACAAAAAVUA" +
        "AAERAAANAAAAAREAAAFVAAADAAAAAWIAAAERAAABBQAAAVUAAAERAAAKAAAAAQUAAAMAAAABQwcAA2IAAAFVAAAKAAAAAVUAAAUA" +
        "AAABLA0AAWIAAAEFAAAKAAAAAQUAAAYAAAABYgAAAREAAAkAAAABEQAAAW0BAAYAAAABQwQAAWIAAAERAAADAAAAAREAAAMAAAAB" +
        "EQAAAWIAAAkAAAABVQAAAQUAAAFVAAABBQAAAVUAAAEFAAABVQAAAQUAAAFtAwAtAAAAAREAAAliAAABEQAABwAAAAEFAQADAAAA" +
        "AREAAAMAAAABEQAAA2IAAAEFAQAFAAAAAQUBAAERCAADEQQAAREIAAMRBAABEQgAAxEEAAERCAABBQEAARIMAAIAAAABEQAAAhEI" +
        "AANiAAABEQgAA2IAAAERCAADYgAAAREIAAFiAAABEQAAAgAAAAFiAAACEQgAA2IAAAERCAADYgAAAREIAAFiAAABYAEAAWIAAAER" +
        "CAACYgAAAgAAAAFiAAACEQgAA2IAAAERCAADYgAAAREIAANiAAABEQgAAmIAAAIAAAABYgAAAREAAAERCAALEQQAAREIAAERAAAB" +
        "YgAAAgAAAAFiAAACEQgAA2IAAAERCAADYgAAAREIAANiAAABEQgAAmIAAAIAAAABYgAAAhEIAANiAAABEQgAA2IAAAERCAADYgAA" +
        "AREIAAJiAAACAAAAAREAAAIRCAADYgAAAREIAANiAAABEQgAA2IAAAERCAACYgAAAgAAAAESDAABBQEAAREIAAMRBAABEQgABxEE" +
        "AAERCAABEQAAAWIAAAMAAAACBQEAA2IAAAERCAADYgAAAREIAANiAAABEQgAAmIAAAMAAAABEQAAARQAAANiAAABEQgAA2IAAAER" +
        "CAADYgAAAREIAAJiAAAFAAAAAREAAAJiAAABEQgAA2IAAAERCAADYgAAAREIAAFiAAABEQAABgAAAAEUAAABYgAAAREIAAMRBAAB" +
        "EQgAAxEEAAERCAABBQEABwAAAAERAAACBQEAAmIAAAEAAAABEQAAA2IAAAEFAQABEgwACQAAAAESBAABEQAABWIAAAERAAAuAAAA" +
        "AREAAAEFAQABbQEAAQAAAAFtAAABEQAAAW0BAAEAAAABbQAAAQUBAAERAAAHAAAADQUBAAUAAAABBQEAAX4JAAcAAAABEQAAAwAA" +
        "AAG8AAABBQEAARIMAAIAAAABEQAAAQUBAAgAAAABawMAAQAAAAGUAAACAAAAAQUBAAERAAACAAAAAUMEAAEFAQAIAAAAAWsDAAIA" +
        "AAABlAAAAQAAAAIFAQACAAAAAW0AAAEFAQAIAAAAAWsDAAQAAAABBQEAAwAAAAERAAABBQEACAAAAAERAAACawAAAWsCAAERAAAB" +
        "BQEAAW0CAAIAAAABbQAAAQUBAA0AAAABBQEAAWIAAAIAAAABQwQAAQUBAA0AAAABBQEAAREAAAIAAAABEQAAAQUBAA0AAAABBQEA" +
        "AWIAAAIAAAABEgwAAQUBAA0AAAABBQEAAW0DAAMAAAACBQEADAAAAAEFAQAEAAAAAREAAAEUAAAMAAAAAgUBAAUAAAABEQAAAwAA" +
        "AAERAAABNgUAAZIEAAE2BAABkgQAATYEAAERAAACBQEAAREAAAYAAAABFAAAAZEBAAEFAQABAAAAATYFAAGSBAABNgQAAZIEAAE2" +
        "BAABAAAAAgUBAAcAAAABEQAAAgUBAAGGBgAFBQEAAYYGAAEFAQABEgwACQAAAAESDAABEQAAAQAAAAFtAwABEQAAAW0DAAEAAAAB" +
        "EQAAHAAAAAESDAADAAAAAWAEAA0AAAABQwAAAREAAAMAAAABEQAAAwAAAAERAAABQwEABwAAAAGGAAADBQEAARQAAAMFAQABFAAA" +
        "AwUBAAGGAQAFAAAAAYYCAAEFAQAHAAAAAREAAAIAAAABfgkAAQUBAAESDAADAAAAAUMCAAEFAQAIAAAAAWsDAAQAAAABBQEAAUMC" +
        "AAIAAAABEQAAAQUBAAgAAAABawMABAAAAAEFAQABEQAAAwAAAAEUAAAIAAAAAWsDAAQAAAABBQEAAW0HAAEAAAABYAYAAREAAAEF" +
        "AQAIAAAAAREAAAJrAAABawIAAREAAAEUAAAEAAAAARQAAA0AAAABBQEAAWIAAAIAAAABEQAAAQUBAA0AAAABBQEAAREAAAIAAAAB" +
        "QwMAAQUBAA0AAAABBQEAAWIAAAIAAAABEgwAAgUBAAwAAAABFAAABAAAAAGGAgABBQEADAAAAAEFAQABbQYAAwAAAAERAAABFAAA" +
        "DAAAAAEFAQABEQAABQAAAAERAAADAAAAAREAAAE2BQABkgQAATYEAAGSBAABNgQAAREAAAIFAQABQwMABgAAAAEUAAABhgUAAQUB" +
        "AAEAAAABNgUAAZIEAAE2BAABkgQAATYEAAEAAAABBQEAAYYDAAcAAAABEQAAAYYBAAESDAABBQEAAYYGAAMFAQABhgYAAQUBAAGG" +
        "AQABEgwACgAAAAFDAAABEQAAAQAAAAERAAABAAAAAREAAAFDAQAPAAAAAWAFAAwAAAABEgwAEgAAAAERAAABBQEAAQAAAAFtBAAB" +
        "EQAAAW0FAAEAAAABBQEAAREAAAkAAAALBQEABwAAAAGGAgABBQEAAX4JAAUAAAABEQAAAQAAAAGGBAACBQEAARIMAAQAAAABhgIA" +
        "AQUBAAcAAAABawMAAgAAAAGGBAACBQEAAwAAAAERAAABBQEACAAAAAFrAwADAAAAAX4JAAEFAQABEQAAAwAAAAEUAAAIAAAAAWsD" +
        "AAQAAAACBQEAAgAAAAERAAABBQEACAAAAAERAAADawIAAREAAAEFAQAEAAAAARQAAA0AAAABBQEAAW0CAAIAAAABEQAAAQUBAA0A" +
        "AAABBQEAAREAAAFgBwACAAAAAwUBAAsAAAABBQEAAW0DAAIAAAABEgwAAgUBAAwAAAABBQEABQAAAAEFAQAMAAAAAgUBAAMAAAAB" +
        "QwAAAREAAAsAAAACBQEAAREAAAUAAAABEQAAAgAAAAEFAQABEQAAATYFAAGSBAABNgQAAZIEAAE2BAABEQAAAgUBAAcAAAABEQAA" +
        "AwUBAAE2BQABkgQAATYEAAGSBAABNgQAAgUBAAgAAAABQwMAAQAAAAESDAAHBQEAARIMAAwAAAABEQAAAW0HAAERAAABbQcAAREA" +
        "AB4AAAABEgwAEQAAAAFDAAABEQAAAREEAAEFAQABbQIAAQUBAAERBAABEQAAAUMBAAkAAAABhgAACQUBAAGGAQAIAAAAAgUBAAUA" +
        "AAABEQAAAWIAAAIFAQABEgwABgAAAAESBAABBQEABgAAAAERCAACYgAAAgUBAAGGAgADAAAAAREAAAIFAQAHAAAAAREIAANiAAAC" +
        "BQEAAUMCAAIAAAABbQQAAQUBAAgAAAABEQgABGIAAAEFAQABEQAAAgAAAAFtAAABBQEACAAAAAERAAADEQQAAREAAAEFAQABEQgA" +
        "AgAAAAFtBAABBQEADQAAAAIFAQACAAAAAREAAAEFAQANAAAAAQUBAAERAAADAAAAAwUBAAsAAAACBQEAAwAAAAESDAACBQEACwAA" +
        "AAEFAQABEQgABAAAAAEFAQAMAAAAAQUBAAERAAAEAAAAAREAAAsAAAACBQEAAUMDAAUAAAABFAAAAQAAAAF+CQABBQEAAREAAAE2" +
        "BQABkgUAATYEAAGSBAABNgQAAREAAAEFAQABhgMABwAAAAERAAABBQEAARIEAAEFAQABNgUAAZIFAAE2BAABkgQAATYEAAIFAQAL" +
        "AAAAARIMAAYFAQABEgwADAAAAAFDAAABEQAAAW0DAAERAAABQwEAMQAAAAESDAABQwAAAREAAAEAAAABEQAAAUMBAAwAAAABhgAA" +
        "AwUBAAEUAAADBQEAAYYBAAkAAAABfgEAAgUBAAF+CQADAAAAAWIAAAIFAQABfgEABwAAAAESBAACBQEABQAAAAFiAAADBQEAAX4B" +
        "AAQAAAABQwIAAYYCAAIFAQAGAAAAAWIAAAQFAQAEAAAAAREAAAEFAQAIAAAAAWIAAAIAAAACBQEAAYYCAAQAAAABFAAACAAAAAER" +
        "AAAEYgAAAQUBAAFDAgACAAAAAREAAAEFAQANAAAAAQUBAAERAAACAAAAAUMDAAGGAwABBQEADAAAAAEUAAAFAAAAAgUBAAsAAAAB" +
        "BQEAAREAAAQAAAABEgwAAQUBAAsAAAABBQEAAUMDAAQAAAABhgIAAQUBAAoAAAABBQEAAYYDAAUAAAABEQAAAgAAAAGGBgAIAAAA" +
        "AQUBAAcAAAABFAAAAQAAAAMFAQABhgUAAwAAAAGGBAACBQEACAAAAAERAAABhgEAAQAAAAEFAQABhgYAAYYFAAEAAAABhgYAAYYE" +
        "AAEFAQABEgwADAAAAAUFAQABfgEADgAAAAERAAABAAAAAREAADQAAAABEQAAAQUBAAERAAAOAAAAARIEAAGGAAADBQEAAYYBAAwA" +
        "AAABEgwAAgUBAAF+CQACAAAAAQUBAAF+AQAKAAAAARIEAAMFAQADAAAAAwUBAAESBAAHAAAAAX4BAAIFAQAFAAAAAWIAAAMFAQAF" +
        "AAAAAREAAAIFAQAHAAAAAWIAAAEAAAACBQEAARIEAAQAAAABbQQAAQUBAAgAAAABEQAAAmIAAAIFAQABhgIAAwAAAAERAAACBQEA" +
        "DAAAAAEFAQABEQAABAAAAAIFAQALAAAAAQUBAAFtBQAEAAAAAX4BAAEFAQALAAAAAQUBAAERAAAEAAAAARIMAAEFAQAKAAAAAQUB" +
        "AAGGAwAGAAAAAQUBAAoAAAABBQEABgAAAAEsAwAEBQEABgAAAAEFAQABfgEABwAAAAERAAAFBQEAAwAAAAIFAQAJAAAAASwDAAEA" +
        "AAABEgQAAQAAAAIFAQABAAAAAgUBAA8AAAAEBQEADwAAAAERAAABbQcAAREAADQAAAABQwAAAREEAAFDAQAQAAAAAwUBAA4AAAAB" +
        "EgwAAX4BAAMFAQANAAAAAX4BAAMFAQABfgkAAgUBAAISDAAJAAAAARIEAAEFAQABfgkABAAAAAMFAQAGAAAAAUMCAAGGAgACBQEA" +
        "BgAAAAFiAAABAAAAAQUBAAF+AQAFAAAAAREIAAIFAQABfgkABgAAAAERAAABYgAAAgUBAAF+AQAEAAAAAUMDAAGGAwACBQEACQAA" +
        "AAMFAQABQwIABQAAAAIFAQAIAAAAAwUBAAERCAAFAAAAAX4BAAEFAQAIAAAAAwUBAAFDAwAFAAAAARIMAAEFAQAJAAAAAQUBAAcA" +
        "AAABfgEAAQUBAAgAAAABBQEACAAAAAUFAQAFAAAAAQUBAAgAAAABEQAAAQUBAAEAAAABEgwAAX4BAAEFAQACAAAAAgUBAAESDAAN" +
        "AAAAAX4BAAEFAQABhgYAAgUBAA8AAAADBQEAAX4BAA8AAAABQwAAAREEAAFDAQA1AAAAAUMCABIAAAABBQEAEgAAAAEFAQAQAAAA" +
        "ARIMAAF+AQACBQEAAX4BAA0AAAAHBQEACgAAAAF+AQACBQEABAAAAAFiAAACBQEABgAAAAFDAAAEBQEAAX4JAAQAAAABEQAAAWIA" +
        "AAEFAQABfgEABwAAAAISBAACBQEABgAAAAIFAQAJAAAAAX4BAAEFAQAHAAAAAwUBAAFDAQAGAAAAARIMAAEFAQAHAAAAAQUBAAF+" +
        "AQAJAAAAAQUBAAF+CQAGAAAAAQUBAAkAAAABhgAAAwUBAAQAAAABBQEACgAAAAEFAQABEgwAAX4BAAEFAQABhgYAAgAAAAF+CQAB" +
        "BQEACQAAAAEsAwAEAAAABAUBAAESDAAPAAAAAwUBABAAAAABhgAAAQUBAAGGAQARAAAAAUMDAIAAAAABEgwAAX4BAAIFAQABEgwA" +
        "DQAAAAF+AQAFBQEAAX4BAAwAAAADBQEAAhQAAAIFAQALAAAAARIEAAGGAwABBQEAAxQAAAIFAQABfgEACwAAAAESDAABBQEABBQA" +
        "AAIFAQAMAAAAAQUBAAQUAAACBQEAARIEAAsAAAADBQEAAhQAAAIFAQALAAAABAUBAAEUAAACBQEAAX4BAA0AAAABEgwABAUBAAES" +
        "DAAPAAAAAgUBABIAAAABBQEAEgAAAAFDAwAtAAA=");

    // BASE_HCF: 29x20x26, 3976 non-air cells; exact selected surface component.
    private static final Template BASE_HCF=new Template(29,20,26,0,
        "AvKbAAAmAAAAAywFAAIBBgADLAUAEwAAAAIsBQADAQYAAQAAAAFBAwADAQYAAiwFABAAAAABLAUAAgEGAAMFAQACAAAAAwUBAAIB" +
        "BgABLAUADgAAAAFVAAABAQYAAQEAAAMAAAABBQEAAmsAAAEFAQADAAAAAQUBAAEBBgABVQAADAAAAAEsBQABAQYAAQEAAAEFAQAK" +
        "AAAAAgUBAAEBBgABLAUACgAAAAEsBQABAQYAAgUBAAwAAAACBQEAAQEGAAEsBQAIAAAAASwFAAEBBgABBQEAEAAAAAEFAQABAQYA" +
        "ASwFAAcAAAABLAUAAQEGAAEFAQAQAAAAAQUBAAEBBgABLAUABwAAAAEBBgABAQAAAQUBABAAAAACBQEAAQEGAAYAAAABbQIAAQEG" +
        "AAIFAQAQAAAAAgUBAAEBBgABbQIABQAAAAEsDQABAQYAAQUBAAgAAAABIwsAAWsAAAEjCwAHAAAAAQUBAAEBBgABLA0ABgAAAAFr" +
        "AQAJAAAAAWsDAAEAAAABawEACAAAAAFrAQAHAAAAAWsDAAkAAAABIwsAAWsCAAEjCwAIAAAAAWsBAAYAAAABLA0AAQEGAAEFAQAS" +
        "AAAAAQUBAAEBBgABLA0ABQAAAAFtAwABAQYAAgUBABAAAAACBQEAAQEGAAFtAwAGAAAAAQEGAAEBAAABBQEAEAAAAAIFAQABAQYA" +
        "BwAAAAEsBQABAQYAAQUBABAAAAABBQEAAQEGAAEsBQAHAAAAASwFAAEBBgABBQEAEAAAAAEFAQABAQYAASwFAAgAAAABLAUAAQEG" +
        "AAIFAQAMAAAAAgUBAAEBBgABLAUACgAAAAEsBQABAQYAAQEAAAEFAQAKAAAAAQUBAAEBAAABAQYAASwFAAwAAAABVQAAAQEGAAEF" +
        "AQADAAAAAQUBAAFrAgABawAAAQUBAAMAAAABBQEAAQEGAAFVAAAOAAAAASwFAAIBBgADBQEAAgAAAAMFAQACAQYAASwFABAAAAAC" +
        "LAUAAwEGAAFBAgABAAAAAQEGAAEBAAABAQYAAiwFABMAAAADLAUAAgEGAAMsBQBSAAAAAgEGABgAAAADBQEAAQAAAAFBAwADBQEA" +
        "EgAAAAF+CQABAQYABAUBAAIAAAAEBQEAAQEGAAF+CQAOAAAAAVUAAAGGAgABBQEAAwAAAAEFAQACawAAAQUBAAMAAAABBQEAAYYC" +
        "AAFVAAAMAAAAAX4JAAGGAAACBQEACgAAAAIFAQABhgEAAX4JAAsAAAABAQYAAgUBAAwAAAACBQEAAQEGAAoAAAACBQEAEAAAAAIF" +
        "AQAJAAAAAgUBABAAAAACBQEACAAAAAEBBgACBQEAEAAAAAIFAQABAQYACAAAAAIFAQAQAAAAAgUBAAcAAAABKwUAAQEGAAEFAQAI" +
        "AAAAASMLAAFrAAABIwsABwAAAAEFAQABAQYAASsFAAYAAAABawEACQAAAAFrAwABAAAAAWsBAAgAAAABawEABwAAAAFrAwAJAAAA" +
        "ASMLAAFrAgABIwsACAAAAAFrAQAGAAAAASsFAAEBBgABBQEAEgAAAAEFAQABAQYAASsFAAcAAAACBQEAEAAAAAIFAQAIAAAAAQEG" +
        "AAIFAQAQAAAAAgUBAAEBBgAIAAAAAgUBABAAAAACBQEACQAAAAIFAQAQAAAAAgUBAAoAAAABAQYAAgUBAAwAAAACBQEAAQEGAAsA" +
        "AAABfgkAAYYAAAIFAQAKAAAAAgUBAAGGAQABfgkADAAAAAFVAAABhgMAAQUBAAMAAAABBQEAAWsCAAFrAAABBQEAAwAAAAEFAQAB" +
        "hgMAAVUAAA4AAAABfgkAAQEGAAQFAQACAAAABAUBAAEBBgABfgkAEgAAAAMFAQABQQIAAQAAAAMFAQAYAAAAAwEGAFEAAAAIAQYA" +
        "EwAAAAIBBgADBQEAAgAAAAMFAQACAQYAEQAAAAEBBgAEBQEAAgEGAAQFAQABAQYADwAAAAFVAAABAAAAAQUBAAMAAAABBQEAAgEG" +
        "AAEFAQADAAAAAQUBAAEAAAABVQAADgAAAAF+AQABIw8ACgAAAAEjDwABfgEADAAAAAIBBgABBQEAASMPAAwAAAABIw8AAQUBAAIB" +
        "BgAIAAAAAQEGAAIFAQAQAAAAAgUBAAEBBgAHAAAAAQEGAAIFAQAQAAAAAgUBAAEBBgAHAAAAAQEGAAIFAQAQAAAAAgUBAAEBBgAG" +
        "AAAAAW0GAAEAAAABfgEAASMPABAAAAABIw8AAX4BAAEAAAABbQYABQAAAAEsDQABAQYAAQUBAAgAAAABXwsAASMLAAFfCwAHAAAA" +
        "AQUBAAEBBgABLA0ABgAAAAIFAQAIAAAAASMLAAFEAgABIwsABwAAAAIFAQAHAAAAAgUBAAgAAAABXwsAASMLAAFfCwAHAAAAAgUB" +
        "AAYAAAABLA0AAQEGAAEFAQASAAAAAQUBAAEBBgABLA0ABQAAAAFtBwABAAAAAX4BAAEjDwAQAAAAASMPAAF+AQABAAAAAW0HAAYA" +
        "AAABAQYAAgUBABAAAAACBQEAAQEGAAcAAAABAQYAAgUBABAAAAACBQEAAQEGAAcAAAABAQYAAgUBABAAAAACBQEAAQEGAAgAAAAC" +
        "AQYAAQUBAAEjDwAMAAAAASMPAAEFAQACAQYADAAAAAF+AQABIw8ACgAAAAEjDwABfgEADgAAAAFVAAABAAAAAQUBAAMAAAABBQEA" +
        "AgEGAAEFAQADAAAAAQUBAAEAAAABVQAADwAAAAEBBgAEBQEAAgEGAAQFAQABAQYAEQAAAAIBBgADBQEAAgAAAAMFAQACAQYAEwAA" +
        "AAgBBgBQAAAAAVUAAAEsBQACAQYAASwFAAFVAAAWAAAAAwUBAAIAAAADBQEAEwAAAAEBBgAEBQEAAgAAAAQFAQABAQYADwAAAAFV" +
        "AAABAAAAASMPAAMAAAABBQEAAl8AAAEFAQADAAAAASMPAAEAAAABVQAADgAAAAEjDwABBQEACgAAAAEFAQABIw8ADQAAAAEBBgAB" +
        "Iw8AAQUBAAwAAAABBQEAASMPAAEBBgAJAAAAASwNAAFVAAABIw8AEAAAAAEjDwABVQAAASwNAAgAAAACBQEAEAAAAAIFAQAIAAAA" +
        "AQEGAAIFAQAQAAAAAgUBAAEBBgAIAAAAAQUBAAEjDwAQAAAAASMPAAEFAQAHAAAAAW0HAAEBBgABBQEACAAAAANfCwAHAAAAAQUB" +
        "AAEBBgABbQcABQAAAAFgDgABWQAAAQUBAAgAAAABXwsAAQAAAAFfCwAHAAAAAQUBAAFZAAABYA8ABQAAAAFgDgABWQAAAQUBAAgA" +
        "AAADXwsABwAAAAEFAQABWQAAAWAPAAUAAAABbQYAAQEGAAEFAQASAAAAAQUBAAEBBgABbQYABwAAAAEFAQABIw8AEAAAAAEjDwAB" +
        "BQEACAAAAAEBBgACBQEAEAAAAAIFAQABAQYACAAAAAIFAQAQAAAAAgUBAAgAAAABLA0AAVUAAAEjDwAQAAAAASMPAAFVAAABLA0A" +
        "CQAAAAEBBgABIw8AAQUBAAwAAAABBQEAASMPAAEBBgANAAAAASMPAAEFAQAKAAAAAQUBAAEjDwAOAAAAAVUAAAEAAAABIw8AAwAA" +
        "AAEFAQACXwAAAQUBAAMAAAABIw8AAQAAAAFVAAAPAAAAAQEGAAQFAQACAAAABAUBAAEBBgATAAAAAwUBAAIAAAADBQEAFgAAAAFV" +
        "AAABLAUAAgEGAAEsBQABVQAAUQAAAAF8AAABAAAAAgEGAAEAAAABfAAAFQAAAAF+AQABhgQAAZgAAAEFAQACAAAAAQUBAAGYAAAB" +
        "hgUAAX4BABEAAAABfgkAAQEGAAEFAQACIw8AAQUBAAIAAAABBQEAAiMPAAEFAQABAQYAAX4JAA4AAAABfgEAAX4JAAEjDwADAAAA" +
        "AQUBAAJfAAABBQEAAwAAAAEjDwABfgkAAX4BAAwAAAACfgkAASMPAAEFAQAKAAAAAQUBAAEjDwACfgkACgAAAAEsDQABAQYAASMP" +
        "AAEFAQAMAAAAAQUBAAEjDwABAQYAASwNAAkAAAABVQAAASMPABAAAAABIw8AAVUAAAgAAAABLAUAAgUBABAAAAACBQEAASwFAAcA" +
        "AAABAQYAAgUBABAAAAACBQEAAQEGAAcAAAABLA0AAX4JAAEjDwAQAAAAASMPAAF+CQABLA0ACAAAAAEFAQAIAAAAA18LAAcAAAAB" +
        "BQEABwAAAAEsBQABAQYAAQUBAAgAAAABXwsAAQAAAAFfCwAHAAAAAQUBAAEBBgABLAUABQAAAAEsBQABAQYAAQUBAAgAAAADXwsA" +
        "BwAAAAEFAQABAQYAASwFAAcAAAABBQEAEgAAAAEFAQAIAAAAASwNAAF+CQABIw8AEAAAAAEjDwABfgkAASwNAAcAAAABAQYAAgUB" +
        "ABAAAAACBQEAAQEGAAcAAAABLAUAAgUBABAAAAACBQEAASwFAAgAAAABVQAAASMPABAAAAABIw8AAVUAAAkAAAABLA0AAQEGAAEj" +
        "DwABBQEADAAAAAEFAQABIw8AAQEGAAEsDQAKAAAAAn4JAAEjDwABBQEACgAAAAEFAQABIw8AAn4JAAwAAAABfgEAAX4JAAEjDwAD" +
        "AAAAAQUBAAJfAAABBQEAAwAAAAEjDwABfgkAAX4BAA4AAAABfgkAAQEGAAEFAQACIw8AAQUBAAIAAAABBQEAAiMPAAEFAQABAQYA" +
        "AX4JABEAAAABfgEAAYYEAAGYAAABBQEAAgAAAAEFAQABmAAAAYYFAAF+AQAVAAAAAXwAAAEAAAACAQYAAQAAAAF8AABTAAAAAgEG" +
        "ABgAAAACfgEAAYYEAAIAAAABhgUAAn4BABMAAAABAQYAAQUBAAIjDwABBQEAAgAAAAEFAQACIw8AAQUBAAEBBgAQAAAAAQUBAAEj" +
        "DwADfgkAAQUBAAJfAAABBQEAA34JAAEjDwABBQEADQAAAAF+CQABBQEAASMPAAEFAQAKfgkAAwUBAAF+CQAKAAAAAX4JAAEBBgAB" +
        "Iw8AAQUBAAN+CQAGAAAAA34JAAEFAQABIw8AAQEGAAF+CQAJAAAAAVUAAAEjDwADfgkACgAAAAN+CQABIw8AAVUAAAkAAAABhgYA" +
        "ASMPAAJ+CQAMAAAAAn4JAAEjDwABhgYACAAAAAEBBgABhgYAASMPAAJ+CQAMAAAAAn4JAAEjDwABAAAAAQEGAAYAAAABYA4AAVkA" +
        "AAIFAQACfgkADAAAAAJ+CQACBQEAAVkAAAFgDwAGAAAAAW0CAAIFAQACfgkABQAAAANfCwAEAAAAAn4JAAIFAQABbQIABwAAAAJt" +
        "BAABBQEAAn4JAAUAAAABXwsAAQAAAAFfCwAEAAAAAn4JAAEFAQACbQUABwAAAAJtBAABBQEAAn4JAAUAAAADXwsABAAAAAJ+CQAB" +
        "BQEAAm0FAAcAAAABbQMAAgUBAAJ+CQAMAAAAAn4JAAIFAQABbQMABgAAAAFgDgABWQAAAgUBAAJ+CQAMAAAAAn4JAAIFAQABWQAA" +
        "AWAPAAYAAAABAQYAAYYHAAEjDwACfgkADAAAAAJ+CQABIw8AAYYHAAEBBgAIAAAAAYYHAAEjDwACfgkADAAAAAJ+CQABIw8AAYYH" +
        "AAkAAAABVQAAASMPAAN+CQAKAAAAA34JAAEjDwABVQAACQAAAAF+CQABAQYAASMPAAEFAQADfgkABgAAAAN+CQABBQEAASMPAAEB" +
        "BgABfgkACgAAAAF+CQABBQEAASMPAAEFAQAKfgkAAwUBAAF+CQANAAAAAQUBAAEjDwADfgkAAQUBAAJfAAABBQEAA34JAAEjDwAB" +
        "BQEAEAAAAAEBBgABBQEAAiMPAAEFAQACAAAAAQUBAAIjDwABBQEAAQEGABMAAAACfgEAAYYEAAIAAAABhgUAAn4BABgAAAACAQYA" +
        "UwAAAAIsBQACAAAAAiwFABUAAAABLAUACAEGAAEsBQASAAAAAgEGAAMFAAACAQYAAwUAAAIBBgAQAAAAAQEGAAIFAAADfgAAAgEG" +
        "AAN+AAACBQAAAQEGAA4AAAABVQAAAQEGAAEFAAACfgAABgUAAAJ+AAABBQAAAQEGAAFVAAAMAAAAAVUAAAEBBgABBQAAAX4AAAIF" +
        "AAAGIwsAAgUAAAF+AAABBQAAAQEGAAFVAAAKAAAAAX4BAAEBBgABBQAAAX4AAAEFAAADIwsAAV8LAAIjCwABXwsAAyMLAAEFAAAB" +
        "fgAAAQUAAAEBBgABfgEACgAAAAEBBgACBQAAAyMLAAJfCwACIwsAAl8LAAMjCwACBQAAAQEGAAoAAAABAQYAAwUAAAEjCwAEXwsA" +
        "AiMLAARfCwABIwsAAwUAAAEBBgAIAAAAASwFAAEBBgADBQAAASMLAARfCwACIwsABF8LAAEjCwADBQAAAQEGAAEsBQAHAAAAASwN" +
        "AAEBBgADBQAAASMLAANfCwAEIwsAA18LAAEjCwADBQAAAQEGAAEsDQAHAAAAASwNAAEBBgADBQAABiMLAAFgCQAFIwsAAQUAAAF+" +
        "AAABBQAAAQEGAAEsDQAHAAAAASwNAAEBBgADBQAADCMLAAEFAAABfgAAAQUAAAEBBgABLA0ABwAAAAEsDQABAQYAAwUAAAEjCwAD" +
        "XwsABCMLAANfCwABIwsAAQUAAAF+AAABBQAAAQEGAAEsDQAHAAAAASwFAAEBBgADBQAAASMLAARfCwACIwsABF8LAAEjCwABBQAA" +
        "AX4AAAEFAAABAQYAASwFAAgAAAABAQYAAwUAAAEjCwAEXwsAAiMLAARfCwABIwsAAwUAAAEBBgAKAAAAAQEGAAIFAAADIwsAAl8L" +
        "AAIjCwACXwsAAyMLAAIFAAABAQYACgAAAAF+AQABAQYAAQUAAAF+AAABBQAAAyMLAAFfCwACIwsAAV8LAAMjCwABBQAAAX4AAAEF" +
        "AAABAQYAAX4BAAoAAAABVQAAAQEGAAEFAAABfgAAAgUAAAYjCwACBQAAAX4AAAEFAAABAQYAAVUAAAwAAAABVQAAAQEGAAEFAAAC" +
        "fgAABgUAAAJ+AAABBQAAAQEGAAFVAAAOAAAAAQEGAAIFAAAIfgAAAgUAAAEBBgAQAAAAAgEGAAgFAAACAQYAEgAAAAEsBQAIAQYA" +
        "ASwFABUAAAACLAUAAgAAAAIsBQBtAAAAARgCAAGLAAABGAIAAosAAAEYAgABiwAAARgCABMAAAACiwAACAAAAAKLAAAQAAAAAosA" +
        "AAoAAAACiwAADgAAAAGAAgABiwAAAwAAAAYBBgADAAAAAYsAAAGAAgAMAAAAAYAAAAEYAgABiwAAAQAAAAMBBgABBQEAAgAAAAEF" +
        "AQADAQYAAQAAAAGLAAABGAIAAYABAAsAAAACiwAAAQAAAAMBBgABBQEABAAAAAEFAQADAQYAAQAAAAKLAAALAAAAAYsAAAEAAAAC" +
        "AQYAAgUBAAYAAAACBQEAAgEGAAEAAAABiwAACgAAAAEYAQABGAIAAVUAAAEBBgABBQEACgAAAAEFAQABAQYAAVUAAAEYAgABGAEA" +
        "CQAAAAGLAAACAAAAAQEGAAEFAQAKAAAAAQUBAAEBBgACAAAAAYsAAAkAAAABGAEAAQAAAAFVAAABAQYAAQUBAAMAAAABIwsAAWsA" +
        "AAFrAgABIwsAAwAAAAEFAQABAQYAAVUAAAEAAAABGAEACQAAAAGLAAACAAAAAQEGAAEFAQADAAAAAWsBAAIAAAABawMABAAAAAEB" +
        "BgACAAAAAYsAAAkAAAABiwAAAgAAAAEBBgABBQEAAwAAAAFrAQACAAAAAWsDAAQAAAABAQYAAgAAAAGLAAAJAAAAARgBAAEAAAAB" +
        "VQAAAQEGAAEFAQADAAAAASMLAAFrAgABawAAASMLAAMAAAABBQEAAQEGAAFVAAABAAAAARgBAAkAAAABiwAAAgAAAAEBBgABBQEA" +
        "CgAAAAEFAQABAQYAAgAAAAGLAAAJAAAAAhgCAAFVAAABAQYAAQUBAAoAAAABBQEAAQEGAAFVAAACGAIACgAAAAGLAAABAAAAAgEG" +
        "AAIFAQAGAAAAAgUBAAIBBgABAAAAAYsAAAsAAAACiwAAAQAAAAMBBgABBQEABAAAAAEFAQADAQYAAQAAAAKLAAALAAAAAYAAAAEY" +
        "AgABiwAAAQAAAAMBBgABBQEAAgAAAAEFAQADAQYAAQAAAAGLAAABGAIAAYABAAwAAAABgAMAAYsAAAMAAAAGAQYAAwAAAAGLAAAB" +
        "gAMADgAAAAKLAAAKAAAAAosAABAAAAACiwAACAAAAAKLAAATAAAAARgCAAGLAAABGAIAAosAAAEYAgABiwAAARgCAIkAAAABGAIA" +
        "AQAAAAEYAgACAAAAARgCAAEAAAABGAIAUAAAAAEBBgABbQIAAgEGAAFtAgABAQYAEgAAAAEYAgACAAAAAVUAAAFtAAABAQYAAQUB" +
        "AAIAAAABBQEAAQEGAAFtAQABVQAAAgAAAAEYAgAPAAAAAW0CAAIBBgABBQEABAAAAAEFAQACAQYAAW0CABAAAAACAQYAAgUBAAYA" +
        "AAACBQEAAgEGAAwAAAABiwAAAQAAAAFVAAABbQIAAQUBAAoAAAABBQEAAW0CAAFVAAABAAAAAYsAAAwAAAABGAEAAQUBAAoAAAAB" +
        "BQEAARgBAAwAAAABGAEAAQAAAAFVAAABbQMAAQUBAAMAAAABIwsAAWsAAAFrAgABIwsAAwAAAAEFAQABbQMAAVUAAAEAAAABGAEA" +
        "DAAAAAEBBgABBQEAAwAAAAFrAQACAAAAAWsDAAQAAAABAQYADwAAAAEBBgABBQEAAwAAAAFrAQACAAAAAWsDAAQAAAABAQYADAAA" +
        "AAEYAQABAAAAAVUAAAFtAgABBQEAAwAAAAEjCwACawAAASMLAAMAAAABBQEAAW0CAAFVAAABAAAAARgBAAwAAAABGAEAAQUBAAoA" +
        "AAABBQEAARgBAAwAAAABiwAAAQAAAAFVAAABbQMAAQUBAAoAAAABBQEAAW0DAAFVAAABAAAAAYsAAAwAAAACAQYAAgUBAAYAAAAC" +
        "BQEAAgEGABAAAAABbQMAAgEGAAEFAQAEAAAAAQUBAAIBBgABbQMADwAAAAEYAgACAAAAAVUAAAFtAAABAQYAAQUBAAIAAAABBQEA" +
        "AQEGAAFtAQABVQAAAgAAAAEYAgASAAAAAQEGAAFtAwACAQYAAW0DAAEBBgBQAAAAARgCAAEAAAABGAIAAgAAAAEYAgABAAAAARgC" +
        "AIkAAAABiwAAAQAAAAGAAQACLAEAAYAAAAEAAAABiwAAFwAAAAEsCQACAAAAASwJADUAAAABAQYAAQAAAAIBBgABAAAAAQEGABIA" +
        "AAABGAIAAgAAAAFVAAABAAAAAQEGAAEFAQACAAAAAQUBAAEBBgABAAAAAVUAAAIAAAABGAIAEAAAAAEsCQABAAAAAQUBAAQAAAAB" +
        "BQEAAQAAAAEsCQARAAAAAgEGAAIFAQAGAAAAAgUBAAIBBgAMAAAAAYsAAAEAAAABVQAAAQAAAAEFAQAKAAAAAQUBAAEAAAABVQAA" +
        "AQAAAAGLAAAMAAAAARgBAAEFAQAKAAAAAQUBAAEYAQAMAAAAAYADAAEAAAABVQAAAQAAAAEFAQADAAAABCMLAAMAAAABBQEAAQAA" +
        "AAFVAAABAAAAAYADAAwAAAABAQYAAVUAAAEjDwACAAAAASMLAAEAAAABYAoAASMLAAQAAAABAQYADwAAAAEBBgABVQAAASMPAAIA" +
        "AAABIwsAAgAAAAEjCwAEAAAAAQEGAAwAAAABgAIAAQAAAAFVAAABAAAAAQUBAAMAAAAEIwsAAwAAAAEFAQABAAAAAVUAAAEAAAAB" +
        "gAIADAAAAAEYAQABBQEACgAAAAEFAQABGAEADAAAAAGLAAABAAAAAVUAAAEAAAABBQEACgAAAAEFAQABAAAAAVUAAAEAAAABiwAA" +
        "DAAAAAIBBgACBQEABgAAAAIFAQACAQYAEQAAAAEsCQABAAAAAQUBAAQAAAABBQEAAQAAAAEsCQAQAAAAARgCAAIAAAABVQAAAQAA" +
        "AAEBBgABBQEAAgAAAAEFAQABAQYAAQAAAAFVAAACAAAAARgCABIAAAABAQYAAQAAAAIBBgABAAAAAQEGADUAAAABLAkAAgAAAAEs" +
        "CQAXAAAAAYsAAAEAAAABgAEAAiwBAAGAAAABAAAAAYsAAIkAAAABiwAAASwBAAGAAgACgAYAAYACAAEsAQABiwAAFAAAAAIsAQAG" +
        "AAAAAiwBABIAAAABLAEABAAAAAIsCQAEAAAAASwBABAAAAABLAEAAgAAAAEsCQABGAIAAQAAAAIYAgABAAAAARgCAAEsCQACAAAA" +
        "ASwBAA4AAAABGAIAAgAAAAFVAAABLAkAAQEGAAEFAQACfgkAAQUBAAEBBgABLAkAAVUAAAIAAAABGAIADAAAAAEsAQACAAAAASsB" +
        "AAEsDQABLAEAAQUBAAQAAAABBQEAASwBAAEsDQABKwEAAgAAAAEsAQAKAAAAASwBAAIAAAACAQYAAgUBAAYAAAACBQEAAgEGAAIA" +
        "AAABLAEACQAAAAGABAABAAAAAVUAAAEAAAABBQEACgAAAAEFAQABAAAAAVUAAAEAAAABgAUACQAAAAEsCQACAAAAAW0AAAEFAQAK" +
        "AAAAAQUBAAFtAQACAAAAASwJAAkAAAABgAcAAQAAAAFVAAABAAAAAQUBAAQAAAACIwsABAAAAAEFAQABAAAAAVUAAAEAAAABgAcA" +
        "CQAAAAEsAQADAAAAAVUAAAEjDwACAAAAAiMLAAFgCgABIwsAAwAAAAF+CQABAQYAAgAAAAEsAQAJAAAAASwBAAMAAAABVQAAASMP" +
        "AAIAAAAEIwsAAwAAAAF+CQABAQYAAgAAAAEsAQAJAAAAAYAGAAEAAAABVQAAAQAAAAEFAQAEAAAAAiMLAAQAAAABBQEAAQAAAAFV" +
        "AAABAAAAAYAGAAkAAAABLAkAAgAAAAFtAAABBQEACgAAAAEFAQABbQEAAgAAAAEsCQAJAAAAAYAEAAEAAAABVQAAAQAAAAEFAQAK" +
        "AAAAAQUBAAEAAAABVQAAAQAAAAGABQAJAAAAASwBAAIAAAACAQYAAgUBAAYAAAACBQEAAgEGAAIAAAABLAEACgAAAAEsAQACAAAA" +
        "ASsBAAEsDQABLAEAAQUBAAQAAAABBQEAASwBAAEsDQABKwEAAgAAAAEsAQAMAAAAARgCAAIAAAABVQAAASwJAAEBBgABBQEAAn4J" +
        "AAEFAQABAQYAASwJAAFVAAACAAAAARgCAA4AAAABLAEAAgAAAAEsCQABGAIAAQAAAAIYAgABAAAAARgCAAEsCQACAAAAASwBABAA" +
        "AAABLAEABAAAAAIsCQAEAAAAASwBABIAAAACLAEABgAAAAIsAQAUAAAAAYsAAAEsAQABgAMAAoAHAAGAAwABLAEAAYsAAIkAAAAB" +
        "GAIABgAAAAEYAgA1AAAAAlUAABQAAAABgAYABAAAAAEYAgABbQUAAhgCAAFtBAABGAIABAAAAAGABgAMAAAAAYAEAAEYAgABgAUA" +
        "AQAAAAFVAAACAQYAAQUBAAJfCwABBQEAAgEGAAFVAAABAAAAAYAEAAEYAgABgAUADAAAAAGABwACAAAAAQEGAAIFAQAEXwsAAgUB" +
        "AAEBBgACAAAAAYAHAA4AAAABKwEAAQEGAAEFAQAIXwsAAQUBAAEBBgABKwEADgAAAAFVAAABLAUAAQUBAApfCwABBQEAASwFAAFV" +
        "AAALAAAAAYAAAAMAAAABBQEACl8LAAEFAQADAAAAAYABAAgAAAABsQQAAYAAAAEAAAABVQAAASwFAAEFAQAEXwsAAgAAAARfCwAB" +
        "BQEAASwFAAFVAAABAAAAAYABAA0AAAABVQAAASMPAAJfCwAEAAAABF8LAAErAQAQAAAAAVUAAAEjDwACXwsABAAAAARfCwABKwEA" +
        "CwAAAAGxBAABgAAAAQAAAAFVAAABLAUAAQUBAARfCwACAAAABF8LAAEFAQABLAUAAVUAAAEAAAABgAEACQAAAAGAAAADAAAAAQUB" +
        "AApfCwABBQEAAwAAAAGAAQALAAAAAVUAAAEsBQABBQEACl8LAAEFAQABLAUAAVUAAA4AAAABKwEAAQEGAAEFAQAIXwsAAQUBAAEB" +
        "BgABKwEADgAAAAGABgACAAAAAQEGAAIFAQAEXwsAAgUBAAEBBgACAAAAAYAGAAwAAAABgAQAARgCAAGABQABAAAAAVUAAAIBBgAB" +
        "BQEAAl8LAAEFAQACAQYAAVUAAAEAAAABgAQAARgCAAGABQAMAAAAAYAHAAQAAAABGAIAAW0FAAIYAgABbQQAARgCAAQAAAABgAcA" +
        "FAAAAAJVAAA1AAAAARgCAAYAAAABGAIAxgAAAAJVAAAUAAAAAYACAAQAAAABGAIAAW0AAAIYAgABbQEAARgCAAQAAAABgAIADAAA" +
        "AAGAAAABWQAAAYABAAEAAAABVQAAASwFAAEAAAABBQEAATYFAAGSBAABBQEAAQAAAAEsBQABVQAAAQAAAAGAAAABWQAAAYABAAwA" +
        "AAABgAMAAgAAAAEsBQACBQEAAZIFAAE2BQABkgQAATYEAAIFAQABLAUAAgAAAAGAAwAOAAAAASsBAAEsBQACBQEAATYFAAGSBQAC" +
        "AAAAATYEAAGSBQACBQEAASwFAAErAQAOAAAAAVUAAAFtBwADBQEAATYFAAQAAAABkgUAAwUBAAFtBwABVQAADwAAAAEFAQACNgMA" +
        "BgAAAAI2AwABBQEADwAAAAFVAAABbQYAAQUBAAKSAwAGAAAAApIDAAEFAQABbQYAAVUAAA4AAAABKwEAASMPAAI2AwAGAAAAAjYD" +
        "AAEAAAABKwEADwAAAAErAQABIw8AApIDAAYAAAACkgMAAQAAAAErAQAOAAAAAVUAAAFtBwABBQEAAjYDAAYAAAACNgMAAQUBAAFt" +
        "BwABVQAADwAAAAEFAQACkgMABgAAAAKSAwABBQEADwAAAAFVAAABbQYAAwUBAAGSBQAEAAAAATYFAAMFAQABbQYAAVUAAA4AAAAB" +
        "KwEAASwFAAIFAQABkgUAATYFAAIAAAABkgQAATYFAAIFAQABLAUAASsBAA4AAAABgAIAAgAAAAEsBQACBQEAATYFAAGSBQABNgQA" +
        "AZIEAAIFAQABLAUAAgAAAAGAAgAMAAAAAYAAAAFZAAABgAEAAQAAAAFVAAABLAUAAQAAAAEFAQABkgUAATYEAAEFAQABAAAAASwF" +
        "AAFVAAABAAAAAYAAAAFZAAABgAEADAAAAAGAAwAEAAAAARgCAAFtAAACGAIAAW0BAAEYAgAEAAAAAYADABQAAAACVQABAwAAAAJV" +
        "AAAZAAAAAQEGAAEAAAACAQYAAQAAAAEBBgAVAAAAAVUAAAEAAAABLA0AAQUBAAE2BQABkgQAAQUBAAEsDQABAAAAAVUAABQAAAAC" +
        "BQEAAZIFAAE2BQABkgQAATYEAAIFAQASAAAAASwJAAEsDQACBQEAATYFAAGSBQACAAAAATYEAAGSBQACBQEAASwNAAEsCQAOAAAA" +
        "AVUAAAEsAQADBQEAATYFAAQAAAABkgUAAwUBAAEsAQABVQAADgAAAAFtBAABBQEAAjYDAAYAAAACNgMAAQUBAAFtBQAOAAAAAVUA" +
        "AAEsAQABBQEAApIDAAYAAAACkgMAAQUBAAEsAQABVQAADgAAAAEsCQABLAUAAjYDAAYAAAACNgMAASwFAAEsCQAPAAAAASwJAAEs" +
        "BQACkgMABgAAAAKSAwABLAUAASwJAA4AAAABVQAAASwBAAEFAQACNgMABgAAAAI2AwABBQEAASwBAAFVAAAOAAAAAW0EAAEFAQAC" +
        "kgMABgAAAAKSAwABBQEAAW0FAA4AAAABVQAAASwBAAMFAQABkgUABAAAAAE2BQADBQEAASwBAAFVAAAOAAAAASwJAAEsDQACBQEA" +
        "AZIFAAE2BQACAAAAAZIEAAE2BQACBQEAASwNAAEsCQASAAAAAgUBAAE2BQABkgUAATYEAAGSBAACBQEAFAAAAAFVAAABAAAAASwN" +
        "AAEFAQABkgUAATYEAAEFAQABLA0AAQAAAAFVAAAVAAAAAQEGAAEAAAACAQYAAQAAAAEBBgAZAAAAAlUAAQMAAAACVQAAGAAAAAEs" +
        "DQABAQYAAW0GAAIBBgABbQYAAQEGAAEsDQAUAAAAAVUAAAFtBAABAQYAAQUBAAE2BQABkgUAAQUBAAEBBgABbQUAAVUAABEAAAAB" +
        "LAkAAW0GAAIBBgABBQEAAZIFAAE2BQABkgUAATYEAAEFAQACAQYAAW0GAAEsCQAPAAAAARgBAAEBBgACBQEAATYFAAGSBQACAAAA" +
        "ATYEAAGSBQACBQEAAQEGAAEYAQAOAAAAAVUAAAEsDQADBQEAATYFAAQAAAABkgUAAwUBAAEsDQABVQAADgAAAAFtAAABBQEAAjYD" +
        "AAYAAAACNgMAAQUBAAFtAQAOAAAAAVUAAAEsDQABBQEAApIDAAYAAAACkgMAAQUBAAEsDQABVQAADgAAAAEYAQACNgMACAAAAAI2" +
        "AwABGAEADwAAAAEYAQACkgIACAAAAAKSAgABGAEADgAAAAFVAAABLA0AAQUBAAI2AwAGAAAAAjYDAAEFAQABLA0AAVUAAA4AAAAB" +
        "bQAAAQUBAAKSAwAGAAAAApIDAAEFAQABbQEADgAAAAFVAAABLA0AAwUBAAGSBQAEAAAAATYFAAMFAQABLA0AAVUAAA4AAAABGAEA" +
        "AQEGAAIFAQABkgUAATYFAAIAAAABkgUAATYFAAIFAQABAQYAARgBAA8AAAABLAkAAW0HAAIBBgABBQEAATYFAAGSBQABNgUAAZIF" +
        "AAEFAQACAQYAAW0HAAEsCQARAAAAAVUAAAFtBAABAQYAAQUBAAGSBQABNgUAAQUBAAEBBgABbQUAAVUAABQAAAABLA0AAQEGAAFt" +
        "BwACAQYAAW0HAAEBBgABLA0AGAAAAAJVAAECAAAAAWAMAAIsAQABYAwAFgAAAAIsAQAGGAIAAiwBABIAAAABLAEAAhgCAAEAAAAB" +
        "BQEAAgAAAAIFAQACGAIAASwBABAAAAABLAUAARgCAAEAAAACBQEABAAAAAIFAQABAAAAARgCAAEsBQAOAAAAASwFAAEYAgACAAAA" +
        "AQUBAAYAAAADBQEAARgCAAEsBQANAAAAAYAEAAEYAQADBQEABgAAAAMFAQABGAEAAYAFAA0AAAABgAAAARgBAAEFAQAKAAAAAQUB" +
        "AAEYAQABgAEADQAAAAGABAABGAEAAQUBAAoAAAABBQEAARgBAAGABQANAAAAASwFAAErBQAMAAAAASsFAAEsBQANAAAAASwFAAEr" +
        "BQAMAAAAASsFAAEsBQANAAAAAYAEAAEYAQABBQEACgAAAAEFAQABGAEAAYAFAA0AAAABgAAAARgBAAEFAQAKAAAAAQUBAAEYAQAB" +
        "gAEADQAAAAGABAABGAEAAwUBAAYAAAADBQEAARgBAAGABQANAAAAASwFAAEYAgABAAAAAgUBAAYAAAADBQEAARgCAAEsBQAOAAAA" +
        "ASwFAAEYAgADBQEABAAAAAMFAQABGAIAASwFABAAAAABLAEAAhgCAAIFAQACAAAAAgUBAAIYAgABLAEAEgAAAAIsAQAGGAIAAiwB" +
        "ABYAAAABYA0AAiwBAAFgDQEBAAAABCwFABgAAAABLAUABCsFAAEsBQAVAAAAAiwFAAZhAgACLAUAEgAAAAEsBQAKYQIAASwFABAA" +
        "AAABLAUAA2ECAAVfCAAEYQIAASwFAA4AAAABLAUAASsFAANhAgAFXwgABGECAAErBQABLAUADgAAAAEsDQADYQIABV8IAARhAgAB" +
        "LA0ADgAAAAEsBQABKwUAA2ECAAVfCAAEYQIAASsFAAEsBQAOAAAAASwFAANhAgAFXwgABGECAAEsBQAPAAAAASwFAANhAgAFXwgA" +
        "BGECAAEsBQAOAAAAASwFAAErBQADYQIABV8IAARhAgABKwUAASwFAA4AAAABLA0AA2ECAAVfCAAEYQIAASwNAA4AAAABLAUAASsF" +
        "AANhAgAFXwgABGECAAErBQABLAUADgAAAAEsBQADYQIABV8IAARhAgABLAUAEAAAAAEsBQAEYQIAAl8IAARhAgABLAUAEgAAAAIs" +
        "BQAGYQIAAiwFABUAAAABLAUABCsFAAEsBQAYAAAABCwFAVgAAAAELAUAGAAAAAEsBQABYQIAAgAAAAFhAgAYAAAAASwFAARhAgAY" +
        "AAAAASwFAAFhAgACAAAAAWECABgAAAABLAUAA2ECAAFfCAABLAUAFwAAAAEsBQABXwgAAgAAAAFhAgABKwUAFwAAAAJhAgACAAAA" +
        "AWECAAErBQAXAAAAASwFAAFfCAACYQIAAV8IAAEsBQAXAAAAASwFAARhAgAYAAAAASwFAARhAgAYAAAAASwFAARhAgAYAAAAAiwF" +
        "AAJhAgACLAUBzAAAAAIsBQA3AAAAAWECAAIsBQABYQIAGQAAAAFhAgACAAAAAWECABkAAAABYQIAAiwNAAFhAgAZAAAABGECABkA" +
        "AAABYQIAAiwNAAFhAgAZAAAAAWECAAIAAAABYQIAGgAAAAJhAgEUAAA=");

    // MODERN_HCF: 17x9x17, 805 non-air cells; exact selected surface component.
    private static final Template MODERN_HCF=new Template(17,9,17,0,
        "AAECAAABAwAAApsAAAEDAAAFAgAAAQMAAAIFAQABAwAABAIAAAGbAAADBQEAAQMAAAMFAQACAwAAAwUBAAEDAAADAgAAAZsAAAcF" +
        "AQABAwAABAUBAAIDAAACAgAAAZsAAAIFAQABAwAABwUBAAKEAgABBQEAAZsAAAICAAABAwAACgUBAAKEAgABBQEAAZsAAAICAAAB" +
        "AwAAAgUBAAEDAAAEBQEAAQMAAAQFAQACAwAAAgIAAAEDAAACBQEAAgMAAAMFAQACAwAAAwUBAAEDAAABmwAAAgIAAAEDAAACAgAA" +
        "AQMAAAUFAQABAwAAAgUBAAEDAAABBQEAAZsAAAICAAABmwAADQUBAAGbAAACAgAAAZsAAAMFAQALmwAAAgIAAAGbAAADBQEAAZsA" +
        "AAmEAgABmwAAAgIAAAGbAAADBQEAAZsAAAmEAgABmwAAAgIAAAGbAAADBQEAAZsAAAmEAgABmwAAAgIAAAGbAAADBQEAAZsAAAmE" +
        "AgABmwAAAgIAAAGbAAADBQEAC5sAACMCAAABAAAAAZsAAAKgDwABmwAABQAAAAGfCQACoA8AAZ8JAAQAAAABoA8AAwAAAAEFAQAD" +
        "awQAAwUBAAGGAQABAAAAAQUBAAMAAAABoA8ABwAAAAEFAQABhgEAAwAAAAEFAQABmwAAAgAAAAGgDwACRAIAAZsAAAQAAAABawcA" +
        "BAAAAAEFAQADAAAAAZsAAAGSBQABNgQAAaAPAAQAAAABawcABAAAAAEFAQADAAAAAZsAAAGSBQABNgQAAZsAAAQAAAABBQEAAYYB" +
        "AAMAAAABBQEAAZsAAAIAAAABmwAAAn4JAAGbAAABBQEAA2sGAAMFAQABhgEAAQAAAAEFAQABLA8AAgAAAAGbAAACfgEAAZsAAAUA" +
        "AAABnwkAAqAPAAGfCQABAAAAASwPAAIAAAABLA8ADQAAAAEsDwACAAAAASwPAA0AAAABLA8AAgAAAAEsDwANAAAAASwPAAIAAAAB" +
        "LA8ADQAAAAEsDwACAAAAASwPAA0AAAABLA8AAgAAAAEsDwANAAAAASwPAAIAAAABmwAAAwAAAAGbAAAJLA8AAZsAAAYAAAACRAMA" +
        "HAAAAAGbAAACoA8AAZsAAAUAAAABnwkAAqAPAAGfCQAEAAAAAaAPAAMAAAABBQEAA2sEAAIFAQABhgEAAgAAAAEFAQADAAAAAaAP" +
        "AAcAAAABBQEABAAAAAEFAQABmwAAAgAAAAGbAAACAAAAAZsAAAQAAAABawcABAAAAAGgDwADAAAAAZsAAAJ+CQABoA8ABAAAAAFr" +
        "BwAEAAAAAaAPAAMAAAABmwAAAn4BAAGbAAAEAAAAAQUBAAQAAAABBQEAAZsAAAIAAAABLAcAAgAAAAEsBwABBQEAA2sGAAIFAQAB" +
        "hgEAAgAAAAEFAQAMAAAAAZ8JAAKgDwABnwkAnQAAAAGbAAACoA8AAZsAAAUAAAABnwkAAqAPAAGfCQAEAAAAAaAPAAN+CQAEBQEA" +
        "AX0BAAGGAQADAAAAAQUBAAMAAAABmwAAB34JAAEFAQAEAAAAAQUBAAGbAAACAAAAAZsAAAJ+AQABmwAABH4JAAEFAQAEAAAAAaAP" +
        "AAMAAAABLAcAAgAAAAGgDwAEfgkAAQUBAAQAAAABoA8ABgAAAAGbAAAEfgkAAQUBAAQAAAABBQEAAZsAAAYAAAAFBQEAAYYBAAMA" +
        "AAABBQEADAAAAAGfCQACoA8AAZ8JAJ0AAAAEmwAABZwGAAGfCQACoA8AAZ8JAAKcBgACAAAAAZsAAAIAAAABawcACQAAAAEFAQAB" +
        "nAUAAgAAAAEsBwACAAAAAWsHAAQAAAABBQEABAAAAAEFAQABmwAABQAAAAGbAAAEAAAAAQUBAAQAAAABhgQAAZsAAAUAAAABoA8A" +
        "BAAAAAEFAQAEAAAAAYYEAAGbAAAFAAAAAZsAAAQAAAABBQEABAAAAAEFAQABmwAABQAAAAGcBAAJAAAAAQUBAAGcBQAFAAAABpwH" +
        "AAGfCQACoA8AAZ8JAAGcBwABnAUAngAAAAGbAAAFoA8AAZ8JAAKgDwABnwkAAqAPAAUAAAABawcACgAAAAGgDwAFAAAAAWsHAAQA" +
        "AAABBQEABQAAAAGbAAAFAAAAAZsAAAQAAAABoA8ABQAAAAGgDwAFAAAAAaAPAAQAAAABoA8ABQAAAAGgDwAFAAAAAaAPAAQAAAAB" +
        "BQEABQAAAAGbAAAFAAAAAaAPAAoAAAABoA8ABQAAAAagDwABnwkAAqAPAAGfCQACoA8AngAAAAGbAAAFoA8AAZ8JAAKgDwABnwkA" +
        "AqAPAAUAAAABmwAACgAAAAGgDwAFAAAAAZsAAAQAAAABBQEABQAAAAGbAAAFAAAAAZsAAAQAAAABBQEABQAAAAGgDwAFAAAAAaAP" +
        "AAQAAAABBQEABQAAAAGgDwAFAAAAAaAPAAQAAAABBQEABQAAAAGbAAAFAAAAAaAPAAoAAAABoA8ABQAAAAagDwABnwkAAqAPAAGf" +
        "CQACoA8AnAAAAAEsDwAHmwAAAZ8JAAKbAAABnwkAA5sAAAIAAAABLA8ADpsAAAIAAAABLA8ACJsAAAJfDwAEmwAAAgAAAAEsDwAI" +
        "mwAAAl8PAASbAAACAAAAASwPAAibAAACXw8ABJsAAAIAAAABLA8ACJsAAAJfDwAEmwAAAgAAAAEsDwAOmwAAAgAAAAEsDwAHmwAA" +
        "AZ8JAAKbAAABnwkAA5sAAAIAAAABLA8ADpsAAAIAAAAPLA8AgQAAAASfCQANAAAABJ8JAA0AAAABnwkAAgAAAAGfCQANAAAAAZ8J" +
        "AAIAAAABnwkADQAAAAGfCQACAAAAAZ8JAA0AAAABnwkAAgAAAAGfCQANAAAABJ8JAA0AAAAEnwkAnAAA");

    // TUNNEL: 11x12x11, 447 non-air cells; exact selected surface component.
    private static final Template TUNNEL=new Template(11,12,11,1,
        "AAFtAAABEQAAAW0BAAUAAAABbQAAAREAAAFtAQABAAAAAW0DAAJiAAADawQAAmIAAAFtAwADAAAAAWIAAAUAAAABYgAABAAAAAFr" +
        "AwAFAAAAAWsBAAQAAAABawEABQAAAAFrAQAEAAAAAWsBAAUAAAABawMABAAAAAFiAAAFAAAAAWIAAAMAAAABbQIAAmIAAAJrAgAB" +
        "awYAAmIAAAFtAgABAAAAAW0AAAERAAABbQEABQAAAAFtAAABEQAAAW0BAAEAAAABbQMAASUAAAYAAAABbQMABAAAAAMfAQABAAAA" +
        "AR8BAAElAAACAAAAAY8CAAERAAAHAAAAAREAAAGPAQACAAAAAWIAAAFtAgADawQAAW0CAAFiAAAEAAAAAW0AAAUAAAABbQEABAAA" +
        "AAFrAwAFAAAAAWsBAAQAAAABawEABQAAAAFrAQAEAAAAAWsBAAUAAAABawMABAAAAAFtAAAFAAAAAW0BAAQAAAABYgAAAW0DAAJr" +
        "AgABawYAAW0DAAFiAAACAAAAAY8CAAERAAAHAAAAAREAAAGPAQABAAAAAY8DAAcAAAABjwMADAAAAAGPAgABEQAAATIEAAUAAAAB" +
        "MgQAAREAAAGPAQABAAAAATICAAFiAAABbQYAA2sEAAFtBgABYgAAATIBAAMAAAABbQQABQAAAAFtBQAEAAAAAWsDAAUAAAABawEA" +
        "BAAAAAFrAwAFAAAAAWsBAAQAAAABawMABQAAAAFrAQAEAAAAAW0EAAUAAAABbQUAAwAAAAEyAgABYgAAAW0HAANrAgABbQcAAWIA" +
        "AAEyAQABAAAAAY8CAAERAAABMgMABQAAAAEyAwABEQAAAY8BAAEAAAABjwMABwAAAAGPAwAMAAAAAY8CAAERAAABbQYABQAAAAFt" +
        "BgABEQAAAY8BAAEAAAABbQQAAWIAAAFtAgABbQYAAW0CAAFtBgABbQIAAWIAAAFtBQADAAAAAW0AAAUsDQABbQEABAAAAAFtBAAB" +
        "LA0AAwAAAAEsDQABbQUABAAAAAFtAAABLA0AAwAAAAEsDQABbQEABAAAAAFtBAABLA0AAwAAAAEsDQABbQUABAAAAAFtAAAFLA0A" +
        "AW0BAAMAAAABbQQAAWIAAAFtAwABbQcAAW0DAAFtBwABbQMAAWIAAAFtBQABAAAAAY8CAAERAAABbQcABQAAAAFtBwABEQAAAY8B" +
        "AAEAAAABjwMABwAAAAGPAwANAAAAASwFAAGPBAAFAAAAAY8EAAEsBQACAAAAAY8CAAERAAABbQIAAQAAAAFtAgABAAAAAW0CAAER" +
        "AAABjwEAAwAAAAFtAAABYgAAARQAAAFiAAABFAAAAWIAAAFtAQAFAAAAARQAAAMAAAABFAAABQAAAAFtAAABYgAAAwAAAAFiAAAB" +
        "bQEABQAAAAEUAAADAAAAARQAAAUAAAABbQAAAWIAAAEUAAABYgAAARQAAAFiAAABbQEAAwAAAAGPAgABEQAAAW0DAAEAAAABbQMA" +
        "AQAAAAFtAwABEQAAAY8BAAIAAAABLAUABgAAAAGPAwABLAUAGQAAAAGPBAAFAAAAAY8EAAMAAAABjwIAAREAAAJtBgABbQIAAm0G" +
        "AAERAAABjwEAAwAAAAFtBAAFYgAAAW0FAAQAAAABbQQAAWIAAAMAAAABYgAAAW0FAAQAAAABbQAAAWIAAAMAAAABYgAAAW0BAAQA" +
        "AAABbQQAAWIAAAMAAAABYgAAAW0FAAQAAAABbQQABWIAAAFtBQADAAAAAY8CAAERAAACbQcAAW0DAAJtBwABEQAAAY8BAAMAAAAB" +
        "jwMABQAAAAGPAwAaAAAAAY8EAAUAAAABjwQAAwAAAAGPAgABEQAAAW0CAAEAAAABbQYAAQAAAAFtAgABEQAAAY8BAAMAAAABbQAA" +
        "AWIAAAEUAAABYgAAARQAAAFiAAABbQEABQAAAAEUAAADLA0AARQAAAUAAAABbQQAAWIAAAEsDQABAAAAASwNAAFiAAABbQUABQAA" +
        "AAEUAAADLA0AARQAAAUAAAABbQAAAWIAAAEUAAABYgAAARQAAAFiAAABbQEAAwAAAAGPAgABEQAAAW0DAAEAAAABbQcAAQAAAAFt" +
        "AwABEQAAAY8BAAMAAAABjwMABQAAAAGPAwAlAAAAASwFAAIAAAABiwAAAQAAAAGPBAABLAUABAAAAAGPAgABEQAAAW0GAAFtAgAB" +
        "bQYAAREAAAGPAQAFAAAAAW0EAANiAAABbQUABQAAAAGLAAABbQAAAWIAAAEAAAABYgAAAW0BAAGLAAAFAAAAAW0EAANiAAABbQUA" +
        "BQAAAAGPAgABEQAAAW0HAAFtAwABbQcAAREAAAGPAQAEAAAAASwFAAGPAwABAAAAAYsAAAEAAAABjwMAASwFADMAAAABMgUAAQAA" +
        "AAGPBAAFAAAAAY8CAAERAAABbQYAAQAAAAFtBgABEQAAAY8BAAUAAAABbQQAAWIAAAEUAAABYgAAAW0FAAUAAAABMgUAAQAAAAEU" +
        "AAABAAAAARQAAAEAAAABMgUABQAAAAFtBAABYgAAARQAAAFiAAABbQUABQAAAAGPAgABEQAAAW0HAAEAAAABbQcAAREAAAGPAQAF" +
        "AAAAAY8DAAEAAAABMgUAAQAAAAGPAwA2AAAAAY8EAAUAAAABjwIAAREAAAFtAgABbQYAAW0CAAERAAABjwEABQAAAAFtAAACYgAA" +
        "ASwNAAFtAQAGAAAAAW0EAAFiAAABAAAAAWIAAAFtBQAGAAAAAW0AAANiAAABbQEABQAAAAGPAgABEQAAAW0DAAFtBwABbQMAAREA" +
        "AAGPAQAFAAAAAY8DAAMAAAABjwMAPQAAAAEsBQABbQYAAQAAAAFtBgABLAUABgAAAAFtBAADKwUAAW0FAAcAAAADKwUABwAAAAFt" +
        "BAADKwUAAW0FAAYAAAABLAUAAW0HAAEAAAABbQcAASwFAFQAAAABLAUAAQAAAAEsBQATAAAAASwFAAEAAAABLAUAOwAA");

    // CAVE: 13x12x13, 600 non-air cells; exact selected surface component.
    private static final Template CAVE=new Template(13,12,13,1,
        "AAEAAAABogEAATUCAAGiAQABNQEAAwAAAAE1AAABogEAATUCAAGiAQACAAAAATUAAAOfCwADawAAA58LAAE1AQACAAAAAaIBAAGf" +
        "CwAHAAAAAZ8LAAGiAQACAAAAATUDAAGfCwAHAAAAAZ8LAAE1AwADAAAAAWsHAAcAAAABawEABAAAAAFrAwAHAAAAAWsFAAQAAAAB" +
        "awEABwAAAAFrAwADAAAAATUCAAGfCwAHAAAAAZ8LAAE1AgACAAAAAaIBAAGfCwAHAAAAAZ8LAAGiAQACAAAAATUAAAOfCwADawIA" +
        "A58LAAE1AQACAAAAAaIBAAE1AwABogEABQAAAAGiAQABNQMAAaIBABwAAAABogEAAWAEAAGiAQAFAAAAAaIBAAFgBAABogEAAgAA" +
        "AAFgBgADnwsAA2sAAAOfCwABYAcAAgAAAAGiAQABnwsABwAAAAGfCwABogEAAgAAAAFNAgABnwsABwAAAAGfCwAEAAAAAWsDAAcA" +
        "AAABawEABAAAAAFrAQAHAAAAAWsBAAQAAAABawMABwAAAAFrAQADAAAAAU0CAAGfCwAHAAAAAZ8LAAMAAAABogEAAZ8LAAcAAAAB" +
        "nwsAAaIBAAIAAAABYA4AA58LAANrAgADnwsAAWAHAAIAAAABogEAAWANAAGiAQAFAAAAAaIBAAFgBQABogEAHAAAAAGiAQABNQYA" +
        "AaIBAAE1BQADAAAAATUEAAGiAQABNQYAAaIBAAIAAAABNQQAA58LAANrAAADnwsAATUFAAIAAAABogEAAZ8LAAcAAAABnwsAAaIB" +
        "AAIAAAABNQcAAZ8LAAcAAAABnwsAATUHAAMAAAABawMABwAAAAFrAQAEAAAAAWsBAAcAAAABawEABAAAAAFrAwAHAAAAAWsBAAMA" +
        "AAABNQYAAZ8LAAcAAAABnwsAATUGAAIAAAABogEAAZ8LAAcAAAABnwsAAaIBAAIAAAABNQQAA58LAANrAAADnwsAATUFAAIAAAAB" +
        "ogEAATUHAAGiAQAFAAAAAaIBAAE1BwABogEAGwAAAAGiBQABogEACaIFAAGiCQABogUAAQAAAAGiCQAEnwsAAQUAAASfCwABogkA" +
        "AgAAAAGiCQABnwsABwAAAAGfCwABogkAAgAAAAGiCQABnwsABwAAAAGfCwABogkAAgAAAAGiCQABnwsABwAAAAGfCwABogkAAgAA" +
        "AAGiCQABBQAABwAAAAEFAAABogkAAgAAAAGiCQABnwsABwAAAAGfCwABogkAAgAAAAGiCQABnwsABwAAAAGfCwABogkAAgAAAAGi" +
        "CQABnwsABwAAAAGfCwABogkAAgAAAAGiCQAEnwsAAQUAAASfCwABogkAAQAAAAGiBQABogEACaIFAAGiAQABogUAAQAAAAGiCQAJ" +
        "AAAAAaIJAAIAAAABTQMACQAAAAFNAwACAAAAAX4AAAGiCQAHAAAAAaIJAAF+AAABAAAAAU0CAAGiBQABogEAAjUCAAGiAQABNQIA" +
        "AaIBAAI1AgABogEAAaIFAAFNAQACAAAAATUAAAdfCgABNQEABAAAAAE1AAAHXwoAATUBAAQAAAABogEAB18KAAGiAQAEAAAAATUE" +
        "AAdfCgABNQEABAAAAAGiAQAHXwoAAaIBAAQAAAABNQAAB18KAAE1AQAEAAAAATUAAAdfCgABNQEAAgAAAAFNAgABogUAAaIBAAI1" +
        "AwABogEAATUDAAGiAQACNQMAAaIBAAGiBQABTQEAAQAAAAF+AAABogkABwAAAAGiCQABfgAAAwAAAAFNAwAHAAAAAU0DAB4AAAAB" +
        "ogEAAmAEAAGiAQABVQAAAaIBAAJgBAABogEABAAAAAFgBgACnwsAAwAAAAKfCwABYAcABAAAAAFgBgABnwsABQAAAAGfCwABYAcA" +
        "BAAAAAGiAQAHAAAAAaIBAAQAAAABVQAABwAAAAFVAAAEAAAAAaIBAAcAAAABogEABAAAAAFgBgABnwsABQAAAAGfCwABYAcABAAA" +
        "AAFgBgACnwsAAwAAAAKfCwABYAcABAAAAAGiAQACYAUAAaIBAAFVAAABogEAAmAFAAGiAQAuAAAAATUGAAEAAAABNQYABwAAAAGi" +
        "AQACNQYAAaIBAAE1AgABogEAAjUGAAGiAQAEAAAAATUEAAcAAAABNQUABAAAAAE1BAAHAAAAATUFAAMAAAABNQQAAaIBAAcAAAAB" +
        "ogEAATUFAAMAAAABNQAABwAAAAE1AQADAAAAATUEAAGiAQAHAAAAAaIBAAE1BQADAAAAATUEAAcAAAABNQUABAAAAAE1BAAHAAAA" +
        "ATUFAAQAAAABogEAAjUHAAGiAQABNQMAAaIBAAI1BwABogEABwAAAAE1BwABAAAAATUHACEAAAABogkABzUCAAGiCQACAAAAAU0C" +
        "AAGiBQABogEAAgAAAAGiAQABNQIAAaIBAAIAAAABogEAAaIFAAFNAQABAAAAATUAAAEFAAAIAAAAATUBAAIAAAABNQAAAQUAAAgA" +
        "AAABNQEAAgAAAAE1AAABogEABwAAAAGiAQABNQEAAgAAAAE1AAABBQAABwAAAAI1AQACAAAAATUAAAGiAQAHAAAAAaIBAAE1AQAC" +
        "AAAAATUAAAEFAAAIAAAAATUBAAIAAAABNQAAAQUAAAgAAAABNQEAAQAAAAFNAgABogUAAaIBAAIAAAABogEAATUDAAGiAQACAAAA" +
        "AaIBAAGiBQABTQEAAgAAAAGiCQAHNQMAAaIJAAQAAAABTQMABwAAAAFNAwAeAAAAAaIBAAI1AgABogEAATUCAAGiAQACNQIAAaIB" +
        "AAQAAAABNQAABwAAAAE1AQAEAAAAATUAAAcAAAABNQEABAAAAAGiAQAHAAAAAaIBAAQAAAABNQAABwAAAAE1AQAEAAAAAaIBAAcA" +
        "AAABogEABAAAAAE1AAAHAAAAATUBAAQAAAABNQAABwAAAAE1AQAEAAAAAaIBAAI1AwABogEAATUDAAGiAQACNQMAAaIBADgAAAAB" +
        "fgEAAgAAAAF+AQABAAAAAX4BAAIAAAABfgEABQAAAAc1AgAGAAAAATUAAAGiAQABXwYAAV8KAAFfBgABogEAATUBAAUAAAABfgEA" +
        "ATUAAAFfBgABXwoAAaIJAAFfCgABXwYAATUBAAF+AQAFAAAAATUAAAFfCgABogUAAV8GAAGiBQABXwoAATUBAAUAAAABfgEAATUA" +
        "AAFfBgABXwoAAaIJAAFfCgABXwYAATUBAAF+AQAFAAAAATUAAAGiAQABXwYAAV8KAAFfBgABogEAATUBAAYAAAAGNQMAATUBAAUA" +
        "AAABfgEAAgAAAAF+AQABAAAAAX4BAAIAAAABfgEAVQAAAAF+AQABAAAAAX4BAAkAAAACfgEAAQAAAAJ+AQAVAAAAAn4BAAEAAAAC" +
        "fgEACQAAAAF+AQABAAAAAX4BAO8AAA==");

    static Template forFamily(int family) {
        switch(family) {
            case 0: return REDEMPTION;
            case 1: return BASE_HCF;
            case 2: return MODERN_HCF;
            case 3: return TUNNEL;
            case 4: return CAVE;
            default: return BASE_HCF;
        }
    }

    static int paletteVariant(HcfBasePlan plan) {
        if(plan==null || plan.faction==null) return 0;

        // Explicit visual palette proofs. These prefixes are QA-only and never
        // occur in normal simulated faction names.
        if(plan.faction.startsWith("QAPaletteCyan")) return 1;
        if(plan.faction.startsWith("QAPaletteArctic")) return 2;
        if(plan.faction.startsWith("QAPaletteRed")) return 3;
        if(plan.faction.startsWith("QAPaletteSmoke")) return 4;

        // The canonical five-family QA factions remain byte-for-byte exact.
        if(plan.faction.startsWith("QA")) return 0;

        int roll=Math.abs((plan.seed/131)%3);
        // Production never uses the literal reference palette. Several source
        // schematics contain mass quartz / biome-specific blocks that are fine
        // as visual references but poor SOTW requirements. Variant 0 is reserved
        // for byte-exact canonical QA; real factions always get a common-material
        // palette while retaining identical voxel geometry.
        switch(plan.primaryFamily) {
            case 0: return roll==0?4:(roll==1?3:1); // smoke / redline / cyan
            case 1: return roll==0?4:(roll==1?1:2); // smoke / cyan / arctic
            case 2: return roll==0?1:(roll==1?2:4); // cyan / arctic / smoke
            case 3: return roll==0?1:(roll==1?4:3); // cyan / smoke / redline
            case 4: return roll==0?1:(roll==1?4:3); // cyan / smoke / redline
            default:return 4;
        }
    }

    static String paletteName(HcfBasePlan plan) {
        switch(paletteVariant(plan)) {
            case 1:return "CYAN_CHARCOAL";
            case 2:return "ARCTIC_BLUE";
            case 3:return "RED_BLACK_WHITE";
            case 4:return "SMOKE_GRAY";
            default:return "REFERENCE";
        }
    }

    private static boolean neutralDye(int data) {
        return data==0 || data==7 || data==8 || data==15;
    }

    /**
     * Era-compatible color variation. Geometry and block placement never move:
     * only glass and dyed accent blocks are recolored. The exact source palette
     * remains variant 0 and is always used by canonical visual QA.
     */
    private static Material paletteMaterial(HcfBasePlan plan,Material material) {
        int variant=paletteVariant(plan);
        if(variant==0 || material==null) return material;
        int id=material.getId();
        if(id==20) return Material.getMaterial(95);   // glass -> stained glass
        if(id==102) return Material.getMaterial(160); // pane -> stained pane

        // Production palette variants must be realistic SOTW builds. Replace
        // mass quartz and biome-/tool-gated structural blocks with common 1.8
        // equivalents while preserving the exact reference voxel geometry.
        // Canonical REFERENCE QA remains untouched.
        if(id==24 || id==97 || id==155) return Material.SMOOTH_BRICK;
        if(id==128 || id==156) return Material.SMOOTH_STAIRS;
        if(id==159) return Material.WOOL;
        if(id==162) return Material.LOG;
        if(id==134 || id==135 || id==136 || id==163 || id==164) return Material.WOOD_STAIRS;
        if(id>=183 && id<=187) return Material.FENCE_GATE;
        if(id>=188 && id<=192) return Material.FENCE;
        return material;
    }

    private static byte paletteData(HcfBasePlan plan,Material source,byte data) {
        int variant=paletteVariant(plan);
        if(variant==0 || source==null) return data;

        int id=source.getId();

        // Normalize metadata when a material family is replaced. Stair
        // orientation remains valid across stair types; LOG_2 needs only its
        // axis bits when converted to oak LOG; stone-brick replacements must
        // not accidentally become mossy/cracked variants because source quartz
        // used metadata for a different purpose.
        if(id==24 || id==97 || id==155) return (byte)0;
        if(id==162) return (byte)(data&0x0c);
        if(id>=183 && id<=192) return (byte)0;

        boolean glass=id==20 || id==95 || id==102 || id==160;
        boolean dyed=id==35 || id==159 || id==171;
        if(!glass && !dyed) return data;

        int d=data&0xff;

        // Clear source glass is a major HCF architectural surface, not a neutral
        // trim pixel. Give it the primary glass tone of the selected palette.
        if(id==20 || id==102) {
            switch(variant) {
                case 1:return (byte)9;  // cyan
                case 2:return (byte)3;  // light blue
                case 3:return (byte)14; // red
                case 4:return (byte)8;  // light gray smoke
                default:return data;
            }
        }

        switch(variant) {
            case 1: // Cyan + charcoal/light-gray framing.
                if(neutralDye(d)) return (byte)(d==15?7:(d==0?8:d));
                return (byte)9;
            case 2: // Light-blue/cyan + white/light-gray.
                if(d==15 || d==7) return (byte)8;
                if(d==0 || d==8) return (byte)0;
                return (byte)(d==9?9:3);
            case 3: // Competitive red / black / white.
                if(d==15 || d==7) return (byte)15;
                if(d==0 || d==8) return (byte)0;
                return (byte)14;
            case 4: // Smoke gray / light gray.
                if(d==15) return (byte)15;
                if(d==0 || d==8) return (byte)8;
                return (byte)7;
            default:
                return data;
        }
    }

    /**
     * Exact finished-block bill for the selected surface template AFTER the
     * production palette substitution. Keys include data when color/orientation
     * matters (e.g. STAINED_GLASS:9). AIR is excluded.
     */
    static java.util.Map<String,Integer> materialBill(HcfBasePlan plan) {
        java.util.Map<String,Integer> out=new java.util.LinkedHashMap<String,Integer>();
        Template t=forFamily(plan.primaryFamily);
        int cursor=0,total=t.width*t.height*t.length;

        for(int i=0;i+3<t.rle.length;i+=4) {
            int count=((t.rle[i]&0xff)<<8)|(t.rle[i+1]&0xff);
            int id=t.rle[i+2]&0xff;
            byte data=t.rle[i+3];
            Material src=Material.getMaterial(id);
            if(src==null) src=Material.AIR;
            Material placed=paletteMaterial(plan,src);
            byte placedData=paletteData(plan,src,data);

            for(int n=0;n<count && cursor<total;n++,cursor++) {
                if(placed==Material.AIR) continue;
                String key=placed.name()+":"+((int)placedData&0xff);
                Integer old=out.get(key);
                out.put(key,old==null?1:old+1);
            }
        }
        return out;
    }

    /**
     * Raw/common-resource acquisition bill for the exact finished surface bill.
     * [woodLogs, stoneFamilyBlocks, ironIngots, obsidian, rawGlass, dyeItems]
     *
     * It intentionally rounds crafting inputs UP so the faction never starts a
     * build one item short. Dyed glass uses one dye per eight raw glass.
     */
    static int[] acquisitionBill(HcfBasePlan plan) {
        return acquisitionBillFromMaterialBill(materialBill(plan));
    }

    static int[] acquisitionBillFromMaterialBill(java.util.Map<String,Integer> bill) {
        int woodPlanks=0,stone=0,iron=0,obsidian=0,glassBlocks=0,glassPanes=0;

        for(java.util.Map.Entry<String,Integer> e:bill.entrySet()) {
            String k=e.getKey();
            int n=e.getValue();
            int split=k.indexOf(':');
            String m=split<0?k:k.substring(0,split);

            if(m.equals("LOG")||m.equals("LOG_2")) woodPlanks+=n*4;
            else if(m.equals("WOOD")) woodPlanks+=n;
            else if(m.equals("FENCE_GATE")||m.endsWith("_FENCE_GATE")) woodPlanks+=n*4;
            else if(m.equals("FENCE")||m.endsWith("_FENCE")) woodPlanks+=(int)Math.ceil(n*(5.0/3.0));
            else if(m.contains("WOOD_STAIRS")) woodPlanks+=(int)Math.ceil(n*1.5);
            else if(m.equals("WOOD_STEP")) woodPlanks+=(int)Math.ceil(n*0.5);
            else if(m.equals("WOOD_DOUBLE_STEP")) woodPlanks+=n;
            else if(m.equals("TRAP_DOOR")) woodPlanks+=n*3;
            else if(m.equals("LADDER")) woodPlanks+=((n+2)/3)*4;
            else if(m.equals("WOOD_BUTTON")) woodPlanks+=n;
            else if(m.equals("CHEST")||m.equals("TRAPPED_CHEST")) woodPlanks+=n*8;
            else if(m.equals("WORKBENCH")) woodPlanks+=n*4;
            else if(m.equals("SIGN_POST")||m.equals("WALL_SIGN")) woodPlanks+=n*2;
            else if(m.equals("WALL_BANNER")||m.equals("STANDING_BANNER")) woodPlanks+=n;

            if(m.equals("STONE")||m.equals("COBBLESTONE")||m.equals("SMOOTH_BRICK")||
               m.equals("BRICK")||m.equals("SMOOTH_STAIRS")||m.equals("COBBLESTONE_STAIRS")||
               m.equals("STEP")||m.equals("DOUBLE_STEP")||m.equals("STONE_PLATE")||
               m.equals("COBBLE_WALL")||m.equals("STONE_BUTTON")) stone+=n;
            else if(m.equals("FURNACE")) stone+=n*8;

            if(m.equals("IRON_BLOCK")) iron+=n*9;
            else if(m.equals("IRON_FENCE")) iron+=(int)Math.ceil(n*0.375);
            else if(m.equals("HOPPER")) iron+=n*5;
            else if(m.equals("IRON_DOOR_BLOCK")||m.equals("IRON_DOOR")) iron+=(int)Math.ceil(n/3.0)*6;
            else if(m.equals("ANVIL")) iron+=n*31;
            else if(m.equals("CAULDRON")) iron+=n*7;
            else if(m.equals("IRON_PLATE")) iron+=n*2;

            if(m.equals("OBSIDIAN")) obsidian+=n;
            if(m.equals("GLASS")) glassBlocks+=n;
            else if(m.equals("THIN_GLASS")) glassPanes+=n;
            else if(m.equals("STAINED_GLASS")) glassBlocks+=n;
            else if(m.equals("STAINED_GLASS_PANE")) glassPanes+=n;
        }

        int rawGlass=glassBlocks+(int)Math.ceil(glassPanes*6.0/16.0);
        int dye=0;
        for(Integer n:dyeSupplyBillFromMaterialBill(bill).values()) dye+=n==null?0:n;
        int logs=(int)Math.ceil(woodPlanks/4.0);
        return new int[]{logs,stone,iron,obsidian,rawGlass,dye};
    }

    private static void addSupply(java.util.Map<String,Integer> out,String key,int amount) {
        if(out==null || key==null || key.isEmpty() || amount<=0) return;
        Integer old=out.get(key);
        out.put(key,(old==null?0:old)+amount);
    }

    private static int dataFromBillKey(String key) {
        if(key==null) return 0;
        int split=key.indexOf(':');
        if(split<0 || split+1>=key.length()) return 0;
        try { return Integer.parseInt(key.substring(split+1)); }
        catch(Exception ignored) { return 0; }
    }

    private static String dyeKeyForBlockData(int data) {
        switch(data&15) {
            case 15:return "dyeblack";
            case 14:return "dyered";
            case 9:return "dyecyan";
            case 8:return "dyelightgray";
            case 7:return "dyegray";
            case 3:return "dyelightblue";
            case 0:return "dyewhite";
            default:return "dyewhite";
        }
    }

    static java.util.Map<String,Integer> dyeSupplyBill(HcfBasePlan plan) {
        return dyeSupplyBillFromMaterialBill(materialBill(plan));
    }

    static java.util.Map<String,Integer> dyeSupplyBillFromMaterialBill(java.util.Map<String,Integer> bill) {
        java.util.Map<String,Integer> out=new java.util.LinkedHashMap<String,Integer>();
        java.util.Map<Integer,Integer> coloredGlassRaw=new java.util.LinkedHashMap<Integer,Integer>();

        for(java.util.Map.Entry<String,Integer> e:bill.entrySet()) {
            String k=e.getKey();
            int n=e.getValue();
            int split=k.indexOf(':');
            String m=split<0?k:k.substring(0,split);
            int data=dataFromBillKey(k)&15;

            if(m.equals("STAINED_GLASS")) {
                Integer old=coloredGlassRaw.get(data);
                coloredGlassRaw.put(data,(old==null?0:old)+n);
            } else if(m.equals("STAINED_GLASS_PANE")) {
                int raw=(int)Math.ceil(n*6.0/16.0);
                Integer old=coloredGlassRaw.get(data);
                coloredGlassRaw.put(data,(old==null?0:old)+raw);
            } else if(m.equals("WOOL") && data!=0) {
                addSupply(out,dyeKeyForBlockData(data),n);
            }
        }

        for(java.util.Map.Entry<Integer,Integer> e:coloredGlassRaw.entrySet())
            addSupply(out,dyeKeyForBlockData(e.getKey()),(int)Math.ceil(e.getValue()/8.0));
        return out;
    }

    /**
     * Exact just-in-time shop bill for small/common surface supplies that are
     * deliberately not promoted to full SimFaction inventory fields. Every
     * finished material remains visible in materialBill(); this map only tells
     * the economy which raw items must be bought at build time.
     */
    static java.util.Map<String,Integer> specialtySupplyBill(HcfBasePlan plan) {
        return specialtySupplyBillFromMaterialBill(materialBill(plan));
    }

    static java.util.Map<String,Integer> specialtySupplyBillFromMaterialBill(java.util.Map<String,Integer> bill) {
        java.util.Map<String,Integer> out=new java.util.LinkedHashMap<String,Integer>();

        for(java.util.Map.Entry<String,Integer> e:bill.entrySet()) {
            String k=e.getKey();
            int n=e.getValue();
            int split=k.indexOf(':');
            String m=split<0?k:k.substring(0,split);

            if(m.equals("GRASS")||m.equals("DIRT")) addSupply(out,"dirt",n);
            else if(m.equals("SAND")) addSupply(out,"sand",n);
            else if(m.equals("GRAVEL")) addSupply(out,"gravel",n);
            else if(m.equals("LEAVES")||m.equals("LEAVES_2")) addSupply(out,"leaves",n);
            else if(m.equals("LONG_GRASS")) addSupply(out,"longgrass",n);
            else if(m.equals("YELLOW_FLOWER")) addSupply(out,"yellowflower",n);
            else if(m.equals("RED_ROSE")) addSupply(out,"redrose",n);
            else if(m.equals("WOOL")) addSupply(out,"wool",n);
            else if(m.equals("TORCH")) addSupply(out,"coal",(n+3)/4);
            else if(m.equals("TRIPWIRE")) addSupply(out,"string",n);
            else if(m.equals("GLOWSTONE")) addSupply(out,"glowstone",n*4);
            else if(m.equals("REDSTONE_LAMP_ON")||m.equals("REDSTONE_LAMP_OFF")) {
                addSupply(out,"glowstone",n*4);
                addSupply(out,"redstone",n*4);
            } else if(m.equals("REDSTONE_BLOCK")) addSupply(out,"redstone",n*9);
            else if(m.equals("REDSTONE_TORCH_ON")||m.equals("REDSTONE_TORCH_OFF"))
                addSupply(out,"redstone",n);
            else if(m.equals("WALL_BANNER")||m.equals("STANDING_BANNER"))
                addSupply(out,"wool",n*6);
        }
        return out;
    }

    static String dyeShopKey(HcfBasePlan plan) {
        switch(paletteVariant(plan)) {
            case 1:return "dyecyan";
            case 2:return "dyelightblue";
            case 3:return "dyered";
            case 4:return "dyelightgray";
            default:return "";
        }
    }

    static int width(int family) { return forFamily(family).width; }
    static int height(int family) {
        Template t=forFamily(family);
        return t.height+t.yOffset;
    }
    static int length(int family) { return forFamily(family).length; }

    // Primary player/bot entrance center measured from the same selected
    // schematic components. Offsets are relative to the plan center; Y is
    // relative to surfaceY. These are gate-panel cells, not bounding-box edges.
    static int primaryGateOffsetX(int family) {
        switch(family) {
            case 0: return 4;   // Redemption recessed 2x3 lower gate sheet
            case 1: return -1;  // Base-HCF north 2x2 gate
            case 2: return -1;  // Modern north 3x2 gate
            case 3: return 0;   // Tunnel north 3x3 gate
            case 4: return 0;   // Devhorah north 3x3 gate
            default: return 0;
        }
    }

    static int primaryGateOffsetZ(int family) {
        switch(family) {
            case 0: return -2;
            case 1: return -8;
            case 2: return -7;
            case 3: return -4;
            case 4: return -5;
            default: return 0;
        }
    }

    static int primaryGateOffsetY(int family) {
        // Redemption's lower gate panel begins two blocks above its reference
        // floor; all other selected primary gate sheets begin one above grade
        // after their template vertical offsets are applied.
        return family==0?2:1;
    }

    /**
     * Compare the materialized above-grade reference component against the exact
     * encoded schematic voxels after every queued production operation has run.
     * The surface floor layer is excluded because the functional 3x3 dropdown
     * intentionally cuts that layer; every facade/roof/gate/glass voxel above
     * grade must remain block-and-data exact.
     */
    static String facadeMismatchSample(World world,HcfBasePlan plan) {
        Template t=forFamily(plan.primaryFamily);
        int originX=plan.cx-((t.width-1)/2);
        int originZ=plan.cz-((t.length-1)/2);
        int cursor=0;
        int total=t.width*t.height*t.length;
        StringBuilder out=new StringBuilder();
        int shown=0;

        for(int i=0;i+3<t.rle.length;i+=4) {
            int count=((t.rle[i]&0xff)<<8)|(t.rle[i+1]&0xff);
            int id=t.rle[i+2]&0xff;
            byte data=t.rle[i+3];

            for(int n=0;n<count && cursor<total;n++,cursor++) {
                int x=cursor%t.width;
                int q=cursor/t.width;
                int z=q%t.length;
                int y=q/t.length;
                int worldY=plan.surfaceY+t.yOffset+y;
                if(worldY<=plan.surfaceY) continue;

                org.bukkit.block.Block actual=world.getBlockAt(originX+x,worldY,originZ+z);
                if(actual.getTypeId()!=id || actual.getData()!=data) {
                    if(shown>0) out.append(" | ");
                    out.append("at=").append(originX+x).append(",").append(worldY).append(",").append(originZ+z)
                        .append(" expected=").append(id).append(":").append(data&0xff)
                        .append(" actual=").append(actual.getTypeId()).append(":").append(actual.getData()&0xff);
                    shown++;
                    if(shown>=16) return out.toString();
                }
            }
        }
        return out.toString();
    }

    static int facadeMismatches(World world,HcfBasePlan plan) {
        Template t=forFamily(plan.primaryFamily);
        int originX=plan.cx-((t.width-1)/2);
        int originZ=plan.cz-((t.length-1)/2);
        int cursor=0;
        int total=t.width*t.height*t.length;
        int mismatches=0;

        for(int i=0;i+3<t.rle.length;i+=4) {
            int count=((t.rle[i]&0xff)<<8)|(t.rle[i+1]&0xff);
            int id=t.rle[i+2]&0xff;
            byte data=t.rle[i+3];

            for(int n=0;n<count && cursor<total;n++,cursor++) {
                int x=cursor%t.width;
                int q=cursor/t.width;
                int z=q%t.length;
                int y=q/t.length;

                int worldY=plan.surfaceY+t.yOffset+y;
                if(worldY<=plan.surfaceY) continue;

                org.bukkit.block.Block actual=world.getBlockAt(originX+x,worldY,originZ+z);
                if(actual.getTypeId()!=id || actual.getData()!=data) mismatches++;
            }
        }
        return mismatches;
    }

    /**
     * Queue the exact selected surface component centered on the production
     * plan. RLE traversal order is Y, Z, X and includes AIR so old procedural
     * facade cells cannot survive a rebuild.
     */
    static void queue(ArrayDeque<HcfBaseBuilder.Op> queue,World world,HcfBasePlan plan) {
        Template t=forFamily(plan.primaryFamily);
        int originX=plan.cx-((t.width-1)/2);
        int originZ=plan.cz-((t.length-1)/2);
        int cursor=0;
        int total=t.width*t.height*t.length;

        for(int i=0;i+3<t.rle.length;i+=4) {
            int count=((t.rle[i]&0xff)<<8)|(t.rle[i+1]&0xff);
            int id=t.rle[i+2]&0xff;
            byte data=t.rle[i+3];
            Material sourceMaterial=Material.getMaterial(id);
            if(sourceMaterial==null) sourceMaterial=Material.AIR;
            Material material=paletteMaterial(plan,sourceMaterial);
            byte placedData=paletteData(plan,sourceMaterial,data);

            for(int n=0;n<count && cursor<total;n++,cursor++) {
                int x=cursor%t.width;
                int q=cursor/t.width;
                int z=q%t.length;
                int y=q/t.length;
                int worldY=plan.surfaceY+t.yOffset+y;

                // The schematic bounding box contains AIR at its ground plane.
                // Pasting that AIR would shave the authored FreeMap into a
                // rectangular cutout around the structure. Preserve native
                // terrain at/below grade when the reference voxel is AIR; solid
                // reference floor/foundation blocks still replace that column.
                if(material==Material.AIR && worldY<=plan.surfaceY) continue;

                queue.add(new HcfBaseBuilder.Op(world,originX+x,worldY,originZ+z,material,placedData));
            }
        }

        // Minecraft 1.8 performs a few state validations after placement even
        // when block physics is suppressed. Re-assert the small set of reference
        // cells that depend on supports/power/neighbors only AFTER the complete
        // template exists. This preserves the schematic's lit lamps, supported
        // wall torches and chest facing data instead of accepting runtime drift.
        cursor=0;
        for(int i=0;i+3<t.rle.length;i+=4) {
            int count=((t.rle[i]&0xff)<<8)|(t.rle[i+1]&0xff);
            int id=t.rle[i+2]&0xff;
            byte data=t.rle[i+3];
            boolean replay=id==50 || id==54 || id==124 || id==146;
            Material material=replay?Material.getMaterial(id):null;

            for(int n=0;n<count && cursor<total;n++,cursor++) {
                if(!replay || material==null) continue;
                int x=cursor%t.width;
                int q=cursor/t.width;
                int z=q%t.length;
                int y=q/t.length;
                int worldY=plan.surfaceY+t.yOffset+y;
                if(worldY<=plan.surfaceY) continue;
                queue.add(new HcfBaseBuilder.Op(world,originX+x,worldY,originZ+z,material,data));
            }
        }

        // A malformed template must fail visibly rather than silently leave a
        // partial shell. The encoded constants are compile-time data, so this
        // branch is only defensive against accidental future edits.
        if(cursor!=total) {
            throw new IllegalStateException("Incomplete HCF surface template family="+
                plan.primaryFamily+" decoded="+cursor+" expected="+total);
        }
    }
}